/*
Analyze V2.x Table and Index
Log file: C:\profiles\cablesoft\Tools\AnalyzeTable.log
指令1: analyze table
             analyze table ??? estimate statistics;
指令2: analyze index
             analyze index ??? estimate statistics;
指令3: check analyze status
             select table_name, last_analyzed  from user_tables order by Table_name;
*/




variable nn number
variable msg varchar2(200)
variable t1 varchar2(19)
variable t2 varchar2(19)
variable str varchar2(80)
variable tt number
variable hh number
variable mm number
variable ss number
set serveroutput on
set heading off
exec :t1 := to_char(sysdate, 'YYYY/MM/DD HH24:MI:SS')
exec :str := '<< 開始 Analyze >> ' || :t1
spool C:\profiles\cablesoft\Tools\AnalyzeTable.log
print str





prompt 正在處理 CD000...
analyze table CD000 compute statistics;

prompt 正在處理 CD001...
analyze table CD001 compute statistics;

prompt 正在處理 CD001A...
analyze table CD001A compute statistics;

prompt 正在處理 CD002...
analyze table CD002 compute statistics;

prompt 正在處理 CD002CM003...
analyze table CD002CM003 compute statistics;

prompt 正在處理 CD003...
analyze table CD003 compute statistics;

prompt 正在處理 CD004...
analyze table CD004 compute statistics;

prompt 正在處理 CD005...
analyze table CD005 compute statistics;

prompt 正在處理 CD006...
analyze table CD006 compute statistics;

prompt 正在處理 CD006A...
analyze table CD006A compute statistics;

prompt 正在處理 CD006B...
analyze table CD006B compute statistics;

prompt 正在處理 CD007...
analyze table CD007 compute statistics;

prompt 正在處理 CD008...
analyze table CD008 compute statistics;

prompt 正在處理 CD008A...
analyze table CD008A compute statistics;

prompt 正在處理 CD008B...
analyze table CD008B compute statistics;

prompt 正在處理 CD008C...
analyze table CD008C compute statistics;

prompt 正在處理 CD009...
analyze table CD009 compute statistics;

prompt 正在處理 CD010...
analyze table CD010 compute statistics;

prompt 正在處理 CD011...
analyze table CD011 compute statistics;

prompt 正在處理 CD011A...
analyze table CD011A compute statistics;

prompt 正在處理 CD011B...
analyze table CD011B compute statistics;

prompt 正在處理 CD012...
analyze table CD012 compute statistics;

prompt 正在處理 CD013...
analyze table CD013 compute statistics;

prompt 正在處理 CD014...
analyze table CD014 compute statistics;

prompt 正在處理 CD015...
analyze table CD015 compute statistics;

prompt 正在處理 CD016...
analyze table CD016 compute statistics;

prompt 正在處理 CD017...
analyze table CD017 compute statistics;

prompt 正在處理 CD018...
analyze table CD018 compute statistics;

prompt 正在處理 CD018TMP...
analyze table CD018TMP compute statistics;

prompt 正在處理 CD019...
analyze table CD019 compute statistics;

prompt 正在處理 CD019A...
analyze table CD019A compute statistics;

prompt 正在處理 CD019B...
analyze table CD019B compute statistics;

prompt 正在處理 CD019CD004...
analyze table CD019CD004 compute statistics;

prompt 正在處理 CD019SO017...
analyze table CD019SO017 compute statistics;

prompt 正在處理 CD020...
analyze table CD020 compute statistics;

prompt 正在處理 CD021...
analyze table CD021 compute statistics;

prompt 正在處理 CD022...
analyze table CD022 compute statistics;

prompt 正在處理 CD022A...
analyze table CD022A compute statistics;

prompt 正在處理 CD022CD019...
analyze table CD022CD019 compute statistics;

prompt 正在處理 CD023...
analyze table CD023 compute statistics;

prompt 正在處理 CD024...
analyze table CD024 compute statistics;

prompt 正在處理 CD025...
analyze table CD025 compute statistics;

prompt 正在處理 CD026...
analyze table CD026 compute statistics;

prompt 正在處理 CD027...
analyze table CD027 compute statistics;

prompt 正在處理 CD027A...
analyze table CD027A compute statistics;

prompt 正在處理 CD027B...
analyze table CD027B compute statistics;

prompt 正在處理 CD027C...
analyze table CD027C compute statistics;

prompt 正在處理 CD027D...
analyze table CD027D compute statistics;

prompt 正在處理 CD028...
analyze table CD028 compute statistics;

prompt 正在處理 CD029...
analyze table CD029 compute statistics;

prompt 正在處理 CD030...
analyze table CD030 compute statistics;

prompt 正在處理 CD031...
analyze table CD031 compute statistics;

prompt 正在處理 CD031A...
analyze table CD031A compute statistics;

prompt 正在處理 CD032...
analyze table CD032 compute statistics;

prompt 正在處理 CD033...
analyze table CD033 compute statistics;

prompt 正在處理 CD034...
analyze table CD034 compute statistics;

prompt 正在處理 CD035...
analyze table CD035 compute statistics;

prompt 正在處理 CD036...
analyze table CD036 compute statistics;

prompt 正在處理 CD037...
analyze table CD037 compute statistics;

prompt 正在處理 CD039...
analyze table CD039 compute statistics;

prompt 正在處理 CD040...
analyze table CD040 compute statistics;

prompt 正在處理 CD041...
analyze table CD041 compute statistics;

prompt 正在處理 CD042...
analyze table CD042 compute statistics;

prompt 正在處理 CD043...
analyze table CD043 compute statistics;

prompt 正在處理 CD044...
analyze table CD044 compute statistics;

prompt 正在處理 CD045...
analyze table CD045 compute statistics;

prompt 正在處理 CD046...
analyze table CD046 compute statistics;

prompt 正在處理 CD047...
analyze table CD047 compute statistics;

prompt 正在處理 CD048...
analyze table CD048 compute statistics;

prompt 正在處理 CD048A...
analyze table CD048A compute statistics;

prompt 正在處理 CD049...
analyze table CD049 compute statistics;

prompt 正在處理 CD050...
analyze table CD050 compute statistics;

prompt 正在處理 CD051...
analyze table CD051 compute statistics;

prompt 正在處理 CD052...
analyze table CD052 compute statistics;

prompt 正在處理 CD053...
analyze table CD053 compute statistics;

prompt 正在處理 CD054...
analyze table CD054 compute statistics;

prompt 正在處理 CD055...
analyze table CD055 compute statistics;

prompt 正在處理 CD056...
analyze table CD056 compute statistics;

prompt 正在處理 CD057...
analyze table CD057 compute statistics;

prompt 正在處理 CD057A...
analyze table CD057A compute statistics;

prompt 正在處理 CD058...
analyze table CD058 compute statistics;

prompt 正在處理 CD059...
analyze table CD059 compute statistics;

prompt 正在處理 CD060...
analyze table CD060 compute statistics;

prompt 正在處理 CD061...
analyze table CD061 compute statistics;

prompt 正在處理 CD062...
analyze table CD062 compute statistics;

prompt 正在處理 CD063...
analyze table CD063 compute statistics;

prompt 正在處理 CD064...
analyze table CD064 compute statistics;

prompt 正在處理 CD065...
analyze table CD065 compute statistics;

prompt 正在處理 CD065A...
analyze table CD065A compute statistics;

prompt 正在處理 CD066...
analyze table CD066 compute statistics;

prompt 正在處理 CD067A...
analyze table CD067A compute statistics;

prompt 正在處理 CD067B...
analyze table CD067B compute statistics;

prompt 正在處理 CD067C...
analyze table CD067C compute statistics;

prompt 正在處理 CD068...
analyze table CD068 compute statistics;

prompt 正在處理 CD069...
analyze table CD069 compute statistics;

prompt 正在處理 CHARGENOTE...
analyze table CHARGENOTE compute statistics;

prompt 正在處理 CM001...
analyze table CM001 compute statistics;

prompt 正在處理 CM002...
analyze table CM002 compute statistics;

prompt 正在處理 CM003...
analyze table CM003 compute statistics;

prompt 正在處理 CM004...
analyze table CM004 compute statistics;

prompt 正在處理 CM005...
analyze table CM005 compute statistics;

prompt 正在處理 CODELIST...
analyze table CODELIST compute statistics;

prompt 正在處理 CODEUSAGE...
analyze table CODEUSAGE compute statistics;

prompt 正在處理 CODE_CHECK1...
analyze table CODE_CHECK1 compute statistics;

prompt 正在處理 CODE_CHECK2...
analyze table CODE_CHECK2 compute statistics;

prompt 正在處理 SO001...
analyze table SO001 compute statistics;

prompt 正在處理 SO002...
analyze table SO002 compute statistics;

prompt 正在處理 SO002A...
analyze table SO002A compute statistics;

prompt 正在處理 SO003...
analyze table SO003 compute statistics;

prompt 正在處理 SO003Z...
analyze table SO003Z compute statistics;

prompt 正在處理 SO004...
analyze table SO004 compute statistics;

prompt 正在處理 SO005...
analyze table SO005 compute statistics;

prompt 正在處理 SO006...
analyze table SO006 compute statistics;

prompt 正在處理 SO007...
analyze table SO007 compute statistics;

prompt 正在處理 SO008...
analyze table SO008 compute statistics;

prompt 正在處理 SO009...
analyze table SO009 compute statistics;

prompt 正在處理 SO010...
analyze table SO010 compute statistics;

prompt 正在處理 SO011...
analyze table SO011 compute statistics;

prompt 正在處理 SO012...
analyze table SO012 compute statistics;

prompt 正在處理 SO013...
analyze table SO013 compute statistics;

prompt 正在處理 SO014...
analyze table SO014 compute statistics;

prompt 正在處理 SO015...
analyze table SO015 compute statistics;

prompt 正在處理 SO016...
analyze table SO016 compute statistics;

prompt 正在處理 SO017...
analyze table SO017 compute statistics;

prompt 正在處理 SO017A...
analyze table SO017A compute statistics;

prompt 正在處理 SO017TMP...
analyze table SO017TMP compute statistics;

prompt 正在處理 SO018...
analyze table SO018 compute statistics;

prompt 正在處理 SO019...
analyze table SO019 compute statistics;

prompt 正在處理 SO020...
analyze table SO020 compute statistics;

prompt 正在處理 SO021...
analyze table SO021 compute statistics;

prompt 正在處理 SO022...
analyze table SO022 compute statistics;

prompt 正在處理 SO023...
analyze table SO023 compute statistics;

prompt 正在處理 SO024...
analyze table SO024 compute statistics;

prompt 正在處理 SO025...
analyze table SO025 compute statistics;

prompt 正在處理 SO026...
analyze table SO026 compute statistics;

prompt 正在處理 SO027...
analyze table SO027 compute statistics;

prompt 正在處理 SO028...
analyze table SO028 compute statistics;

prompt 正在處理 SO029...
analyze table SO029 compute statistics;

prompt 正在處理 SO029A...
analyze table SO029A compute statistics;

prompt 正在處理 SO029_0730...
analyze table SO029_0730 compute statistics;

prompt 正在處理 SO030...
analyze table SO030 compute statistics;

prompt 正在處理 SO030A...
analyze table SO030A compute statistics;

prompt 正在處理 SO031...
analyze table SO031 compute statistics;

prompt 正在處理 SO032...
analyze table SO032 compute statistics;

prompt 正在處理 SO032BREAK...
analyze table SO032BREAK compute statistics;

prompt 正在處理 SO033...
analyze table SO033 compute statistics;

prompt 正在處理 SO033DEBT...
analyze table SO033DEBT compute statistics;

prompt 正在處理 SO034...
analyze table SO034 compute statistics;

prompt 正在處理 SO035...
analyze table SO035 compute statistics;

prompt 正在處理 SO036...
analyze table SO036 compute statistics;

prompt 正在處理 SO037...
analyze table SO037 compute statistics;

prompt 正在處理 SO038...
analyze table SO038 compute statistics;

prompt 正在處理 SO039...
analyze table SO039 compute statistics;

prompt 正在處理 SO040...
analyze table SO040 compute statistics;

prompt 正在處理 SO041...
analyze table SO041 compute statistics;

prompt 正在處理 SO042...
analyze table SO042 compute statistics;

prompt 正在處理 SO043...
analyze table SO043 compute statistics;

prompt 正在處理 SO044...
analyze table SO044 compute statistics;

prompt 正在處理 SO045...
analyze table SO045 compute statistics;

prompt 正在處理 SO046...
analyze table SO046 compute statistics;

prompt 正在處理 SO050...
analyze table SO050 compute statistics;

prompt 正在處理 SO051...
analyze table SO051 compute statistics;

prompt 正在處理 SO052...
analyze table SO052 compute statistics;

prompt 正在處理 SO053...
analyze table SO053 compute statistics;

prompt 正在處理 SO054...
analyze table SO054 compute statistics;

prompt 正在處理 SO055...
analyze table SO055 compute statistics;

prompt 正在處理 SO056...
analyze table SO056 compute statistics;

prompt 正在處理 SO057...
analyze table SO057 compute statistics;

prompt 正在處理 SO058...
analyze table SO058 compute statistics;

prompt 正在處理 SO059...
analyze table SO059 compute statistics;

prompt 正在處理 SO060...
analyze table SO060 compute statistics;

prompt 正在處理 SO061...
analyze table SO061 compute statistics;

prompt 正在處理 SO062...
analyze table SO062 compute statistics;

prompt 正在處理 SO063...
analyze table SO063 compute statistics;

prompt 正在處理 SO064...
analyze table SO064 compute statistics;

prompt 正在處理 SO065...
analyze table SO065 compute statistics;

prompt 正在處理 SO066...
analyze table SO066 compute statistics;

prompt 正在處理 SO067...
analyze table SO067 compute statistics;

prompt 正在處理 SO068...
analyze table SO068 compute statistics;

prompt 正在處理 SO069...
analyze table SO069 compute statistics;

prompt 正在處理 SO070...
analyze table SO070 compute statistics;

prompt 正在處理 SO071...
analyze table SO071 compute statistics;

prompt 正在處理 SO072...
analyze table SO072 compute statistics;

prompt 正在處理 SO073...
analyze table SO073 compute statistics;

prompt 正在處理 SO074...
analyze table SO074 compute statistics;

prompt 正在處理 SO075...
analyze table SO075 compute statistics;

prompt 正在處理 SO076...
analyze table SO076 compute statistics;

prompt 正在處理 SO077...
analyze table SO077 compute statistics;

prompt 正在處理 SO078...
analyze table SO078 compute statistics;

prompt 正在處理 SO079...
analyze table SO079 compute statistics;

prompt 正在處理 SO080...
analyze table SO080 compute statistics;

prompt 正在處理 SO080A...
analyze table SO080A compute statistics;

prompt 正在處理 SO080B...
analyze table SO080B compute statistics;

prompt 正在處理 SO081...
analyze table SO081 compute statistics;

prompt 正在處理 SO082...
analyze table SO082 compute statistics;

prompt 正在處理 SO083...
analyze table SO083 compute statistics;

prompt 正在處理 SO084...
analyze table SO084 compute statistics;

prompt 正在處理 SO085...
analyze table SO085 compute statistics;

prompt 正在處理 SO086...
analyze table SO086 compute statistics;

prompt 正在處理 SO087...
analyze table SO087 compute statistics;

prompt 正在處理 SO088...
analyze table SO088 compute statistics;

prompt 正在處理 SO089...
analyze table SO089 compute statistics;

prompt 正在處理 SO089B...
analyze table SO089B compute statistics;

prompt 正在處理 SO090...
analyze table SO090 compute statistics;

prompt 正在處理 SO091...
analyze table SO091 compute statistics;

prompt 正在處理 SO092...
analyze table SO092 compute statistics;

prompt 正在處理 SO093...
analyze table SO093 compute statistics;

prompt 正在處理 SO094...
analyze table SO094 compute statistics;

prompt 正在處理 SO095...
analyze table SO095 compute statistics;

prompt 正在處理 SO096...
analyze table SO096 compute statistics;

prompt 正在處理 SO097...
analyze table SO097 compute statistics;

prompt 正在處理 SO098...
analyze table SO098 compute statistics;

prompt 正在處理 SO099...
analyze table SO099 compute statistics;

prompt 正在處理 SO100...
analyze table SO100 compute statistics;

prompt 正在處理 SO101...
analyze table SO101 compute statistics;

prompt 正在處理 SO102...
analyze table SO102 compute statistics;

prompt 正在處理 SO103...
analyze table SO103 compute statistics;

prompt 正在處理 SO104...
analyze table SO104 compute statistics;

prompt 正在處理 SO105...
analyze table SO105 compute statistics;

prompt 正在處理 SO105A...
analyze table SO105A compute statistics;

prompt 正在處理 SO105B...
analyze table SO105B compute statistics;

prompt 正在處理 SO105C...
analyze table SO105C compute statistics;

prompt 正在處理 SO105D...
analyze table SO105D compute statistics;

prompt 正在處理 SO105T...
analyze table SO105T compute statistics;

prompt 正在處理 SO106...
analyze table SO106 compute statistics;

prompt 正在處理 SO107...
analyze table SO107 compute statistics;

prompt 正在處理 SO108...
analyze table SO108 compute statistics;

prompt 正在處理 SO109...
analyze table SO109 compute statistics;

prompt 正在處理 SO110...
analyze table SO110 compute statistics;

prompt 正在處理 SO111...
analyze table SO111 compute statistics;

prompt 正在處理 SO112...
analyze table SO112 compute statistics;

prompt 正在處理 SO112A...
analyze table SO112A compute statistics;

prompt 正在處理 SO113...
analyze table SO113 compute statistics;

prompt 正在處理 SO114...
analyze table SO114 compute statistics;

prompt 正在處理 SO115...
analyze table SO115 compute statistics;

prompt 正在處理 SO116...
analyze table SO116 compute statistics;

prompt 正在處理 SO117...
analyze table SO117 compute statistics;

prompt 正在處理 SO118...
analyze table SO118 compute statistics;

prompt 正在處理 SO119...
analyze table SO119 compute statistics;

prompt 正在處理 SO120...
analyze table SO120 compute statistics;
prompt 正在處理 SO125...
analyze table SO125 compute statistics;

prompt 正在處理 SO126...
analyze table SO126 compute statistics;

prompt 正在處理 SO127...
analyze table SO127 compute statistics;

prompt 正在處理 SO128...
analyze table SO128 compute statistics;

prompt 正在處理 SO129...
analyze table SO129 compute statistics;

prompt 正在處理 SO131...
analyze table SO131 compute statistics;

prompt 正在處理 SO132...
analyze table SO132 compute statistics;


prompt 正在處理 SO133...
analyze table SO133 compute statistics;

prompt 正在處理 SO134...
analyze table SO134 compute statistics;

prompt 正在處理 SO135...
analyze table SO135 compute statistics;


prompt 正在處理 SO200...
analyze table SO200 compute statistics;

prompt 正在處理 SO201...
analyze table SO201 compute statistics;

prompt 正在處理 SO301A...
analyze table SO301A compute statistics;

prompt 正在處理 SO301B...
analyze table SO301B compute statistics;

prompt 正在處理 SO302A...
analyze table SO302A compute statistics;

prompt 正在處理 SO302B...
analyze table SO302B compute statistics;

prompt 正在處理 SO303...
analyze table SO303 compute statistics;

prompt 正在處理 SO304...
analyze table SO304 compute statistics;

prompt 正在處理 SO501...
analyze table SO501 compute statistics;

prompt 正在處理 SO501A...
analyze table SO501A compute statistics;

prompt 正在處理 SO501X...
analyze table SO501X compute statistics;

prompt 正在處理 SO502...
analyze table SO502 compute statistics;

prompt 正在處理 SO502X...
analyze table SO502X compute statistics;

prompt 正在處理 SO503...
analyze table SO503 compute statistics;

prompt 正在處理 SO504...
analyze table SO504 compute statistics;

prompt 正在處理 SO505...
analyze table SO505 compute statistics;

prompt 正在處理 SO506...
analyze table SO506 compute statistics;

prompt 正在處理 SO506A...
analyze table SO506A compute statistics;

prompt 正在處理 SO507...
analyze table SO507 compute statistics;

prompt 正在處理 SO508...
analyze table SO508 compute statistics;

prompt 正在處理 SO508A...
analyze table SO508A compute statistics;

prompt 正在處理 SO509...
analyze table SO509 compute statistics;

prompt 正在處理 SO509A...
analyze table SO509A compute statistics;

prompt 正在處理 SO509B...
analyze table SO509B compute statistics;

prompt 正在處理 SO509C...
analyze table SO509C compute statistics;

prompt 正在處理 SO510...
analyze table SO510 compute statistics;

prompt 正在處理 SO510A...
analyze table SO510A compute statistics;

prompt 正在處理 SO511A...
analyze table SO511A compute statistics;

prompt 正在處理 SO511B...
analyze table SO511B compute statistics;

prompt 正在處理 SO511C...
analyze table SO511C compute statistics;

prompt 正在處理 SO511Z...
analyze table SO511Z compute statistics;

prompt 正在處理 SO5D01...
analyze table SO5D01 compute statistics;

prompt 正在處理 SOAC0101...
analyze table SOAC0101 compute statistics;

prompt 正在處理 SOAC0102...
analyze table SOAC0102 compute statistics;

prompt 正在處理 SOAC0103...
analyze table SOAC0103 compute statistics;

prompt 正在處理 SOAC0201A...
analyze table SOAC0201A compute statistics;

prompt 正在處理 SOAC0201B...
analyze table SOAC0201B compute statistics;

prompt 正在處理 SOAC0201C...
analyze table SOAC0201C compute statistics;

prompt 正在處理 SOAC0201D...
analyze table SOAC0201D compute statistics;

prompt 正在處理 SOAC0201E...
analyze table SOAC0201E compute statistics;

prompt 正在處理 SOAC0202...
analyze table SOAC0202 compute statistics;

prompt 正在處理 SOAC0203A...
analyze table SOAC0203A compute statistics;

prompt 正在處理 SOAC0203B...
analyze table SOAC0203B compute statistics;

prompt 正在處理 SOAC0204...
analyze table SOAC0204 compute statistics;

prompt 正在處理 SOAC0301A...
analyze table SOAC0301A compute statistics;

prompt 正在處理 SOAC0301B...
analyze table SOAC0301B compute statistics;

prompt 正在處理 SOAC0301C...
analyze table SOAC0301C compute statistics;

prompt 正在處理 SOAC0301D...
analyze table SOAC0301D compute statistics;

prompt 正在處理 SOAC0302...
analyze table SOAC0302 compute statistics;

prompt 正在處理 SOAC0401...
analyze table SOAC0401 compute statistics;

prompt 正在處理 SOAC0402...
analyze table SOAC0402 compute statistics;

prompt 正在處理 SOAC0403...
analyze table SOAC0403 compute statistics;

prompt 正在處理 SOPOWER...
analyze table SOPOWER compute statistics;




exec :t2 := to_char(sysdate, 'YYYY/MM/DD HH24:MI:SS');
exec :str := '<< Analyze執行完畢, 請檢查log檔, 看是否有錯誤 >> ' || :t2;
print str
exec :tt := TRUNC(86400*(to_date(:t2, 'YYYY/MM/DD HH24:MI:SS')-to_date(:t1, 'YYYY/MM/DD HH24:MI:SS')));
exec :hh := trunc(:tt/3600);
exec :ss := mod(:tt, 60);
exec :mm := (:tt - :hh*3600 - :ss) / 60;
exec :str := '合計執行時間: ' || :hh || '時' || :mm || '分' || :ss || '秒';
print str
spool off
set heading on
