/*
Analyze V2.x Table and Index
Log file: C:\profiles\cablesoft\Tools\AnalyzeIndex.log
指令1: analyze table
             analyze table ??? estimate statistics;
指令2: analyze index
             analyze index ??? estimate statistics;
指令3: check analyze status
             select table_name, last_analyzed  from user_tables order by Table_name;
*/




variable nn number
variable msg varchar2(200)
variable t1 varchar2(19)
variable t2 varchar2(19)
variable str varchar2(80)
variable tt number
variable hh number
variable mm number
variable ss number
set serveroutput on
set heading off
exec :t1 := to_char(sysdate, 'YYYY/MM/DD HH24:MI:SS')
exec :str := '<< 開始 Analyze >> ' || :t1
spool C:\profiles\cablesoft\Tools\AnalyzeIndex.log
print str




prompt 正在處理 I_CD019A_INDEX1...
analyze index I_CD019A_INDEX1 compute statistics;

prompt 正在處理 I_CD019CD004_CITEMCP...
analyze index I_CD019CD004_CITEMCP compute statistics;

prompt 正在處理 I_CD019CD004_CLASSCP...
analyze index I_CD019CD004_CLASSCP compute statistics;

prompt 正在處理 I_CD019SO017_CITEMMP...
analyze index I_CD019SO017_CITEMMP compute statistics;

prompt 正在處理 I_CD019SO017_MDUCP...
analyze index I_CD019SO017_MDUCP compute statistics;

prompt 正在處理 I_CD067B_1...
analyze index I_CD067B_1 compute statistics;

prompt 正在處理 I_CD067C_1...
analyze index I_CD067C_1 compute statistics;

prompt 正在處理 I_CM003_EMPNAME...
analyze index I_CM003_EMPNAME compute statistics;

prompt 正在處理 I_CODEUSAGE1...
analyze index I_CODEUSAGE1 compute statistics;

prompt 正在處理 I_CODEUSAGE2...
analyze index I_CODEUSAGE2 compute statistics;

prompt 正在處理 I_DSSRPT_00000011...
analyze index I_DSSRPT_00000011 compute statistics;

prompt 正在處理 I_DSSRPT_00000016...
analyze index I_DSSRPT_00000016 compute statistics;

prompt 正在處理 I_SENDMSS2_1...
analyze index I_SENDMSS2_1 compute statistics;

prompt 正在處理 I_SENDMSS3_1...
analyze index I_SENDMSS3_1 compute statistics;

prompt 正在處理 I_SENDMSS6_1...
analyze index I_SENDMSS6_1 compute statistics;

prompt 正在處理 I_SEND_NAGRA_1...
analyze index I_SEND_NAGRA_1 compute statistics;

prompt 正在處理 I_SEND_NAGRA_2...
analyze index I_SEND_NAGRA_2 compute statistics;

prompt 正在處理 I_SEND_NAGRA_3...
analyze index I_SEND_NAGRA_3 compute statistics;

prompt 正在處理 I_SEND_NDS_1...
analyze index I_SEND_NDS_1 compute statistics;

prompt 正在處理 I_SO001_1...
analyze index I_SO001_1 compute statistics;

prompt 正在處理 I_SO001_11...
analyze index I_SO001_11 compute statistics;

prompt 正在處理 I_SO001_2...
analyze index I_SO001_2 compute statistics;

prompt 正在處理 I_SO001_CHARGEADDRNO...
analyze index I_SO001_CHARGEADDRNO compute statistics;

prompt 正在處理 I_SO001_CLCTAREACODE...
analyze index I_SO001_CLCTAREACODE compute statistics;

prompt 正在處理 I_SO001_CUSTNAME...
analyze index I_SO001_CUSTNAME compute statistics;

prompt 正在處理 I_SO001_ID...
analyze index I_SO001_ID compute statistics;

prompt 正在處理 I_SO001_INDEX2_R25...
analyze index I_SO001_INDEX2_R25 compute statistics;

prompt 正在處理 I_SO001_INSTADDRNO...
analyze index I_SO001_INSTADDRNO compute statistics;

prompt 正在處理 I_SO001_MAILADDRNO...
analyze index I_SO001_MAILADDRNO compute statistics;

prompt 正在處理 I_SO001_MDUID...
analyze index I_SO001_MDUID compute statistics;

prompt 正在處理 I_SO001_ORGCODE...
analyze index I_SO001_ORGCODE compute statistics;

prompt 正在處理 I_SO001_PINCODE...
analyze index I_SO001_PINCODE compute statistics;

prompt 正在處理 I_SO001_PWCODE...
analyze index I_SO001_PWCODE compute statistics;

prompt 正在處理 I_SO001_SERVCODE...
analyze index I_SO001_SERVCODE compute statistics;

prompt 正在處理 I_SO001_TEL1...
analyze index I_SO001_TEL1 compute statistics;

prompt 正在處理 I_SO001_TEL2...
analyze index I_SO001_TEL2 compute statistics;

prompt 正在處理 I_SO001_TEL3...
analyze index I_SO001_TEL3 compute statistics;

prompt 正在處理 I_SO002A_ACCOUNTNO...
analyze index I_SO002A_ACCOUNTNO compute statistics;

prompt 正在處理 I_SO002A_CHARGETITLE...
analyze index I_SO002A_CHARGETITLE compute statistics;

prompt 正在處理 I_SO002_1...
analyze index I_SO002_1 compute statistics;

prompt 正在處理 I_SO002_2...
analyze index I_SO002_2 compute statistics;

prompt 正在處理 I_SO002_3...
analyze index I_SO002_3 compute statistics;

prompt 正在處理 I_SO002_4...
analyze index I_SO002_4 compute statistics;

prompt 正在處理 I_SO002_ACCOUNTNO...
analyze index I_SO002_ACCOUNTNO compute statistics;

prompt 正在處理 I_SO002_BANKCODE...
analyze index I_SO002_BANKCODE compute statistics;

prompt 正在處理 I_SO002_CMCODE...
analyze index I_SO002_CMCODE compute statistics;

prompt 正在處理 I_SO002_CONTNAME...
analyze index I_SO002_CONTNAME compute statistics;

prompt 正在處理 I_SO002_CONTTEL...
analyze index I_SO002_CONTTEL compute statistics;

prompt 正在處理 I_SO002_CREDITCARDNO...
analyze index I_SO002_CREDITCARDNO compute statistics;

prompt 正在處理 I_SO002_CUSTSTATUSCODE...
analyze index I_SO002_CUSTSTATUSCODE compute statistics;

prompt 正在處理 I_SO002_DELCODE...
analyze index I_SO002_DELCODE compute statistics;

prompt 正在處理 I_SO002_EMAIL...
analyze index I_SO002_EMAIL compute statistics;

prompt 正在處理 I_SO002_EMAIL1...
analyze index I_SO002_EMAIL1 compute statistics;

prompt 正在處理 I_SO002_EMAIL2...
analyze index I_SO002_EMAIL2 compute statistics;

prompt 正在處理 I_SO002_EMAIL3...
analyze index I_SO002_EMAIL3 compute statistics;

prompt 正在處理 I_SO002_EMAIL4...
analyze index I_SO002_EMAIL4 compute statistics;

prompt 正在處理 I_SO002_ID...
analyze index I_SO002_ID compute statistics;

prompt 正在處理 I_SO002_INDEX1...
analyze index I_SO002_INDEX1 compute statistics;

prompt 正在處理 I_SO002_INSTTIME...
analyze index I_SO002_INSTTIME compute statistics;

prompt 正在處理 I_SO002_MEDIACODE...
analyze index I_SO002_MEDIACODE compute statistics;

prompt 正在處理 I_SO002_PINCODE...
analyze index I_SO002_PINCODE compute statistics;

prompt 正在處理 I_SO002_PRTIME...
analyze index I_SO002_PRTIME compute statistics;

prompt 正在處理 I_SO002_WIPCODE1...
analyze index I_SO002_WIPCODE1 compute statistics;

prompt 正在處理 I_SO002_WIPCODE2...
analyze index I_SO002_WIPCODE2 compute statistics;

prompt 正在處理 I_SO002_WIPCODE3...
analyze index I_SO002_WIPCODE3 compute statistics;

prompt 正在處理 I_SO003_CITEMCODE...
analyze index I_SO003_CITEMCODE compute statistics;

prompt 正在處理 I_SO003_CLCTDATE...
analyze index I_SO003_CLCTDATE compute statistics;

prompt 正在處理 I_SO003_CSCC...
analyze index I_SO003_CSCC compute statistics;

prompt 正在處理 I_SO003_CUSTID...
analyze index I_SO003_CUSTID compute statistics;

prompt 正在處理 I_SO004_BUYCODE...
analyze index I_SO004_BUYCODE compute statistics;

prompt 正在處理 I_SO004_CHECKNO...
analyze index I_SO004_CHECKNO compute statistics;

prompt 正在處理 I_SO004_CSS...
analyze index I_SO004_CSS compute statistics;

prompt 正在處理 I_SO004_CUSTID_FACICODE...
analyze index I_SO004_CUSTID_FACICODE compute statistics;

prompt 正在處理 I_SO004_CVTID...
analyze index I_SO004_CVTID compute statistics;

prompt 正在處理 I_SO004_FACICODE...
analyze index I_SO004_FACICODE compute statistics;

prompt 正在處理 I_SO004_FACISNO...
analyze index I_SO004_FACISNO compute statistics;

prompt 正在處理 I_SO004_INSTDATE...
analyze index I_SO004_INSTDATE compute statistics;

prompt 正在處理 I_SO004_MEDIACODE...
analyze index I_SO004_MEDIACODE compute statistics;

prompt 正在處理 I_SO004_ORDERNO...
analyze index I_SO004_ORDERNO compute statistics;

prompt 正在處理 I_SO004_PRDATE...
analyze index I_SO004_PRDATE compute statistics;

prompt 正在處理 I_SO004_PRSNO...
analyze index I_SO004_PRSNO compute statistics;

prompt 正在處理 I_SO004_SSBFP...
analyze index I_SO004_SSBFP compute statistics;

prompt 正在處理 I_SO005_CSC...
analyze index I_SO005_CSC compute statistics;

prompt 正在處理 I_SO005_CUSTID...
analyze index I_SO005_CUSTID compute statistics;

prompt 正在處理 I_SO005_CUSTIDCVTIDCHCODE...
analyze index I_SO005_CUSTIDCVTIDCHCODE compute statistics;

prompt 正在處理 I_SO006_11...
analyze index I_SO006_11 compute statistics;

prompt 正在處理 I_SO006_CIDACPTTIME...
analyze index I_SO006_CIDACPTTIME compute statistics;

prompt 正在處理 I_SO006_CSC...
analyze index I_SO006_CSC compute statistics;

prompt 正在處理 I_SO006_MEDIACODE...
analyze index I_SO006_MEDIACODE compute statistics;

prompt 正在處理 I_SO006_NODENO...
analyze index I_SO006_NODENO compute statistics;

prompt 正在處理 I_SO006_ORDERNO...
analyze index I_SO006_ORDERNO compute statistics;

prompt 正在處理 I_SO006_PROMCODE...
analyze index I_SO006_PROMCODE compute statistics;

prompt 正在處理 I_SO006_SERVICECODE...
analyze index I_SO006_SERVICECODE compute statistics;

prompt 正在處理 I_SO006_SNO...
analyze index I_SO006_SNO compute statistics;

prompt 正在處理 I_SO007_1...
analyze index I_SO007_1 compute statistics;

prompt 正在處理 I_SO007_11...
analyze index I_SO007_11 compute statistics;

prompt 正在處理 I_SO007_12...
analyze index I_SO007_12 compute statistics;

prompt 正在處理 I_SO007_ACCEPTTIME...
analyze index I_SO007_ACCEPTTIME compute statistics;

prompt 正在處理 I_SO007_ADDRNO...
analyze index I_SO007_ADDRNO compute statistics;

prompt 正在處理 I_SO007_CALLOKTIME...
analyze index I_SO007_CALLOKTIME compute statistics;

prompt 正在處理 I_SO007_CIDSNO...
analyze index I_SO007_CIDSNO compute statistics;

prompt 正在處理 I_SO007_FINTIME...
analyze index I_SO007_FINTIME compute statistics;

prompt 正在處理 I_SO007_GROUPCODE...
analyze index I_SO007_GROUPCODE compute statistics;

prompt 正在處理 I_SO007_INSTCODE...
analyze index I_SO007_INSTCODE compute statistics;

prompt 正在處理 I_SO007_MEDIACODE...
analyze index I_SO007_MEDIACODE compute statistics;

prompt 正在處理 I_SO007_NODENO...
analyze index I_SO007_NODENO compute statistics;

prompt 正在處理 I_SO007_ORDERNO...
analyze index I_SO007_ORDERNO compute statistics;

prompt 正在處理 I_SO007_PROMCODE...
analyze index I_SO007_PROMCODE compute statistics;

prompt 正在處理 I_SO007_R61_1...
analyze index I_SO007_R61_1 compute statistics;

prompt 正在處理 I_SO007_RESVTIME...
analyze index I_SO007_RESVTIME compute statistics;

prompt 正在處理 I_SO007_RETURNCODE...
analyze index I_SO007_RETURNCODE compute statistics;

prompt 正在處理 I_SO007_SATICODE...
analyze index I_SO007_SATICODE compute statistics;

prompt 正在處理 I_SO007_SIGNDATE...
analyze index I_SO007_SIGNDATE compute statistics;

prompt 正在處理 I_SO007_SNO2...
analyze index I_SO007_SNO2 compute statistics;

prompt 正在處理 I_SO007_TEL1...
analyze index I_SO007_TEL1 compute statistics;

prompt 正在處理 I_SO008_ACCEPTTIME...
analyze index I_SO008_ACCEPTTIME compute statistics;

prompt 正在處理 I_SO008_ADDRNO...
analyze index I_SO008_ADDRNO compute statistics;

prompt 正在處理 I_SO008_CALLOKTIME...
analyze index I_SO008_CALLOKTIME compute statistics;

prompt 正在處理 I_SO008_CIDSNO...
analyze index I_SO008_CIDSNO compute statistics;

prompt 正在處理 I_SO008_FINTIME...
analyze index I_SO008_FINTIME compute statistics;

prompt 正在處理 I_SO008_GROUPCODE...
analyze index I_SO008_GROUPCODE compute statistics;

prompt 正在處理 I_SO008_MFCODE1...
analyze index I_SO008_MFCODE1 compute statistics;

prompt 正在處理 I_SO008_MFCODE2...
analyze index I_SO008_MFCODE2 compute statistics;

prompt 正在處理 I_SO008_NODENO...
analyze index I_SO008_NODENO compute statistics;

prompt 正在處理 I_SO008_RESVTIME...
analyze index I_SO008_RESVTIME compute statistics;

prompt 正在處理 I_SO008_RETURNCODE...
analyze index I_SO008_RETURNCODE compute statistics;

prompt 正在處理 I_SO008_SATICODE...
analyze index I_SO008_SATICODE compute statistics;

prompt 正在處理 I_SO008_SERVICECODE...
analyze index I_SO008_SERVICECODE compute statistics;

prompt 正在處理 I_SO008_SIGNDATE...
analyze index I_SO008_SIGNDATE compute statistics;

prompt 正在處理 I_SO008_SNO2...
analyze index I_SO008_SNO2 compute statistics;

prompt 正在處理 I_SO008_TEL1...
analyze index I_SO008_TEL1 compute statistics;

prompt 正在處理 I_SO009_ACCEPTTIME...
analyze index I_SO009_ACCEPTTIME compute statistics;

prompt 正在處理 I_SO009_CALLOKTIME...
analyze index I_SO009_CALLOKTIME compute statistics;

prompt 正在處理 I_SO009_CIDSNO...
analyze index I_SO009_CIDSNO compute statistics;

prompt 正在處理 I_SO009_FINTIME...
analyze index I_SO009_FINTIME compute statistics;

prompt 正在處理 I_SO009_GROUPCODE...
analyze index I_SO009_GROUPCODE compute statistics;

prompt 正在處理 I_SO009_NODENO...
analyze index I_SO009_NODENO compute statistics;

prompt 正在處理 I_SO009_OLDADDRNO...
analyze index I_SO009_OLDADDRNO compute statistics;

prompt 正在處理 I_SO009_PRCODE...
analyze index I_SO009_PRCODE compute statistics;

prompt 正在處理 I_SO009_REASONCODE...
analyze index I_SO009_REASONCODE compute statistics;

prompt 正在處理 I_SO009_REINSTADDRNO...
analyze index I_SO009_REINSTADDRNO compute statistics;

prompt 正在處理 I_SO009_RESVTIME...
analyze index I_SO009_RESVTIME compute statistics;

prompt 正在處理 I_SO009_RETURNCODE...
analyze index I_SO009_RETURNCODE compute statistics;

prompt 正在處理 I_SO009_SATICODE...
analyze index I_SO009_SATICODE compute statistics;

prompt 正在處理 I_SO009_SIGNDATE...
analyze index I_SO009_SIGNDATE compute statistics;

prompt 正在處理 I_SO009_SNO2...
analyze index I_SO009_SNO2 compute statistics;

prompt 正在處理 I_SO009_TEL1...
analyze index I_SO009_TEL1 compute statistics;

prompt 正在處理 I_SO012_COMPCODEINTROID...
analyze index I_SO012_COMPCODEINTROID compute statistics;

prompt 正在處理 I_SO013_PROFCODE...
analyze index I_SO013_PROFCODE compute statistics;

prompt 正在處理 I_SO014_ADDRESS...
analyze index I_SO014_ADDRESS compute statistics;

prompt 正在處理 I_SO014_ADDRNO...
analyze index I_SO014_ADDRNO compute statistics;

prompt 正在處理 I_SO014_ADDRSORT...
analyze index I_SO014_ADDRSORT compute statistics;

prompt 正在處理 I_SO014_ADDRSORT2...
analyze index I_SO014_ADDRSORT2 compute statistics;

prompt 正在處理 I_SO014_BOURGCODE...
analyze index I_SO014_BOURGCODE compute statistics;

prompt 正在處理 I_SO014_BTCODE...
analyze index I_SO014_BTCODE compute statistics;

prompt 正在處理 I_SO014_CIRCUITNO...
analyze index I_SO014_CIRCUITNO compute statistics;

prompt 正在處理 I_SO014_CLCTAREACODE...
analyze index I_SO014_CLCTAREACODE compute statistics;

prompt 正在處理 I_SO014_CLCTEN...
analyze index I_SO014_CLCTEN compute statistics;

prompt 正在處理 I_SO014_COMPARESTR...
analyze index I_SO014_COMPARESTR compute statistics;

prompt 正在處理 I_SO014_MDUID...
analyze index I_SO014_MDUID compute statistics;

prompt 正在處理 I_SO014_NODENO...
analyze index I_SO014_NODENO compute statistics;

prompt 正在處理 I_SO014_STRTCODE...
analyze index I_SO014_STRTCODE compute statistics;

prompt 正在處理 I_SO015_ADDRNO...
analyze index I_SO015_ADDRNO compute statistics;

prompt 正在處理 I_SO015_CUSTID...
analyze index I_SO015_CUSTID compute statistics;

prompt 正在處理 I_SO016_AREACODE...
analyze index I_SO016_AREACODE compute statistics;

prompt 正在處理 I_SO016_BTCODE...
analyze index I_SO016_BTCODE compute statistics;

prompt 正在處理 I_SO016_SERVCODE...
analyze index I_SO016_SERVCODE compute statistics;

prompt 正在處理 I_SO019_AREACODE...
analyze index I_SO019_AREACODE compute statistics;

prompt 正在處理 I_SO019_CLASSCODE...
analyze index I_SO019_CLASSCODE compute statistics;

prompt 正在處理 I_SO019_FACICODE1...
analyze index I_SO019_FACICODE1 compute statistics;

prompt 正在處理 I_SO019_FACICODE2...
analyze index I_SO019_FACICODE2 compute statistics;

prompt 正在處理 I_SO019_SERVCODE...
analyze index I_SO019_SERVCODE compute statistics;

prompt 正在處理 I_SO020_COUNTCODE...
analyze index I_SO020_COUNTCODE compute statistics;

prompt 正在處理 I_SO029_LINK...
analyze index I_SO029_LINK compute statistics;

prompt 正在處理 I_SO030A_BEGINEXECTIME...
analyze index I_SO030A_BEGINEXECTIME compute statistics;

prompt 正在處理 I_SO030A_COMPCODE...
analyze index I_SO030A_COMPCODE compute statistics;

prompt 正在處理 I_SO030A_JOBID...
analyze index I_SO030A_JOBID compute statistics;

prompt 正在處理 I_SO030A_SERVICETYPE...
analyze index I_SO030A_SERVICETYPE compute statistics;

prompt 正在處理 I_SO030_EXECDATE...
analyze index I_SO030_EXECDATE compute statistics;

prompt 正在處理 I_SO030_EXECTIME...
analyze index I_SO030_EXECTIME compute statistics;

prompt 正在處理 I_SO032_NODENO...
analyze index I_SO032_NODENO compute statistics;

prompt 正在處理 I_SO033DEBT_SNO...
analyze index I_SO033DEBT_SNO compute statistics;

prompt 正在處理 I_SO033_11...
analyze index I_SO033_11 compute statistics;

prompt 正在處理 I_SO033_12...
analyze index I_SO033_12 compute statistics;

prompt 正在處理 I_SO033_13...
analyze index I_SO033_13 compute statistics;

prompt 正在處理 I_SO033_A1...
analyze index I_SO033_A1 compute statistics;

prompt 正在處理 I_SO033_ADDRNOCLCTYM...
analyze index I_SO033_ADDRNOCLCTYM compute statistics;

prompt 正在處理 I_SO033_CITEMCODE...
analyze index I_SO033_CITEMCODE compute statistics;

prompt 正在處理 I_SO033_CITEMDATE...
analyze index I_SO033_CITEMDATE compute statistics;

prompt 正在處理 I_SO033_CITIBANKATM...
analyze index I_SO033_CITIBANKATM compute statistics;

prompt 正在處理 I_SO033_CLCTEN...
analyze index I_SO033_CLCTEN compute statistics;

prompt 正在處理 I_SO033_CMCODE...
analyze index I_SO033_CMCODE compute statistics;

prompt 正在處理 I_SO033_CREATEEN...
analyze index I_SO033_CREATEEN compute statistics;

prompt 正在處理 I_SO033_CREATETIME...
analyze index I_SO033_CREATETIME compute statistics;

prompt 正在處理 I_SO033_CUSTID...
analyze index I_SO033_CUSTID compute statistics;

prompt 正在處理 I_SO033_FACISEQNO...
analyze index I_SO033_FACISEQNO compute statistics;

prompt 正在處理 I_SO033_INDEX1...
analyze index I_SO033_INDEX1 compute statistics;

prompt 正在處理 I_SO033_INDEX2...
analyze index I_SO033_INDEX2 compute statistics;

prompt 正在處理 I_SO033_INDEX3...
analyze index I_SO033_INDEX3 compute statistics;

prompt 正在處理 I_SO033_INDEX4...
analyze index I_SO033_INDEX4 compute statistics;

prompt 正在處理 I_SO033_MEDIABILLNO...
analyze index I_SO033_MEDIABILLNO compute statistics;

prompt 正在處理 I_SO033_NODENO...
analyze index I_SO033_NODENO compute statistics;

prompt 正在處理 I_SO033_OLDBC...
analyze index I_SO033_OLDBC compute statistics;

prompt 正在處理 I_SO033_PRTSNO...
analyze index I_SO033_PRTSNO compute statistics;

prompt 正在處理 I_SO033_PTCODE...
analyze index I_SO033_PTCODE compute statistics;

prompt 正在處理 I_SO033_REALDATE...
analyze index I_SO033_REALDATE compute statistics;

prompt 正在處理 I_SO033_SHOULDDATE...
analyze index I_SO033_SHOULDDATE compute statistics;

prompt 正在處理 I_SO033_SNO...
analyze index I_SO033_SNO compute statistics;

prompt 正在處理 I_SO033_STCODE...
analyze index I_SO033_STCODE compute statistics;

prompt 正在處理 I_SO033_UCCODE...
analyze index I_SO033_UCCODE compute statistics;

prompt 正在處理 I_SO034_11...
analyze index I_SO034_11 compute statistics;

prompt 正在處理 I_SO034_12...
analyze index I_SO034_12 compute statistics;

prompt 正在處理 I_SO034_13...
analyze index I_SO034_13 compute statistics;

prompt 正在處理 I_SO034_A1...
analyze index I_SO034_A1 compute statistics;

prompt 正在處理 I_SO034_ADDRNOCLCTYM...
analyze index I_SO034_ADDRNOCLCTYM compute statistics;

prompt 正在處理 I_SO034_CITEMCODE...
analyze index I_SO034_CITEMCODE compute statistics;

prompt 正在處理 I_SO034_CITEMDATE...
analyze index I_SO034_CITEMDATE compute statistics;

prompt 正在處理 I_SO034_CLCTEN...
analyze index I_SO034_CLCTEN compute statistics;

prompt 正在處理 I_SO034_CMCODE...
analyze index I_SO034_CMCODE compute statistics;

prompt 正在處理 I_SO034_CREATETIME...
analyze index I_SO034_CREATETIME compute statistics;

prompt 正在處理 I_SO034_CUSTID...
analyze index I_SO034_CUSTID compute statistics;

prompt 正在處理 I_SO034_FACISEQNO...
analyze index I_SO034_FACISEQNO compute statistics;

prompt 正在處理 I_SO034_INDEX1...
analyze index I_SO034_INDEX1 compute statistics;

prompt 正在處理 I_SO034_INDEX2...
analyze index I_SO034_INDEX2 compute statistics;

prompt 正在處理 I_SO034_INDEX3...
analyze index I_SO034_INDEX3 compute statistics;

prompt 正在處理 I_SO034_INDEX4...
analyze index I_SO034_INDEX4 compute statistics;

prompt 正在處理 I_SO034_MEDIABILLNO...
analyze index I_SO034_MEDIABILLNO compute statistics;

prompt 正在處理 I_SO034_NODENO...
analyze index I_SO034_NODENO compute statistics;

prompt 正在處理 I_SO034_PRTSNO...
analyze index I_SO034_PRTSNO compute statistics;

prompt 正在處理 I_SO034_PTCODE...
analyze index I_SO034_PTCODE compute statistics;

prompt 正在處理 I_SO034_REALDATE...
analyze index I_SO034_REALDATE compute statistics;

prompt 正在處理 I_SO034_SNO...
analyze index I_SO034_SNO compute statistics;

prompt 正在處理 I_SO034_STCODE...
analyze index I_SO034_STCODE compute statistics;

prompt 正在處理 I_SO034_UCCODE...
analyze index I_SO034_UCCODE compute statistics;

prompt 正在處理 I_SO035_11...
analyze index I_SO035_11 compute statistics;

prompt 正在處理 I_SO035_ADDRNOCLCTYM...
analyze index I_SO035_ADDRNOCLCTYM compute statistics;

prompt 正在處理 I_SO035_CITEMCODE...
analyze index I_SO035_CITEMCODE compute statistics;

prompt 正在處理 I_SO035_CITEMDATE...
analyze index I_SO035_CITEMDATE compute statistics;

prompt 正在處理 I_SO035_CLCTEN...
analyze index I_SO035_CLCTEN compute statistics;

prompt 正在處理 I_SO035_CREATETIME...
analyze index I_SO035_CREATETIME compute statistics;

prompt 正在處理 I_SO035_CUSTID...
analyze index I_SO035_CUSTID compute statistics;

prompt 正在處理 I_SO035_FACISEQNO...
analyze index I_SO035_FACISEQNO compute statistics;

prompt 正在處理 I_SO035_MEDIABILLNO...
analyze index I_SO035_MEDIABILLNO compute statistics;

prompt 正在處理 I_SO035_NODENO...
analyze index I_SO035_NODENO compute statistics;

prompt 正在處理 I_SO035_SNO...
analyze index I_SO035_SNO compute statistics;

prompt 正在處理 I_SO035_STCODE...
analyze index I_SO035_STCODE compute statistics;

prompt 正在處理 I_SO036_ADDRNOCLCTYM...
analyze index I_SO036_ADDRNOCLCTYM compute statistics;

prompt 正在處理 I_SO036_CITEMCODE...
analyze index I_SO036_CITEMCODE compute statistics;

prompt 正在處理 I_SO036_CITEMDATE...
analyze index I_SO036_CITEMDATE compute statistics;

prompt 正在處理 I_SO036_CLCTEN...
analyze index I_SO036_CLCTEN compute statistics;

prompt 正在處理 I_SO036_CMCODE...
analyze index I_SO036_CMCODE compute statistics;

prompt 正在處理 I_SO036_MEDIABILLNO...
analyze index I_SO036_MEDIABILLNO compute statistics;

prompt 正在處理 I_SO036_NODENO...
analyze index I_SO036_NODENO compute statistics;

prompt 正在處理 I_SO036_PTCODE...
analyze index I_SO036_PTCODE compute statistics;

prompt 正在處理 I_SO036_REALDATE...
analyze index I_SO036_REALDATE compute statistics;

prompt 正在處理 I_SO036_SNO...
analyze index I_SO036_SNO compute statistics;

prompt 正在處理 I_SO036_STCODE...
analyze index I_SO036_STCODE compute statistics;

prompt 正在處理 I_SO036_UCCODE...
analyze index I_SO036_UCCODE compute statistics;

prompt 正在處理 I_SO040_MAINCUSTID...
analyze index I_SO040_MAINCUSTID compute statistics;

prompt 正在處理 I_SO040_MBRCUSTID...
analyze index I_SO040_MBRCUSTID compute statistics;

prompt 正在處理 I_SO050_BILLNOITEM...
analyze index I_SO050_BILLNOITEM compute statistics;

prompt 正在處理 I_SO051_EN_TIME...
analyze index I_SO051_EN_TIME compute statistics;

prompt 正在處理 I_SO051_UPDTIME...
analyze index I_SO051_UPDTIME compute statistics;

prompt 正在處理 I_SO054_PRGNAME...
analyze index I_SO054_PRGNAME compute statistics;

prompt 正在處理 I_SO055_EN_TIME...
analyze index I_SO055_EN_TIME compute statistics;

prompt 正在處理 I_SO055_UPDTIME...
analyze index I_SO055_UPDTIME compute statistics;

prompt 正在處理 I_SO061_EN_TIME...
analyze index I_SO061_EN_TIME compute statistics;

prompt 正在處理 I_SO061_UPDTIME...
analyze index I_SO061_UPDTIME compute statistics;

prompt 正在處理 I_SO064_BATCHTYPESNO...
analyze index I_SO064_BATCHTYPESNO compute statistics;

prompt 正在處理 I_SO074_ENNO...
analyze index I_SO074_ENNO compute statistics;

prompt 正在處理 I_SO089B_CITEMCODE...
analyze index I_SO089B_CITEMCODE compute statistics;

prompt 正在處理 I_SO089_CITEMCODE...
analyze index I_SO089_CITEMCODE compute statistics;

prompt 正在處理 I_SO089_RA1_1...
analyze index I_SO089_RA1_1 compute statistics;

prompt 正在處理 I_SO095_BULLETINCODE...
analyze index I_SO095_BULLETINCODE compute statistics;

prompt 正在處理 I_SO095_PROMCODE...
analyze index I_SO095_PROMCODE compute statistics;

prompt 正在處理 I_SO096_ACCEPTENTIMEBULLETIN...
analyze index I_SO096_ACCEPTENTIMEBULLETIN compute statistics;

prompt 正在處理 I_SO096_ACCEPTTIME...
analyze index I_SO096_ACCEPTTIME compute statistics;

prompt 正在處理 I_SO096_BULLETINCODE...
analyze index I_SO096_BULLETINCODE compute statistics;

prompt 正在處理 I_SO096_PROMCODE...
analyze index I_SO096_PROMCODE compute statistics;

prompt 正在處理 I_SO098_CUSTCOMPSERVICE...
analyze index I_SO098_CUSTCOMPSERVICE compute statistics;

prompt 正在處理 I_SO104_PRTIME_INSTTIME_STATUS...
analyze index I_SO104_PRTIME_INSTTIME_STATUS compute statistics;

prompt 正在處理 I_SO104_STATUS_CUSTID_INSTTIME...
analyze index I_SO104_STATUS_CUSTID_INSTTIME compute statistics;

prompt 正在處理 I_SO105B_OPCS...
analyze index I_SO105B_OPCS compute statistics;

prompt 正在處理 I_SO105C_CFCB...
analyze index I_SO105C_CFCB compute statistics;

prompt 正在處理 I_SO105C_OPAFS...
analyze index I_SO105C_OPAFS compute statistics;

prompt 正在處理 I_SO105D_OPFS...
analyze index I_SO105D_OPFS compute statistics;

prompt 正在處理 I_SO105T_CUSTIDCOMPCODE...
analyze index I_SO105T_CUSTIDCOMPCODE compute statistics;

prompt 正在處理 I_SO106_ACCOUNTID...
analyze index I_SO106_ACCOUNTID compute statistics;

prompt 正在處理 I_SO106_CUSTIDCOMPCODE...
analyze index I_SO106_CUSTIDCOMPCODE compute statistics;

prompt 正在處理 I_SO107_INDEX1...
analyze index I_SO107_INDEX1 compute statistics;

prompt 正在處理 I_SO109_PCS...
analyze index I_SO109_PCS compute statistics;

prompt 正在處理 I_SO112_INDEX2...
analyze index I_SO112_INDEX2 compute statistics;

prompt 正在處理 I_SO115_INDEX1...
analyze index I_SO115_INDEX1 compute statistics;

prompt 正在處理 I_SO115_INDEX2...
analyze index I_SO115_INDEX2 compute statistics;

prompt 正在處理 I_SO115_INDEX3...
analyze index I_SO115_INDEX3 compute statistics;

prompt 正在處理 I_SO115_INDEX4...
analyze index I_SO115_INDEX4 compute statistics;

prompt 正在處理 I_SO115_INDEX5...
analyze index I_SO115_INDEX5 compute statistics;

prompt 正在處理 I_SO115_INDEX6...
analyze index I_SO115_INDEX6 compute statistics;

prompt 正在處理 I_SO120_INDEX1...
analyze index I_SO120_INDEX1 compute statistics;

prompt 正在處理 I_SO120_INDEX2...
analyze index I_SO120_INDEX2 compute statistics;

prompt 正在處理 I_SO120_INDEX3...
analyze index I_SO120_INDEX3 compute statistics;

prompt 正在處理 I_SO121_INDEX1...
analyze index I_SO121_INDEX1 compute statistics;

prompt 正在處理 I_SO122_INDEX1...
analyze index I_SO122_INDEX1 compute statistics;

prompt 正在處理 I_SO126_1...
analyze index I_SO126_1 compute statistics;

prompt 正在處理 I_SO126_2...
analyze index I_SO126_2 compute statistics;

prompt 正在處理 I_SO126_3...
analyze index I_SO126_3 compute statistics;

prompt 正在處理 I_SO126_4...
analyze index I_SO126_4 compute statistics;

prompt 正在處理 I_SO126_5...
analyze index I_SO126_5 compute statistics;

prompt 正在處理 I_SO126_6...
analyze index I_SO126_6 compute statistics;

prompt 正在處理 I_SO126_7...
analyze index I_SO126_7 compute statistics;

prompt 正在處理 I_SO127_1...
analyze index I_SO127_1 compute statistics;

prompt 正在處理 I_SO128_1...
analyze index I_SO128_1 compute statistics;

prompt 正在處理 I_SO128_2...
analyze index I_SO128_2 compute statistics;

prompt 正在處理 I_SO131_INDEX1...
analyze index I_SO131_INDEX1 compute statistics;

prompt 正在處理 I_SO131_INDEX2...
analyze index I_SO131_INDEX2 compute statistics;

prompt 正在處理 I_SO200_LINK...
analyze index I_SO200_LINK compute statistics;

prompt 正在處理 I_SO301A_KEY...
analyze index I_SO301A_KEY compute statistics;

prompt 正在處理 I_SO301B_KEY...
analyze index I_SO301B_KEY compute statistics;

prompt 正在處理 I_SO302A_KEY...
analyze index I_SO302A_KEY compute statistics;

prompt 正在處理 I_SO302B_KEY...
analyze index I_SO302B_KEY compute statistics;

prompt 正在處理 I_SO303_KEY...
analyze index I_SO303_KEY compute statistics;

prompt 正在處理 I_SO304_ADDRNO...
analyze index I_SO304_ADDRNO compute statistics;

prompt 正在處理 I_SO304_ADDRNO2...
analyze index I_SO304_ADDRNO2 compute statistics;

prompt 正在處理 I_SO304_ADDRNO3...
analyze index I_SO304_ADDRNO3 compute statistics;

prompt 正在處理 I_SO501X_MAIN...
analyze index I_SO501X_MAIN compute statistics;

prompt 正在處理 I_SO501_MAIN...
analyze index I_SO501_MAIN compute statistics;

prompt 正在處理 I_SO502X_MAIN...
analyze index I_SO502X_MAIN compute statistics;

prompt 正在處理 I_SO502_MAIN...
analyze index I_SO502_MAIN compute statistics;

prompt 正在處理 I_SO504_MAIN1...
analyze index I_SO504_MAIN1 compute statistics;

prompt 正在處理 I_SO504_MAIN2...
analyze index I_SO504_MAIN2 compute statistics;

prompt 正在處理 I_SO504_SEQNO...
analyze index I_SO504_SEQNO compute statistics;

prompt 正在處理 I_SO506A_INSTADDRNO...
analyze index I_SO506A_INSTADDRNO compute statistics;

prompt 正在處理 I_SO506_STATUS...
analyze index I_SO506_STATUS compute statistics;

prompt 正在處理 I_SO509A_INDEX1...
analyze index I_SO509A_INDEX1 compute statistics;

prompt 正在處理 I_SO509B_INDEX1...
analyze index I_SO509B_INDEX1 compute statistics;

prompt 正在處理 I_SO510A_CRU...
analyze index I_SO510A_CRU compute statistics;

prompt 正在處理 I_SO510A_RCU...
analyze index I_SO510A_RCU compute statistics;

prompt 正在處理 I_SO510_CR...
analyze index I_SO510_CR compute statistics;

prompt 正在處理 I_SO510_RC...
analyze index I_SO510_RC compute statistics;

prompt 正在處理 I_SO511A_CRCPN...
analyze index I_SO511A_CRCPN compute statistics;

prompt 正在處理 I_SO511A_RPTYM...
analyze index I_SO511A_RPTYM compute statistics;

prompt 正在處理 I_SO511B_CRCPN...
analyze index I_SO511B_CRCPN compute statistics;

prompt 正在處理 I_SO511B_RPTYM...
analyze index I_SO511B_RPTYM compute statistics;

prompt 正在處理 I_SO511C_CRCPN...
analyze index I_SO511C_CRCPN compute statistics;

prompt 正在處理 I_SO511C_RPTYM...
analyze index I_SO511C_RPTYM compute statistics;

prompt 正在處理 I_SO511Z_CCP...
analyze index I_SO511Z_CCP compute statistics;

prompt 正在處理 I_SOAC0102_CHCODE...
analyze index I_SOAC0102_CHCODE compute statistics;

prompt 正在處理 I_SOAC0201C_ICCSNO...
analyze index I_SOAC0201C_ICCSNO compute statistics;

prompt 正在處理 I_SOAC0201C_STBSNO...
analyze index I_SOAC0201C_STBSNO compute statistics;

prompt 正在處理 I_SOAC0202_ICCSNO...
analyze index I_SOAC0202_ICCSNO compute statistics;

prompt 正在處理 I_SOAC0202_STBSNO...
analyze index I_SOAC0202_STBSNO compute statistics;

prompt 正在處理 I_SOAC0204_CALLTIME...
analyze index I_SOAC0204_CALLTIME compute statistics;

prompt 正在處理 I_SOAC0301C_ICCSNO...
analyze index I_SOAC0301C_ICCSNO compute statistics;

prompt 正在處理 I_SOAC0301C_STBSNO...
analyze index I_SOAC0301C_STBSNO compute statistics;

prompt 正在處理 I_SOAC0302_ICCSNO...
analyze index I_SOAC0302_ICCSNO compute statistics;

prompt 正在處理 I_SOAC0302_STBSNO...
analyze index I_SOAC0302_STBSNO compute statistics;

prompt 正在處理 I_SOAC0402_CHCODE...
analyze index I_SOAC0402_CHCODE compute statistics;

prompt 正在處理 PK_CD000...
analyze index PK_CD000 compute statistics;

prompt 正在處理 PK_CD001...
analyze index PK_CD001 compute statistics;

prompt 正在處理 PK_CD001A...
analyze index PK_CD001A compute statistics;

prompt 正在處理 PK_CD002...
analyze index PK_CD002 compute statistics;

prompt 正在處理 PK_CD002CM003...
analyze index PK_CD002CM003 compute statistics;

prompt 正在處理 PK_CD003...
analyze index PK_CD003 compute statistics;

prompt 正在處理 PK_CD004...
analyze index PK_CD004 compute statistics;

prompt 正在處理 PK_CD005...
analyze index PK_CD005 compute statistics;

prompt 正在處理 PK_CD006...
analyze index PK_CD006 compute statistics;

prompt 正在處理 PK_CD006A...
analyze index PK_CD006A compute statistics;

prompt 正在處理 PK_CD006B...
analyze index PK_CD006B compute statistics;

prompt 正在處理 PK_CD007...
analyze index PK_CD007 compute statistics;

prompt 正在處理 PK_CD008...
analyze index PK_CD008 compute statistics;

prompt 正在處理 PK_CD008A...
analyze index PK_CD008A compute statistics;

prompt 正在處理 PK_CD008B...
analyze index PK_CD008B compute statistics;

prompt 正在處理 PK_CD008C...
analyze index PK_CD008C compute statistics;

prompt 正在處理 PK_CD009...
analyze index PK_CD009 compute statistics;

prompt 正在處理 PK_CD010...
analyze index PK_CD010 compute statistics;

prompt 正在處理 PK_CD011...
analyze index PK_CD011 compute statistics;

prompt 正在處理 PK_CD011A...
analyze index PK_CD011A compute statistics;

prompt 正在處理 PK_CD011B...
analyze index PK_CD011B compute statistics;

prompt 正在處理 PK_CD012...
analyze index PK_CD012 compute statistics;

prompt 正在處理 PK_CD013...
analyze index PK_CD013 compute statistics;

prompt 正在處理 PK_CD014...
analyze index PK_CD014 compute statistics;

prompt 正在處理 PK_CD015...
analyze index PK_CD015 compute statistics;

prompt 正在處理 PK_CD016...
analyze index PK_CD016 compute statistics;

prompt 正在處理 PK_CD017...
analyze index PK_CD017 compute statistics;

prompt 正在處理 PK_CD018...
analyze index PK_CD018 compute statistics;

prompt 正在處理 PK_CD019...
analyze index PK_CD019 compute statistics;

prompt 正在處理 PK_CD019A...
analyze index PK_CD019A compute statistics;

prompt 正在處理 PK_CD020...
analyze index PK_CD020 compute statistics;

prompt 正在處理 PK_CD021...
analyze index PK_CD021 compute statistics;

prompt 正在處理 PK_CD022...
analyze index PK_CD022 compute statistics;

prompt 正在處理 PK_CD023...
analyze index PK_CD023 compute statistics;

prompt 正在處理 PK_CD024...
analyze index PK_CD024 compute statistics;

prompt 正在處理 PK_CD025...
analyze index PK_CD025 compute statistics;

prompt 正在處理 PK_CD026...
analyze index PK_CD026 compute statistics;

prompt 正在處理 PK_CD027...
analyze index PK_CD027 compute statistics;

prompt 正在處理 PK_CD027A...
analyze index PK_CD027A compute statistics;

prompt 正在處理 PK_CD027B...
analyze index PK_CD027B compute statistics;

prompt 正在處理 PK_CD027C...
analyze index PK_CD027C compute statistics;

prompt 正在處理 PK_CD027D...
analyze index PK_CD027D compute statistics;

prompt 正在處理 PK_CD028...
analyze index PK_CD028 compute statistics;

prompt 正在處理 PK_CD029...
analyze index PK_CD029 compute statistics;

prompt 正在處理 PK_CD030...
analyze index PK_CD030 compute statistics;

prompt 正在處理 PK_CD031...
analyze index PK_CD031 compute statistics;

prompt 正在處理 PK_CD031A...
analyze index PK_CD031A compute statistics;

prompt 正在處理 PK_CD032...
analyze index PK_CD032 compute statistics;

prompt 正在處理 PK_CD033...
analyze index PK_CD033 compute statistics;

prompt 正在處理 PK_CD034...
analyze index PK_CD034 compute statistics;

prompt 正在處理 PK_CD035...
analyze index PK_CD035 compute statistics;

prompt 正在處理 PK_CD036...
analyze index PK_CD036 compute statistics;

prompt 正在處理 PK_CD037...
analyze index PK_CD037 compute statistics;

prompt 正在處理 PK_CD039...
analyze index PK_CD039 compute statistics;

prompt 正在處理 PK_CD040...
analyze index PK_CD040 compute statistics;

prompt 正在處理 PK_CD041...
analyze index PK_CD041 compute statistics;

prompt 正在處理 PK_CD042...
analyze index PK_CD042 compute statistics;

prompt 正在處理 PK_CD043...
analyze index PK_CD043 compute statistics;

prompt 正在處理 PK_CD044...
analyze index PK_CD044 compute statistics;

prompt 正在處理 PK_CD045...
analyze index PK_CD045 compute statistics;

prompt 正在處理 PK_CD046...
analyze index PK_CD046 compute statistics;

prompt 正在處理 PK_CD047...
analyze index PK_CD047 compute statistics;

prompt 正在處理 PK_CD048...
analyze index PK_CD048 compute statistics;

prompt 正在處理 PK_CD049...
analyze index PK_CD049 compute statistics;

prompt 正在處理 PK_CD050...
analyze index PK_CD050 compute statistics;

prompt 正在處理 PK_CD051...
analyze index PK_CD051 compute statistics;

prompt 正在處理 PK_CD052...
analyze index PK_CD052 compute statistics;

prompt 正在處理 PK_CD053...
analyze index PK_CD053 compute statistics;

prompt 正在處理 PK_CD054...
analyze index PK_CD054 compute statistics;

prompt 正在處理 PK_CD055...
analyze index PK_CD055 compute statistics;

prompt 正在處理 PK_CD056...
analyze index PK_CD056 compute statistics;

prompt 正在處理 PK_CD057...
analyze index PK_CD057 compute statistics;

prompt 正在處理 PK_CD058...
analyze index PK_CD058 compute statistics;

prompt 正在處理 PK_CD059...
analyze index PK_CD059 compute statistics;

prompt 正在處理 PK_CD060...
analyze index PK_CD060 compute statistics;

prompt 正在處理 PK_CD061...
analyze index PK_CD061 compute statistics;

prompt 正在處理 PK_CD062...
analyze index PK_CD062 compute statistics;

prompt 正在處理 PK_CD063...
analyze index PK_CD063 compute statistics;

prompt 正在處理 PK_CD064...
analyze index PK_CD064 compute statistics;

prompt 正在處理 PK_CD065...
analyze index PK_CD065 compute statistics;

prompt 正在處理 PK_CD065A...
analyze index PK_CD065A compute statistics;

prompt 正在處理 PK_CD066...
analyze index PK_CD066 compute statistics;

prompt 正在處理 PK_CD067A...
analyze index PK_CD067A compute statistics;

prompt 正在處理 PK_CD069...
analyze index PK_CD069 compute statistics;

prompt 正在處理 PK_CM001...
analyze index PK_CM001 compute statistics;

prompt 正在處理 PK_CM002...
analyze index PK_CM002 compute statistics;

prompt 正在處理 PK_CM003...
analyze index PK_CM003 compute statistics;

prompt 正在處理 PK_CM004...
analyze index PK_CM004 compute statistics;

prompt 正在處理 PK_CM005...
analyze index PK_CM005 compute statistics;

prompt 正在處理 PK_CODELIST...
analyze index PK_CODELIST compute statistics;

prompt 正在處理 PK_CODEUSAGE...
analyze index PK_CODEUSAGE compute statistics;

prompt 正在處理 PK_GICOLUMN...
analyze index PK_GICOLUMN compute statistics;

prompt 正在處理 PK_GIINDEX...
analyze index PK_GIINDEX compute statistics;

prompt 正在處理 PK_GITABLE...
analyze index PK_GITABLE compute statistics;

prompt 正在處理 PK_NOS002...
analyze index PK_NOS002 compute statistics;

prompt 正在處理 PK_SEND_DAC6000...
analyze index PK_SEND_DAC6000 compute statistics;

prompt 正在處理 PK_SEND_NAGRA...
analyze index PK_SEND_NAGRA compute statistics;

prompt 正在處理 PK_SEND_NDS...
analyze index PK_SEND_NDS compute statistics;

prompt 正在處理 PK_SO001...
analyze index PK_SO001 compute statistics;

prompt 正在處理 PK_SO002...
analyze index PK_SO002 compute statistics;

prompt 正在處理 PK_SO002A...
analyze index PK_SO002A compute statistics;

prompt 正在處理 PK_SO003...
analyze index PK_SO003 compute statistics;

prompt 正在處理 PK_SO004...
analyze index PK_SO004 compute statistics;

prompt 正在處理 PK_SO006...
analyze index PK_SO006 compute statistics;

prompt 正在處理 PK_SO007...
analyze index PK_SO007 compute statistics;

prompt 正在處理 PK_SO008...
analyze index PK_SO008 compute statistics;

prompt 正在處理 PK_SO009...
analyze index PK_SO009 compute statistics;

prompt 正在處理 PK_SO010...
analyze index PK_SO010 compute statistics;

prompt 正在處理 PK_SO011...
analyze index PK_SO011 compute statistics;

prompt 正在處理 PK_SO013...
analyze index PK_SO013 compute statistics;

prompt 正在處理 PK_SO014...
analyze index PK_SO014 compute statistics;

prompt 正在處理 PK_SO016...
analyze index PK_SO016 compute statistics;

prompt 正在處理 PK_SO017...
analyze index PK_SO017 compute statistics;

prompt 正在處理 PK_SO017A...
analyze index PK_SO017A compute statistics;

prompt 正在處理 PK_SO018...
analyze index PK_SO018 compute statistics;

prompt 正在處理 PK_SO019...
analyze index PK_SO019 compute statistics;

prompt 正在處理 PK_SO020...
analyze index PK_SO020 compute statistics;

prompt 正在處理 PK_SO021...
analyze index PK_SO021 compute statistics;

prompt 正在處理 PK_SO022...
analyze index PK_SO022 compute statistics;

prompt 正在處理 PK_SO023...
analyze index PK_SO023 compute statistics;

prompt 正在處理 PK_SO024...
analyze index PK_SO024 compute statistics;

prompt 正在處理 PK_SO025...
analyze index PK_SO025 compute statistics;

prompt 正在處理 PK_SO026...
analyze index PK_SO026 compute statistics;

prompt 正在處理 PK_SO027...
analyze index PK_SO027 compute statistics;

prompt 正在處理 PK_SO029...
analyze index PK_SO029 compute statistics;

prompt 正在處理 PK_SO029A...
analyze index PK_SO029A compute statistics;

prompt 正在處理 PK_SO030...
analyze index PK_SO030 compute statistics;

prompt 正在處理 PK_SO032...
analyze index PK_SO032 compute statistics;

prompt 正在處理 PK_SO033...
analyze index PK_SO033 compute statistics;

prompt 正在處理 PK_SO033DEBT...
analyze index PK_SO033DEBT compute statistics;

prompt 正在處理 PK_SO034...
analyze index PK_SO034 compute statistics;

prompt 正在處理 PK_SO035...
analyze index PK_SO035 compute statistics;

prompt 正在處理 PK_SO036...
analyze index PK_SO036 compute statistics;

prompt 正在處理 PK_SO037...
analyze index PK_SO037 compute statistics;

prompt 正在處理 PK_SO041...
analyze index PK_SO041 compute statistics;

prompt 正在處理 PK_SO042...
analyze index PK_SO042 compute statistics;

prompt 正在處理 PK_SO043...
analyze index PK_SO043 compute statistics;

prompt 正在處理 PK_SO044...
analyze index PK_SO044 compute statistics;

prompt 正在處理 PK_SO045...
analyze index PK_SO045 compute statistics;

prompt 正在處理 PK_SO046...
analyze index PK_SO046 compute statistics;

prompt 正在處理 PK_SO052...
analyze index PK_SO052 compute statistics;

prompt 正在處理 PK_SO059...
analyze index PK_SO059 compute statistics;

prompt 正在處理 PK_SO060...
analyze index PK_SO060 compute statistics;

prompt 正在處理 PK_SO062...
analyze index PK_SO062 compute statistics;

prompt 正在處理 PK_SO069...
analyze index PK_SO069 compute statistics;

prompt 正在處理 PK_SO071...
analyze index PK_SO071 compute statistics;

prompt 正在處理 PK_SO072...
analyze index PK_SO072 compute statistics;

prompt 正在處理 PK_SO073...
analyze index PK_SO073 compute statistics;

prompt 正在處理 PK_SO074...
analyze index PK_SO074 compute statistics;

prompt 正在處理 PK_SO076...
analyze index PK_SO076 compute statistics;

prompt 正在處理 PK_SO077...
analyze index PK_SO077 compute statistics;

prompt 正在處理 PK_SO078...
analyze index PK_SO078 compute statistics;

prompt 正在處理 PK_SO081...
analyze index PK_SO081 compute statistics;

prompt 正在處理 PK_SO082...
analyze index PK_SO082 compute statistics;

prompt 正在處理 PK_SO083...
analyze index PK_SO083 compute statistics;

prompt 正在處理 PK_SO084...
analyze index PK_SO084 compute statistics;

prompt 正在處理 PK_SO086...
analyze index PK_SO086 compute statistics;

prompt 正在處理 PK_SO087...
analyze index PK_SO087 compute statistics;

prompt 正在處理 PK_SO094...
analyze index PK_SO094 compute statistics;

prompt 正在處理 PK_SO103...
analyze index PK_SO103 compute statistics;

prompt 正在處理 PK_SO105...
analyze index PK_SO105 compute statistics;

prompt 正在處理 PK_SO105A...
analyze index PK_SO105A compute statistics;

prompt 正在處理 PK_SO105T...
analyze index PK_SO105T compute statistics;

prompt 正在處理 PK_SO108...
analyze index PK_SO108 compute statistics;

prompt 正在處理 PK_SO110...
analyze index PK_SO110 compute statistics;

prompt 正在處理 PK_SO111...
analyze index PK_SO111 compute statistics;

prompt 正在處理 PK_SO112...
analyze index PK_SO112 compute statistics;

prompt 正在處理 PK_SO112A...
analyze index PK_SO112A compute statistics;

prompt 正在處理 PK_SO113...
analyze index PK_SO113 compute statistics;

prompt 正在處理 PK_SO114...
analyze index PK_SO114 compute statistics;

prompt 正在處理 PK_SO116...
analyze index PK_SO116 compute statistics;

prompt 正在處理 PK_SO117...
analyze index PK_SO117 compute statistics;

prompt 正在處理 PK_SO118...
analyze index PK_SO118 compute statistics;

prompt 正在處理 PK_SO119...
analyze index PK_SO119 compute statistics;

prompt 正在處理 PK_SO123...
analyze index PK_SO123 compute statistics;

prompt 正在處理 PK_SO124...
analyze index PK_SO124 compute statistics;

prompt 正在處理 PK_SO126...
analyze index PK_SO126 compute statistics;

prompt 正在處理 PK_SO127...
analyze index PK_SO127 compute statistics;

prompt 正在處理 PK_SO135...
analyze index PK_SO135 compute statistics;

prompt 正在處理 PK_SO200...
analyze index PK_SO200 compute statistics;

prompt 正在處理 PK_SO201...
analyze index PK_SO201 compute statistics;

prompt 正在處理 PK_SOAC0101...
analyze index PK_SOAC0101 compute statistics;

prompt 正在處理 PK_SOAC0201A...
analyze index PK_SOAC0201A compute statistics;

prompt 正在處理 PK_SOAC0201B...
analyze index PK_SOAC0201B compute statistics;

prompt 正在處理 PK_SOAC0301A...
analyze index PK_SOAC0301A compute statistics;

prompt 正在處理 PK_SOAC0301B...
analyze index PK_SOAC0301B compute statistics;

prompt 正在處理 PK_SOAC0401...
analyze index PK_SOAC0401 compute statistics;

prompt 正在處理 PK_TMP004...
analyze index PK_TMP004 compute statistics;

prompt 正在處理 UK_CD000_DESCRIPTION...
analyze index UK_CD000_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD003_DESCRIPTION...
analyze index UK_CD003_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD006B_DESCRIPTION...
analyze index UK_CD006B_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD008A_DESCRIPTION...
analyze index UK_CD008A_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD008B_DESCRIPTION...
analyze index UK_CD008B_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD011B_DESCRIPTION...
analyze index UK_CD011B_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD017_DESCRIPTION...
analyze index UK_CD017_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD021_DESCRIPTION...
analyze index UK_CD021_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD024_DESCRIPTION...
analyze index UK_CD024_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD026_DESCRIPTION...
analyze index UK_CD026_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD027_DESCRIPTION...
analyze index UK_CD027_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD031A_DESCRIPTION...
analyze index UK_CD031A_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD031_DESCRIPTION...
analyze index UK_CD031_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD034_DESCRIPTION...
analyze index UK_CD034_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD035_DESCRIPTION...
analyze index UK_CD035_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD036_DESCRIPTION...
analyze index UK_CD036_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD037_DESCRIPTION...
analyze index UK_CD037_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD039_DESCRIPTION...
analyze index UK_CD039_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD041_DESCRIPTION...
analyze index UK_CD041_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD046_DESCRIPTION...
analyze index UK_CD046_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD052_DESCRIPTION...
analyze index UK_CD052_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD053_DESCRIPTION...
analyze index UK_CD053_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD055_DESCRIPTION...
analyze index UK_CD055_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD056_DESCRIPTION...
analyze index UK_CD056_DESCRIPTION compute statistics;

prompt 正在處理 UK_CD057_DESCRIPTION...
analyze index UK_CD057_DESCRIPTION compute statistics;

prompt 正在處理 UK_CM001_DESCRIPTION...
analyze index UK_CM001_DESCRIPTION compute statistics;

prompt 正在處理 UK_CM002_DESCRIPTION...
analyze index UK_CM002_DESCRIPTION compute statistics;

prompt 正在處理 UK_SOAC0101_CVTID...
analyze index UK_SOAC0101_CVTID compute statistics;

prompt 正在處理 UK_SOAC0401_CVTID...
analyze index UK_SOAC0401_CVTID compute statistics;



exec :t2 := to_char(sysdate, 'YYYY/MM/DD HH24:MI:SS');
exec :str := '<< Analyze執行完畢, 請檢查log檔, 看是否有錯誤 >> ' || :t2;
print str
exec :tt := TRUNC(86400*(to_date(:t2, 'YYYY/MM/DD HH24:MI:SS')-to_date(:t1, 'YYYY/MM/DD HH24:MI:SS')));
exec :hh := trunc(:tt/3600);
exec :ss := mod(:tt, 60);
exec :mm := (:tt - :hh*3600 - :ss) / 60;
exec :str := '合計執行時間: ' || :hh || '時' || :mm || '分' || :ss || '秒';
print str
spool off
set heading on
