
prompt
prompt Creating trigger TR_EMCEBT006_INSERT
prompt ====================================
prompt
create or replace trigger TR_EMCEBT006_INSERT
  after insert on EMC_EBT006
  for each row  
begin
    insert into EMC_EBT009
      ( EMCCUSTID, EBTCATVID, EBTCONTRACTNO, EBTCUSTID, EBTCONTRACTBDATE, EBTCONTRACTEDATE,
        EBTCUSTCNAME, EBTCUSTCONTACTPHONE, EBTCUSTCONTACTMOBILE, EBTCOMPOWNERNAME, EBTCONTACTPHONE,
        EBTITCONTACTNAME, EBTITCONTACTPHONE, EBTITCONTACTMOBILE, EBTITEMAIL, EBTINSTADDR, EBTCUSTADDR,
        EBTBILLADDR, EBTCONTRACTSTATUSCODE, EBTCONTRACTSTATUSDESC, EBTFEEPERIODCODE, EBTFEEPERIODDESC,
        EBTSERVICETYPE, EBTAGENTNAME, EBTAGENTPHONE, EBTAGENTID, EBTAGENTADDRESS, EBTIDCARDID,
        EBTCOMPANYOWNERID, EBTNONPROFITCOMPANYID, EBTCOMPANYID, PROCESSFLAG, ERRORCODE, ERRORMSG, EBTNOTES,
        EMCNOTES, CATVVALID, UPDTIME,UPDEN )                            
values( :new.EMCCUSTID , :new.EBTCATVID , :new.EBTCONTRACTNO , :new.EBTCUSTID, :new.EBTCONTRACTBDATE, :new.EBTCONTRACTEDATE, 
        :new.EBTCUSTCNAME , :new.EBTCUSTCONTACTPHONE , :new.EBTCUSTCONTACTMOBILE, :new.EBTCOMPOWNERNAME , :new.EBTCONTACTPHONE, 
        :new.EBTITCONTACTNAME, :new.EBTITCONTACTPHONE , :new.EBTITCONTACTMOBILE , :new.EBTITEMAIL, :new.EBTINSTADDR, :new.EBTCUSTADDR,
        :new.EBTBILLADDR, :new.EBTCONTRACTSTATUSCODE , :new.EBTCONTRACTSTATUSDESC , :new.EBTFEEPERIODCODE, :new.EBTFEEPERIODDESC, 
        :new.EBTSERVICETYPE ,:new.EBTAGENTNAME, :new.EBTAGENTPHONE , :new.EBTAGENTID ,:new.EBTAGENTADDRESS, :new.EBTIDCARDID,
        :new.EBTCOMPANYOWNERID , :new.EBTNONPROFITCOMPANYID, :new.EBTCOMPANYID ,:new.PROCESSFLAG , :new.ERRORCODE , :new.ERRORMSG, :new.EBTNOTES, 
        :new.EMCNOTES ,:new.CATVVALID, :new.UPDTIME,:new.UPDEN );
end;
/

