

/*
  說明: 建立EBT 之使用者帳號

  檔名: Add_User.sql
  Date: 2004.03.12
*/

DROP USER "EBTUSER";

CREATE USER "EBTUSER"  PROFILE "DEFAULT" IDENTIFIED BY "ebt" 
    DEFAULT 
    TABLESPACE "EMC" TEMPORARY 
    TABLESPACE "EMC_TEMP" ACCOUNT UNLOCK;


GRANT "CONNECT" TO "EBTUSER";



/*
以下用系統台之使用者帳號來執行
*/
ALTER USER "EBTUSER"  QUOTA UNLIMITED ON EMC;
GRANT SELECT ON SO001 TO "EBTUSER";
GRANT SELECT ON SO002 TO "EBTUSER";
GRANT SELECT ON SO003 TO "EBTUSER";
GRANT SELECT ON SO014 TO "EBTUSER";
GRANT SELECT ON SO017 TO "EBTUSER";
GRANT SELECT ON SO152 TO "EBTUSER";
GRANT SELECT ON SO509A TO "EBTUSER";

/*
以下用有權限之使用者帳號來執行
*/
GRANT CREATE ANY TRIGGER TO "EBTUSER";

/*
以下為 EBT CSIS 的帳號 => 給 CSIS 第二階段之EBT user 使用
*/
DROP USER "EBTD01";

CREATE USER "EBTD01"  PROFILE "DEFAULT" IDENTIFIED BY "ebtit01005" 
    DEFAULT 
    TABLESPACE "EMC" TEMPORARY 
    TABLESPACE "EMC_TEMP" ACCOUNT UNLOCK;


GRANT "CONNECT" TO "EBTD01";

此 user 對 EMC_EBT006(EBT完工寫入資料檔) 要有 select , insert, update 的權限
此 user 對 EMC_EBT007(EBT客戶資料異動資料檔) 要有 select , insert, update 的權限
此 user 對 EMC_EBT008(EMC客戶狀態異動資料檔)要有 select , update 的權限


/*
以下用ebtuser來執行
*/

GRANT "CONNECT" TO "EBTD01";
GRANT SELECT ON EMC_EBT006 TO "EBTD01";
GRANT INSERT ON EMC_EBT006 TO "EBTD01";
GRANT UPDATE ON EMC_EBT006 TO "EBTD01";

GRANT SELECT ON EMC_EBT007 TO "EBTD01";
GRANT INSERT ON EMC_EBT007 TO "EBTD01";
GRANT UPDATE ON EMC_EBT007 TO "EBTD01";

GRANT SELECT ON EMC_EBT008 TO "EBTD01";
GRANT UPDATE ON EMC_EBT008 TO "EBTD01";

/*
以下用ebtd01來執行
*/

DROP SYNONYM "EBTD01"."EMC_EBT006";
CREATE SYNONYM "EBTD01"."EMC_EBT006" FOR "EBTUSER"."EMC_EBT006";

DROP SYNONYM "EBTD01"."EMC_EBT007";
CREATE SYNONYM "EBTD01"."EMC_EBT007" FOR "EBTUSER"."EMC_EBT007";

DROP SYNONYM "EBTD01"."EMC_EBT008";
CREATE SYNONYM "EBTD01"."EMC_EBT008" FOR "EBTUSER"."EMC_EBT008";







DROP USER "EBTD02";

CREATE USER "EBTD02"  PROFILE "DEFAULT" IDENTIFIED BY "ebtit020982" 
    DEFAULT 
    TABLESPACE "EMC" TEMPORARY 
    TABLESPACE "EMC_TEMP" ACCOUNT UNLOCK;


GRANT "CONNECT" TO "EBTD02";

此 user 對 EMC_EBT006(EBT完工寫入資料檔) 要有 select 的權限
此 user 對 EMC_EBT007(EBT客戶資料異動資料檔) 要有 select  的權限
此 user 對 EMC_EBT008(EMC客戶狀態異動資料檔)要有 select 的權限



GRANT SELECT ON EMC_EBT006 TO "EBTD02";

GRANT SELECT ON EMC_EBT007 TO "EBTD02";

GRANT SELECT ON EMC_EBT008 TO "EBTD02";



DROP SYNONYM "EBTD02"."EMC_EBT006";
CREATE SYNONYM "EBTD02"."EMC_EBT006" FOR "EBTUSER"."EMC_EBT006";

DROP SYNONYM "EBTD02"."EMC_EBT007";
CREATE SYNONYM "EBTD02"."EMC_EBT007" FOR "EBTUSER"."EMC_EBT007";

DROP SYNONYM "EBTD02"."EMC_EBT008";
CREATE SYNONYM "EBTD02"."EMC_EBT008" FOR "EBTUSER"."EMC_EBT008";


