Attribute VB_Name = "mod_POS_Err_Return"
    
    'POS錯誤回傳值
    '
    'status：1 (Payment Gateway DataBase Error)
    'errcode： 無 (交易資料有誤，無法寫入資料庫)
    '
    'status：2 (Payment Gateway Error)
    'errcode:
    '#define PG_ERR_NO_MEMORY 1 (銀行P.G.系統記憶體配置異常)
    '#define PG_ERR_FILE_OPEN 2 (銀行P.G.系統開啟系統資料檔異常)
    '#define PG_ERR_FILE_RW 3 (銀行P.G.系統存取系統資料檔異常)*
    '#define PG_ERR_DB_CONN 4 (銀行P.G.系統連結資料庫系統異常)
    '#define PG_ERR_SEND_MER 5 (銀行P.G.無法回傳交易結果，發動Cancel交易) *
    '#define PG_ERR_WORK_FAIL 6 (Reserved)
    '#define PG_ERR_WORK_TIMEOUT 7 (銀行P.G.系統等待授權結果逾時) *
    '#define PG_ERR_BD_INIT 8 (銀行P.G.系統初始化交易資料格式異常)
    '#define PG_ERR_BD_RW 9 (銀行P.G.系統存取批次交易資料異常)
    '#define PG_ERR_CREATE_THREAD 10 (銀行P.G.系統啟動過期資料清檔程序異常)
    '#define PG_ERR_REPORT_FAIL 11 (銀行P.G.系統產生該交易批次報表異常)
    '#define PG_ERR_TIME_TOO_OLD 12 (銀行P.G.系統時間早於1970，需重新設定)
    '#define PG_ERR_CHDIR 13 (Reserved)
    '#define PG_ERR_MKDIR 14 (銀行P.G.系統啟動時產生Log或QID目錄異常)
    '#define PG_ERR_BUF_OVERFLOW 15 (銀行P.G.系統參數資料長度超過2048位元)
    '#define PG_ERR_RPT_TIMEOUT 16 (銀行P.G.系統產生reconcile report逾時)
    '#define PG_ERR_SRV_INFO 20 (銀行 P.G.系統讀取 DB Server 資料設定異常)
    '#define PG_ERR_SYS_PARA 21 (銀行P.G.系統讀取HYWEBPGDIR環境變數異常)
    '#define PG_ERR_SERVER_TYPE 22* (銀行P.G.系統Config內容設定異常)
    '#define PG_ERR_SYS_SHUTDOWN 30* (銀行P.G.系統正在進行關機程序，無法處理新進的交易)
    '#define PG_ERR_UPTO_MAX_THREAD_NO 40 (銀行P.G.同時進行處理的交易數量已達上限，請稍後再試)
    '
    'status：3 (Payment Gateway Reject)
    'errcode:
    '#define PG_REJ_TRANS_NOT_ALLOW 1 (銀行P.G.系統拒絕商家進行該型態的交易指令)
    '#define PG_REJ_LACK_PREV_TRANS 2 (違反交易法則，銀行P.G.系統無法作業)
    '#define PG_REJ_VOID_PREV_TRANS 3 (違反交易法則，銀行P.G.系統無法void原已取消的交易)
    '#define PG_REJ_BAD_SETTYPE 4 (交易指令不在銀行P.G.系統的CAT/EDC定義範圍內)
    '#define PG_REJ_BAD_COMPSTATE 5 (違反交易法則，銀行P.G.系統無法判讀交易完成狀態)
    '#define PG_REJ_BAD_STATUS 6 (銀行P.G.系統無法儲存未approved的成功交易)
    '#define PG_REJ_INVALID_AMT 7 (交易金額違反法則，銀行P.G.系統無法處理)
    '#define PG_REJ_BAD_MERCID 8 (MerchantID資料長度超過有效範圍)
    '#define PG_REJ_BAD_TERMID 9 (TerminalID資料長度超過有效範圍)
    '#define PG_REJ_BAD_SERVERTYPE 10 (交易型態不在銀行P.G.系統的SET/SSL類別定義內)
    '#define PG_REJ_BAD_EC_INDICATOR 11 (銀行P.G.系統設定交易資料內EC_INDICATOR異常)
    '#define PG_REJ_BRAND_NOT_MATCH 12 (分期付款中交易資料內信用卡BRAND不一致)
    '#define PG_REJ_BAD_RECURID 13 (銀行P.G.系統設定交易資料內分期期數異常)
    '#define PG_REJ_XID_DUP 14 (銀行P.G.拒絕重複的交易代碼XID)
    '#define PG_REJ_XID_LOCKED 15 (該筆SSL交易代XID交易正被處理中)
    '#define PG_REJ_XID_MISS_LOCK 16 (銀行P.G.系統偵測到交易中的資料未進行Lock保護機制)
    '#define PG_REJ_STATE_VOID 17 (銀行P.G.系統無法處理原void的交易資料)
    '#define PG_REJ_DB_EXPIRE 18 (Reserved：交易資料已列存在過期的歷史資料庫，無法進行交易)
    '#define PG_REJ_AUTH_EXPIRE 19 (該授權交易已超過有效期限，銀行P.G.系統無法繼續執行該交易)
    '#define PG_REJ_CREDIT_EXPIRE 20 (該退款交易已超過有效期限，銀行P.G.系統無法繼續執行該交易)
    '#define PG_REJ_ORG_AMT_NOT_MATCH 21 (交易資料的授權金額比對有問題)
    '#define PG_REJ_PAN_NOT_MATCH 22 (交易資料的信用卡卡號比對有問題)
    '#define PG_REJ_EXPDATE_NOT_MATCH 23 (交易資料的信用卡有效期限比對有問題)
    '#define PG_REJ_APPROVECODE_NOT_MATCH 24 (交易資料的授權碼比對有問題)
    '#define PG_REJ_REF_ID_NOT_MATCH 25 (銀行P.G.系統無法判別前次的交易資料)
    '#define PG_REJ_PURCHDATA_NOT_MATCH 26 (Reserved：分期付款的金額有誤)
    '#define PG_REJ_NULL_TM_RESPCODE 27 (批次結帳作業無回應狀態值)
    '#define PG_REJ_NULL_RESPCODE 28 (批次結帳作業無回應狀態值)
    '#define PG_REJ_UNEXPECT_TM_RESPCODE 29 (批次結帳結果的狀態值不在定義範圍內)
    '#define PG_REJ_UNEXPECT_RESPCODE 30 (批次結帳結果的狀態值不在定義範圍內)
    '#define PG_REJ_TERM_LOCKED 31 (該商家目前有交易正在進行，銀行P.G.系統無法鎖定該特店)
    '#define PG_REJ_TERM_UNKNOW 32 (銀行P.G.系統無法判別商家目前的MerchantID及TerminalID)
    '#define PG_REJ_BATCH_UNKNOW 33 (銀行 P.G.系統無法判別商家目前欲進行的交易批次)
    '#define PG_REJ_BATCH_INACTIVE 34 (該批次編號需先進行BatchOpen的動作才能使用)
    '#define PG_REJ_TRACENO_FULL 35 (商家的同批次內的交易筆數已達銀行P.G.系統的上限，需進行批次結帳的作業)
    '#define PG_REJ_BATCHNO_FULL 36 (商家的交易批次編號已達銀行P.G.系統的上限，需進行批次清除的作業)
    '#define PG_REJ_BATCH_IN_OPEN 37 (銀行P.G.系統無法對已啟用的批次編號再進行開啟作業)
    '#define PG_REJ_BATCH_IN_CLOSE 38 (銀行P.G.系統無法對已關閉的批次編號再進行結帳作業)
    '#define PG_REJ_BATCH_IN_SETTLE 39 (Reserved)
    '#define PG_REJ_BATCH_STATUS 40 (銀行P.G.系統拒絕在目前的批次狀態執行該交易)
    '#define PG_REJ_BATCH_OCCUPIED 41 (該商家的交易批次編號已使用中)
    '#define PG_REJ_DUP_BATCH 42 (銀行P.G.系統無法判別商家目前使用中的交易批次編號)
    '#define PG_REJ_NO_ACTIVE_BATCH 43 (商家尚無啟用中的批次資料可供結帳作業)
    '#define PG_REJ_NO_CVV2_CODE 44 (交易資料無CVV2驗證碼)
    '#define PG_REJ_INVALID_RECUR_AMT 51 (分期付款交易，請款或退款金額必須等於授權金額)
    '
    'status：4 (TM Error)
    '
    'status：5 (TM Reject)
    'errcode:
    '#define TM_ERR_RESPONSE_TIMEOUT 1 (銀行CardPool收單系統逾時回應訊息)
    '#define TM_ERR_INVALID_SSLTYPE 2 (銀行P.G.系統上傳的交易型態異常)
    '#define TM_ERR_TRANS_DATA 3 (銀行P.G.系統上傳的交易資料格式異常)
    '#define TM_ERR_COMMUNICATION_FAIL 4 (銀行P.G.系統與CardPool收單系統系統連線失敗)
    '#define TM_ERR_TRANS_NOT_ALLOW 5 (銀行CardPool收單系統回應訊息異常)
    '#define TM_ERR_BUFFER_FULL 6 (銀行P.G.系統交易處理滿載中)
    '#define TM_ERR_CARD_NOT_ACCEPT 7 (交易資料內的信用卡不在銀行P.G.系統支援的範圍內)
    '#define TM_ERR_UPLOAD_ERROR 8 (Reserved：交易批次資料上傳CardPool收單系統異常)
    '#define TM_ERR_CANCEL_NOT_ALLOW 9 (銀行P.G.系統不允許該交易進行Cancel作業)
    '#define TM_ERR_CPS_NOT_RESPONSE 10 (銀行P.G.系統等不到CardPool收單系統系統回應交易結果)*
    '#define TM_ERR_RESTART 11 (銀行P.G.系統重新啟動中)*
    '#define TM_ERR_OS_ERR 12 (銀行P.G主機作業系統異常)*
    '#define TM_ERR_BANK_NOT_SUPPORT 13 (銀行P.G.無法對其他銀行特店進行收單)
    '#define TM_ERR_QUEUE_TIMEOUT 14 (銀行 P.G 系統與 CardPool 收單系統間網路忙線中，請稍
    '後重新交易)
    '#define TM_ERR_RETR_REF_NOT_MATCH 40 (CardPool 收單系統所回應的該資料欄位異常)
    '#define TM_ERR_MSGTYPE_NOT_MATCH 30 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_PROCCODE_NOT_MATCH 31 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_AMT_NOT_MATCH 32 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_TRACENO_NOT_MATCH 33 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_NII_NOT_MATCH 34 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_RESPCODE_NOT_MATCH 35 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_TERMINAL_NOT_MATCH 36 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_TIME_NOT_MATCH 37 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_DATE_NOT_MATCH 38 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_PAN_INFO_NOT_MATCH 39 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_MERCHANT_NOT_MATCH 41 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_CURRENCY_NOT_MATCH 42 (CardPool收單系統所回應的該資料欄位異常)
    '#define TM_ERR_PREFIX_NOT_MATCH 43 (CardPool收單系統所回應的該資料欄位異常)
    '
    'status：8 (Bank Error) ※此部份的異常交易，網路商家/持卡人，如需要請向收單銀行或發卡銀行了解原因※
    'errcode:
    '#define APPROVED 00 (Reserved)
    '#define REFER TO CARD ISSUER 01 (請與您的發卡銀行聯絡有關網路交易授權失敗的原因)
    '#define REFER TO CARD ISSUER 02 (特殊狀況，請與發卡銀行聯絡有關網路交易授權失敗的原因)
    '#define INVALID MERCHANT 03 (未經授權使用的Merchant ID)
    '#define DECLINED 05 (發卡銀行無任何因素地拒絕該卡號的網路交易)*
    '#define RESERVED TO ISO USE 06
    '#define CAPTURE CARD 07 (特殊狀況，失卡，請與發卡銀行聯絡)
    '#define RESERVED TO ISO USE 08~11
    '#define INVALID TRANSACTION 12 (無效的交易，交易資料異常)
    '#define INVALID AMOUNT 13 (無效的金額，消費金額異常)
    '#define INVALID CARD NUMBER 14 (無效的卡號資料)
    '#define INVALID ISSUER 15 (無效的發卡銀行)
    '#define RESERVED TO ISO USE 16~18
    '#define RE-ENTER TRANSACTION 19 (銀行系統拒絕重複的交易)
    '#define INVALID RESPONSE 20 (Reserved)
    '#define FORMAT ERROR 30 (系統無法判別交易的資料格式)
    '#define BANK NOT SUPPORTED 31 (Reserved, bank not supported by switch)
    '#define COMPLETED PARTIALLY 32 (Reserved, completed partially)
    '#define EXPIRED CARD 33 (發卡銀行：您的信用卡有效期限輸入錯誤)
    '#define SUSPECTED FRAUD 34 (Reserved, suspected fraud故意欺騙)
    '#define CALL HELP 35 (Reserved, card acceptor call acquirer security)
    '#define RESTRICTED CARD 36 (Reserved, restricted card受限卡)
    '#define CARD HELP 37 (Reserved, card acceptor call acquirer security)
    '#define PIN TRY LOCK 38 (Reserved, allowable PIN tries exceeded錯誤三次)
    '#define NO CREDIT ACCOUNT 39 (系統無法獲得持卡者的信用資料)
    '#define REQUEST NOT SUPPORTED 40 (Reserved, requested function not supported)
    '#define LOST CARD 41 (信用卡已掛失)
    '#define NO UNIVERSAL ACCOUNT 42 (Reserved, no universal account)
    '#define STOLEN CARD 43 (拾獲失竊卡)
    '#define NO INVESTMENT ACCOUNT 44 (Reserved, no investment account)
    '#define RESERVED TO ISO USE 45~50
    '#define NO SUFFICIENT FUNDS 51 (發卡銀行：消費額度不足)
    '#define RESERVED TO ISO USE 52 (No chequing account)~53(No saving account)
    '#define EXPIRED CARD 54 (信用卡有效期限過期)
    '#define INCORRECT PIN 55 (Reserved, incorrect personal identification number)
    '#define NO CARD RECORD 56 (系統無法獲得持卡者的信用卡紀錄)
    '#define TRANS. NOT PERMITTED TO CARDHOLD 57 (拒絕持卡者進行該網路交易)
    '#define TRANS. NOT PERMITTED TO TERMINAL 58 (拒絕商家進行該網路交易)
    '#define SUSPECTED CARD 59 (嫌疑卡)
    '#define CALL HELP 60 (Reserved, card acceptor call acquirer)
    '#define EXCCEEDS WITHDRAW 61 (Reserved, amount too high)
    '#define RESTRICTED CARD 62 (Reserved, card have to check)
    '#define CVC ERROR 63 (信用卡安全識別碼錯誤, security violation)*
    '#define ORIGINAL AMOUNT INCORRECT 64 (相關交易的金額前後不符)
    '#define EXCCEEDS WITHDRAW 65 (Reserved, exceeds withdrawal frequency limit)
    '#define CALL HELP 66 (Reserved, card acceptor call acquirer’s security department)
    '#define HARD CAPTURE 67 (Reserved, requires that card be picked up at ATM)
    '#define RESPONSE RECEIVED TOO LATE 68 (Reserved)
    '#define RESERVED TO ISO USE 69~74
    '#define PIN TRIES EXCEES 75 (Reserved, pin try too many times)
    '#define RESERVED TO ISO USE 76~88
    '#define INVALID TERMINAL 89 (Reserved,未經授權使用的Terminal ID)
    '#define SYSTEM NOT AVAILABLE 90 (Reserved, cutoff is in process, transaction can be sent again in a few miniutes)
    '#define ISSUER INOPERATIVE 91 (Reserved, issuer or switch center is inoperative)
    '#define NETWORK ROUTING ERROR 92 (Reserved, financial institution or intermediate net. facility cannot be found for routing)
    '#define VIOLATION OF LAW 93 (Reserved, transaction cannot be completed)
    '#define DUPLICATE TRANSMISSION 94 (Reserved)
    '#define RECONCILE ERROR 95 (Reserved, batch upload started)
    '#define SYSTEM MALFUNCTION 96 (Reserved)
    '
    'status：9 (SSL HyPOS Server Error)
    'errcode:
    '#define ST_MER_SERVER_BUSY nc* (伺服器忙碌中)
    '#define ST_MER_DB_NOT_MATCH nd (交易資料在商家HyPOS系統的資料不一致)
    '#define ST_MER_EXISTING_ENTRY ne (該筆為已請款交易，無法再進行請款)
    '#define ST_MER_MISSING_ELEMENT ng* (缺少所必須的欄位)
    '#define ST_MER_INTERNAL ni* (伺服器系統錯誤)
    '#define ST_MER_INVALID_MESSAGE nm* (從API或PG接收到的資料或格式錯誤)
    '#define ST_MER_RECV_TIMEOUT no (接收資料逾時)
    '#define ST_MER_RECV_PG_ERROR np (網路通訊異常：無法獲得銀行 P.G.系統的交易結果)
    '#define ST_MER_SEND_PG_ERROR nq (網路通訊異常：無法傳送交易到銀行P.G.系統)
    '#define ST_MER_SYSTEM_ERROR ns (在伺服器中找不到該特店相關資料)
    '#define ST_MER_INVALID_FORMAT nt (POS伺服器接收到的資料有誤)
    '
    'status：10 (SSL EZPOS System Error)
    'errcode:
    '#define SSL_CONFIG_FILE_ERROR 1 (HyPOSEZ Server 系統設定異常)
    '#define SSL_CONFIG_FILE_NOT_EXIST 2 (HyPOSEZ Server系統設定檔不存在)
    '#define SSL_MEMORY_ERROR 3 (HyPOSEZ Server系統記憶體配置異常)
    '#define SSL_CONNECT_HYPOS_ERROR 4 (HyPOSEZ無法連結到SSL HyPOS Server)
    '#define SSL_MERCHANT_DB_DIR_WRITE_ERROR 5(Reserved)
    '#define SSL_STOP 6 (Reserved)
    '#define SSL_LOCK_ERROR 7 (該筆交易正在HyPOSEZ Server進行中)
    '#define SSL_LOCK_BUSY 8 (Reserved)
    '#define SSL_UNKNOWN_ERROR 10 (其他不明原因的錯誤)
    '#define SSLEZ_NOT_MATCH_ERROR 11 (HyPOSEZ 帳管系統無此訂單編號)
    '#define SSLEZ_CONF_FILE_ERROR 12 (HyPOSEZ系統設定異常)
    '#define SSLEZ_DBPATH_NOT_FOUND_ERROR 13 (Reserved)
    '#define SSLEZ_DBFILE_NOT_FOUND_ERROR 14 (HyPOSEZ無此交易相關紀錄檔)
    '#define SSLEZ_XIDFILE_ERROR 15 (HyPOSEZ交易紀錄中XID交易序號格式異常)
    '#define SSLEZ_UPDATEDB_SIGNAL_ERROR 16 (HyPOSEZ開啟交易紀錄檔異常)
    '#define SSLEZ_STOP 17 (HyPOSEZ帳管系統交易查詢異常中斷)
    '#define SSLAP_MERID_ERROR 18 (URL-Link網頁整合格式異常─網路特店編號)
    '#define SSLAP_LIDM_ERROR 19 (URL-Link網頁整合格式異常─商場訂單編號)
    '#define SSLAP_PURCHAMT_ERROR 20 (URL-Link網頁整合格式異常─訂單交易金額)
    '#define SSLAP_AMTEXP_ERROR 21 (URL-Link網頁整合格式異常─交易幣別指數)
    '#define SSLAP_EXPDATE_ERROR 22 (信用卡有效期限長度格式異常)
    '#define SSLAP_PAN_ERROR 23 (信用卡卡號長度格式異常)
    '#define SSLAP_AUTHRRPID_ERROR 27 (HyPOSEZ Internal Error：AUTHRRPID 交易序號異常)
    '#define SSLAP_CURRENCY_ERROR 24 (URL-Link網頁整合格式異常─訂單交易幣別)
    '#define SSLAP_INIFILE_ERROR 25 (HyPOSEZ Internal Error：系統設定檔異常)
    '#define SSLAP_XID_ERROR 26 (HyPOSEZ Internal Error：XID交易序號異常)
    '#define SSLAP_CREDRRPID_ERROR 28 (HyPOSEZ Internal Error：CREDRRPID交易序號異常)
    '#define SSLAP_BATCHID_ERROR 29 (HyPOSEZ Internal Error：交易批次編號異常)
    '#define SSLAP_UPDATEDB_SIGNAL_ERROR 30 (HyPOSEZS開啟交易紀錄檔異常)
    '#define SSLAP_CONNECT_TIMEOUT_ERROR 31 (HyPOSEZ與SSL HyPOS Server連線交易異常)
    '#define SSLAP_LOGIN_ERROR 32 (交易網頁資料已超過有效時間，請重新執行)
    '
    'status：12 (3D Secure Error / Risk Constraint Error)
    'errcode:
    '#define VISA_3DSECURE_CAVVCHK_ERROR 11 (銀行CardPool檢核交易3D驗證碼失敗)
    '#define VISA_3DSECURE_OVER_AUTHAMT 21 (單日累積授權金額超過銀行P.G.上限)
    '#define VISA_3DSECURE_OVER_AUTHNUM 22 (單日累積授權筆數超過銀行P.G.上限)
    '#define VISA_3DSECURE_OVER_SGL_AUTHAMT 23 (單筆授權金額超過銀行P.G.上限)
    '#define VISA_3DSECURE_INACTIVE 24 (銀行P.G.暫時停止特店交易)
    '#define VISA_3DSECURE_INVALID_CARDRANGE 25 (銀行P.G.或特店目前不接受該類信用卡交易)
    '#define VISA_3DSECURE_IN_PANBLACKLIST 26 (銀行P.G.或特店目前不接受該卡號交易)
    '#define VISA_3DSECURE_NO_MERDATA 27 (銀行 P.G.尚未收到特店的收單申請)
    '#define VISA_3DSECURE_DENIAL 41 (持卡人輸入 3D 密碼驗證錯誤)
    '#define VISA_3DSECURE_INVALID_ATTRIBUTE 28 (銀行P.G.尚未收到特店申請該項服務)
    '#define VISA_3DSECURE_PROCESS_ERROR 40 (3D驗證失敗)
    '#define VISA_3DSECURE_NONPARTICIPATING_PAN 42(持卡人未申請3D驗證服務)
    '#define VISA_3DSECURE_ENROLLEDCHK_PAN 43 (無法判讀卡號所屬的3D發卡行資訊)
    '#define VISA_3DSECURE_PARES_NONE 44 (無法收到 3D 發卡行的認證回應)
    '#define VISA_3DSECURE_PARES_UNKNOWN 45 (無法判讀 3D 發卡行回應的認證資料)
