
----- ミ祇布 USER ----
CREATE USER EMCINV IDENTIFIED BY "E0928INV"
  DEFAULT TABLESPACE EMCINV
  TEMPORARY TABLESPACE EMCINV_TMP
  PROFILE DEFAULT;
  

-----  role privileges --------------  
GRANT CONNECT TO EMCINV;
GRANT EXEC_PACKAGE TO EMCINV;
GRANT RESOURCE TO EMCINV;


---- system privileges ------
GRANT ANALYZE ANY TO EMCINV;
GRANT CREATE ANY VIEW TO EMCINV;
GRANT CREATE DATABASE LINK TO EMCINV;
GRANT CREATE PUBLIC DATABASE LINK TO EMCINV;
GRANT CREATE SYNONYM TO EMCINV;
GRANT INSERT ANY TABLE TO EMCINV;
GRANT SELECT ANY DICTIONARY TO EMCINV;
GRANT SELECT ANY SEQUENCE TO EMCINV;
GRANT UNLIMITED TABLESPACE TO EMCINV;
  

GRANT SELECT ANY TABLE TO EMCINV;

---- 祇布╰参穝キ2產╰参祇布秨ミ戈舦( USER=EMCINV ) ----
GRANT UPDATE ON "EMCCT.SO033" TO "EMCINV";
GRANT UPDATE ON "EMCCT.SO034" TO "EMCINV";

GRANT UPDATE ON "EMCNTY.SO033" TO "EMCINV";
GRANT UPDATE ON "EMCNTY.SO034" TO "EMCINV";


---- 祇布╰参硓筁 dblink 穝いキ2產╰参祇布秨ミ戈舦( USER=COM ) ----
GRANT UPDATE ON "EMCNCC.SO033" TO "COM";
GRANT UPDATE ON "EMCNCC.SO034" TO "COM";

GRANT UPDATE ON "EMCFM.SO033" TO "COM";
GRANT UPDATE ON "EMCFM.SO034" TO "COM";
