spool c:\temp\CreateMvct.log

prompt 起始時間
select to_char(sysdate,'YYYY/MM/DD HH24:MI:SS') TIME from dual@catvn.US.ORACLE.COM;


prompt 前置動作
prompt 	1.要將tc的 data 放到北平台來
prompt 	2.在我的電腦中,設定好Net 8, 分別使用 alias "tc" 連接到tc,alias "4800" 連接到北平台
prompt 	  而北平台主機上也已經設定好用 alias "tc" 連接到tc.
prompt 	3.在北平台上建立了兩個 tablespace : MV 和 REPORT_NDX, 希望將TC的data以及 index分別放在這兩個 tablespace中
prompt 	4.在北平台上建立一個 tablespace:MV_TMP, 用來做排序用
prompt 	5.在北平台上建立user:EMCTC, 使其 default tablespace 是MV, default temporary tablespace 是MV_TMP
prompt 	  並賦予EMCTC適度的權限,指令如下: (特別留意最後一行 grant 指令)
prompt 		GRANT "CONNECT" TO "EMCTC"@catvn.US.ORACLE.COM;
prompt 		GRANT "DBA" TO "EMCTC"@catvn.US.ORACLE.COM;
prompt 		GRANT "RESOURCE" TO "EMCTC"@catvn.US.ORACLE.COM;
prompt 		GRANT UNLIMITED TABLESPACE TO "EMCTC"@catvn.US.ORACLE.COM;
prompt 		ALTER USER "EMCTC" DEFAULT ROLE ALL@catvn.US.ORACLE.COM;
prompt 		grant create table to "EMCTC"@catvn.US.ORACLE.COM;
prompt 		grant create view to "EMCTC"@catvn.US.ORACLE.COM;
prompt 		grant create sequence to "EMCTC"@catvn.US.ORACLE.COM;
prompt 		grant query rewrite to "EMCTC"@catvn.US.ORACLE.COM;

prompt   注意: 請將 EMCTC 修改成適當的 owner
prompt   注意: 請修改 system 的密碼以及連線的 alias
prompt   注意: 請修改 EMCTC 的密碼以及連線的 alias
prompt   注意: 請修改 DbLink 的內容
prompt   注意: 請修改  REPORT_NDX 為正確的 Index tablespace name
prompt   注意: DBMS_REFRESH.MAKE 中 2002102501300 => 表示 2002/10/25 01:30:00 將第一次執行此job. => 將此修改成想要的日期
prompt   注意:                          SYSDATE+1 => 表示以後每一天執行一次此job. => 將此修改成想要的天數



--CONNECT EMCTC/EMCTC@4800


prompt 為何用 SDTCMIS ? 請連接到 tc, 然後執行 SQL>select * from global_name@catvn.US.ORACLE.COM; 
--CREATE DATABASE LINK nt CONNECT TO EMCnt  IDENTIFIED BY EMCnt USING 'nt'@catvn.US.ORACLE.COM;



--CONNECT system/66503972@catv1@catvn.US.ORACLE.COM;


prompt CD001 ~ CD010


CREATE MATERIALIZED view CD000   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD000@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD001   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD001@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD001A   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD001A@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD002   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD002@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD002CM003   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD002CM003@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view CD003   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD003@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD004   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD004@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD005   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD005@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD006   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD006@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD006A   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD006A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD006B   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD006B@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD007   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD007@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD008   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD008@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD008A   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD008A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD008B   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD008B@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD008C   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD008C@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD009   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD009@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD010   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD010@catvn.US.ORACLE.COM;








prompt CD011 ~ Cd020

CREATE MATERIALIZED view CD011   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD011@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD011A   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD011A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD011B   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD011B@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD012   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD012@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view CD013   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD013@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD014   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD014@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD015   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD015@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD016   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD016@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view CD017   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD017@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD018   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD018@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD018tmp   USING INDEX TABLESPACE "REPORT_NDX" REFRESH with rowid ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD018tmp@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD019   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD019@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD019A   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD019A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD019b   USING INDEX TABLESPACE "REPORT_NDX" REFRESH with rowid ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD019b@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD019CD004  USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD019CD004@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD019SO017  USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD019SO017@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD020   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD020@catvn.US.ORACLE.COM;




prompt CD021 ~ Cd030

CREATE MATERIALIZED view CD021   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD021@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD022   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD022@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD022a   USING INDEX TABLESPACE "REPORT_NDX" REFRESH with rowid ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD022a@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD022CD019  USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD022CD019@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD023   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD023@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD024   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD024@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD025   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD025@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD026   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD026@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view CD027   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD027@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD027A   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD027A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD027B   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD027B@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD027C   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD027C@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD027D   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD027D@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view CD028   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD028@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD029   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD029@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD030   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD030@catvn.US.ORACLE.COM;




prompt CD031 ~ Cd040

CREATE MATERIALIZED view CD031   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD031@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD031A   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD031A@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD032   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD032@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD033   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD033@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD034   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD034@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD035   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD035@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD036   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD036@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view CD037   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD037@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD039   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD039@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD040   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD040@catvn.US.ORACLE.COM;





prompt CD041 ~ Cd050

CREATE MATERIALIZED view CD041   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD041@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD042   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD042@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD043   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD043@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD044   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD044@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD045   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD045@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD046   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD046@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view CD047   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD047@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD048   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD048@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD048a   USING INDEX TABLESPACE "REPORT_NDX" REFRESH with rowid ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD048a@catvn.US.ORACLE.COM;



CREATE MATERIALIZED view CD049   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD049@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD050   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD050@catvn.US.ORACLE.COM;




prompt Cd051 以後

CREATE MATERIALIZED view CD051   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD051@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD052   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD052@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD053   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD053@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD054   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD054@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD055   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD055@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD056   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD056@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view CD057   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD057@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD057A   USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD057A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD058   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD058@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view CD059   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD059@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD060   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD060@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD061   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD061@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD062   USING INDEX TABLESPACE "REPORT_NDX" REFRESH with rowid ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD062@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD063   USING INDEX TABLESPACE "REPORT_NDX" REFRESH with rowid ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD063@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD064   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD064@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD065   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD065@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD065A   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD065A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD066   USING INDEX TABLESPACE "REPORT_NDX" REFRESH with rowid ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD066@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD067   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD067@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CD069   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD069@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CM001   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CM001@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CM002   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CM002@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CM003   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CM003@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CM004   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CM004@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view CM005   USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CM005@catvn.US.ORACLE.COM;


prompt SO001~SO010

CREATE MATERIALIZED view SO001 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO001@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO002 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO002@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO002A USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO002A@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO003 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO003@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO004 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO004@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO005 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO005@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO006 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO006@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view SO007 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO007@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO008 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO008@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO009 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO009@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO010 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO010@catvn.US.ORACLE.COM;





prompt SO011~SO020

CREATE MATERIALIZED view SO011 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO011@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO012 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO012@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO013 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO013@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO014 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO014@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO015 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO015@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO016 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO016@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO017 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO017@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO017A USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO017A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO017tmp USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO017tmp@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO018 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO018@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO019 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO019@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO020 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO020@catvn.US.ORACLE.COM;





prompt SO021~SO030

CREATE MATERIALIZED view SO021 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO021@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO022 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO022@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO023 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO023@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO024 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO024@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO026 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO026@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO027 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO027@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO028 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO028@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO029 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO029@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO029A USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO029A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO030 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO030@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO030A USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO030A@catvn.US.ORACLE.COM;



prompt SO031~SO040

CREATE MATERIALIZED view SO031 USING INDEX TABLESPACE "REPORT_NDX" REFRESH with rowid ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO031@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO032 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO032@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO032BREAK USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO032BREAK@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO033 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO033@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO033DEBT USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO033DEBT@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO034 USING INDEX TABLESPACE "REPORT_NDX" 
REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO034@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO035 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO035@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO036 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO036@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO037 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO037@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO038 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO038@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO039 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO039@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO040 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO040@catvn.US.ORACLE.COM;




prompt SO041~SO080

CREATE MATERIALIZED view SO041 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO041@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO042 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO042@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO043 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO043@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO044 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO044@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO045 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO045@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO046 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO046@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO052 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO052@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view SO062 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO062@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view SO069 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO069@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO071 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO071@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO072 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO072@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO073 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO073@catvn.US.ORACLE.COM;




prompt SO081~SO100



CREATE MATERIALIZED view SO082 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO082@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO083 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO083@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO084 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO084@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO088 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO088@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO089 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO089@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO090 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO090@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO091 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO091@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO092 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO092@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO093 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO093@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO094 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO094@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view SO098 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO098@catvn.US.ORACLE.COM;





prompt SO101~SO130


CREATE MATERIALIZED view SO105 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO105@catvn.US.ORACLE.COM;

CREATE MATERIALIZED view SO105A USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO105A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO105B USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO105B@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO105C USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO105C@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO105D USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO105D@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO105T USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO105T@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view SO106 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO106@catvn.US.ORACLE.COM;



CREATE MATERIALIZED view SO110 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO110@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO111 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO111@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO112 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO112@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO112A USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO112A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO113 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO113@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO114 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO114@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO115 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO115@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO116 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO116@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO117 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO117@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO118 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO118@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO119 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO119@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO120 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO120@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO121 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO121@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO122 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO122@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO123 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO123@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO124 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO124@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO125 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO125@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO126 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO126@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO127 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO127@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO131 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO131@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO132 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO132@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO133 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO133@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO134 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO134@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO135 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO135@catvn.US.ORACLE.COM;

prompt SO200~SO600




CREATE MATERIALIZED view SO301A USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO301A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO301B USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO301B@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO302A USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO302A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO302B USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO302B@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view SO303 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO303@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO304 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO304@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view SO501A USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO501A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO504 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO504@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO507 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO507@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO508 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO508@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO509 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO509@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO509A USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO509A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO510 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO510@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO511a USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO511a@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO511b USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO511b@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO511c USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO511c@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SO511z USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SO511z@catvn.US.ORACLE.COM;




prompt others

CREATE MATERIALIZED view SOAC0101 USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0101@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SOAC0102 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0102@catvn.US.ORACLE.COM;


CREATE MATERIALIZED view SOAC0103 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0103@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SOAC0201A USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0201A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SOAC0201B USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0201B@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SOAC0201C USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0201C@catvn.US.ORACLE.COM;



CREATE MATERIALIZED view SOAC0201D USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0201D@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SOAC0201E USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0201E@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SOAC0202 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0202@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SOAC0203A USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0203A@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SOAC0203B USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0203B@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SOAC0204 USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOAC0204@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view SOPOWER USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.SOPOWER@catvn.US.ORACLE.COM;
CREATE MATERIALIZED view send_nagra USING INDEX TABLESPACE "REPORT_NDX" REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.send_nagra@catvn.US.ORACLE.COM;


prompt 注意: 若 4800 中該 table 已經存在, 則正確之指令如下:
prompt 注意: CREATE MATERIALIZED view CD010  ON PREBUILT TABLE USING INDEX TABLESPACE "REPORT_NDX" REFRESH FAST 
prompt 注意: 		ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  emcct.CD010@catvn.US.ORACLE.COM;
prompt 注意: 若要取消此項設定,範例指令如下:SQL>DROP MATERIALIZED view CD008@catvn.US.ORACLE.COM;
prompt 注意: 此指令執行完成後, data 也就抓取過來了	


/*
CONNECT system/66503072@catvn.US.ORACLE.COM;

execute DBMS_REFRESH.MAKE('emcct.CD1','emcct.CD000,emcct.CD001,emcct.CD001A,emcct.CD002,emcct.CD002CM003,emcct.CD003,emcct.CD004,
emcct.CD005,emcct.CD006,emcct.CD006A,emcct.CD006B,emcct.CD007,emcct.CD008,emcct.CD008A,emcct.CD008B, emcct.CD008C,emcct.CD009,emcct.CD010',
to_date('20021026013000','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.CD2','emcct.CD011,emcct.CD011A,emcct.CD012,emcct.CD013,emcct.CD014,emcct.CD015,emcct.CD016,
emcct.CD017,emcct.CD018, emcct.CD019,emcct.CD019A,emcct.CD019CD004,emcct.CD019SO017,emcct.CD020',
to_date('20021026013200','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.CD3','emcct.CD021,emcct.CD022,emcct.CD022CD019,emcct.CD023,emcct.CD024,emcct.CD025,emcct.CD026,
emcct.CD027,emcct.CD027A, emcct.CD027B, emcct.CD027C, emcct.CD027D,emcct.CD028, emcct.CD029,emcct.CD030',
to_date('20021026013400','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.CD4','emcct.CD031,emcct.CD032,emcct.CD033,emcct.CD034,emcct.CD035,emcct.CD036,
emcct.CD037,emcct.CD039,emcct.CD040',
to_date('20021026013600','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;

execute DBMS_REFRESH.MAKE('emcct.CD5','emcct.CD041,emcct.CD042,emcct.CD043,emcct.CD044,emcct.CD045,emcct.CD046,
emcct.CD047,emcct.CD048,emcct.CD048A,emcct.CD049,emcct.CD050',
to_date('20021028013800','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.CD6','emcct.CD051,emcct.CD052,emcct.CD053,emcct.CD054,emcct.CD055,emcct.CD056,
emcct.CD057,emcct.CD058,emcct.CD059,emcct.CD060,emcct.CD061,emcct.CM001,emcct.CM002,emcct.CM003,emcct.CM004,emcct.CM005',
to_date('20021028014000','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.SO1','emcct.SO001,emcct.SO002,emcct.SO002A,emcct.SO003,
emcct.SO004,emcct.SO005,emcct.SO006,emcct.SO007,emcct.SO008,emcct.SO009,emcct.SO010',
to_date('20021028014200','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.SO2','emcct.SO011,emcct.SO012,emcct.SO013,emcct.SO014,emcct.SO015,emcct.SO016,emcct.SO017A,
emcct.SO019,emcct.SO020',
to_date('20021028014800','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.SO3','emcct.SO021,emcct.SO022,emcct.SO023,emcct.SO024,emcct.SO025,emcct.SO026,emcct.SO027,
emcct.SO028,emcct.SO029,emcct.SO029A,emcct.SO030,emcct.SO030A',
to_date('20021028015400','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;



execute DBMS_REFRESH.MAKE('emcct.SO4','emcct.SO031,emcct.SO032,emcct.SO032BREAK,emcct.SO033,emcct.SO034,emcct.SO035,emcct.SO036,
emcct.SO037,emcct.SO039,emcct.SO040',
to_date('20021028020000','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.SO5','emcct.SO041,emcct.SO042,emcct.SO043,emcct.SO044,emcct.SO045,emcct.SO046,emcct.SO052,
emcct.SO054,emcct.SO062,emcct.SO063,emcct.SO064,emcct.SO065,emcct.SO066,emcct.SO067,emcct.SO069,emcct.SO074,emcct.SO075,emcct.SO077,emcct.SO079',to_date('20021028021000','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.SO6','emcct.SO081,emcct.SO082,emcct.SO083,emcct.SO084,emcct.SO085,emcct.SO086,emcct.SO087,
emcct.SO088,emcct.SO089,emcct.SO090,emcct.SO091,emcct.SO092,emcct.SO093,emcct.SO094,emcct.SO096,emcct.SO098,emcct.SO100',
to_date('20021028021500','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.SO7','emcct.SO102,emcct.SO103,emcct.SO104,emcct.SO105,emcct.SO105A,emcct.SO105B,emcct.SO105C,
emcct.SO105D,emcct.SO106,emcct.SO107,emcct.SO110,emcct.SO111,emcct.SO112,emcct.SO113,emcct.SO114,emcct.SO115,emcct.SO116,
emcct.SO117,emcct.SO126,emcct.SO127',to_date('20021028022000','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.SO8','emcct.SO200,emcct.SO201,emcct.SO301A,emcct.SO301B,emcct.SO302A,emcct.SO302B,emcct.SO303,
emcct.SO304,emcct.SO501,emcct.SO501A,emcct.SO501X,emcct.SO502,emcct.SO502X,emcct.SO503',
to_date('20021028022500','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;


execute DBMS_REFRESH.MAKE('emcct.SO9','emcct.SOAC0101,emcct.SOAC0102,emcct.SOAC0103,emcct.SOAC0201A,emcct.SOAC0201B,emcct.SOAC0201C,
emcct.SOAC0201D,emcct.SOAC0201E,emcct.SOAC0202,emcct.SOAC0203A,emcct.SOAC0203B,emcct.SOAC0204,emcct.SOPOWER',
to_date('20021028023000','YYYYMMDDHH24MISS'),'SYSDATE+1')@catvn.US.ORACLE.COM;

*/
prompt 完成時間
select to_char(sysdate,'YYYY/MM/DD HH24:MI:SS') TIME from dual@catvn.US.ORACLE.COM;

spool off


prompt 以上表示已經設定完成.

prompt 備註.
prompt 	1.若要馬上從TC抓資料到 4800,動作如下:
prompt 		CONNECT system/manager@4800	@catvn.US.ORACLE.COM;
prompt 		execute DBMS_REFRESH.REFRESH('emcct.CD1')@catvn.US.ORACLE.COM;

prompt 	2.若要殺掉此 Refresh Group
		execute DBMS_REFRESH.DESTROY('emcct.CD1')@catvn.US.ORACLE.COM;

prompt 	3.目前 refresh group emcct.CD1 擁有 10 個 member, 若要加入 mamber(ex:emcct.CD011,emcct.CD012), 則執行下列指令 :
prompt 		execute DBMS_REFRESH.ADD('emcct.CD1','emcct.CD011,emcct.CD012',true)@catvn.US.ORACLE.COM;

prompt 	4.若要移除 refresh group emcct.CD1 的 member (ex: emcct.CD011), 則執行下列指令 :
prompt        	execute DBMS_REFRESH.SUBTRACT('emcct.CD1','emcct.CD011',false)@catvn.US.ORACLE.COM;
prompt 	5.在 oracle 8i(含) 以上,若 table 中有 Long 或 Long Raw 這兩種資料型態者,無法使用此機制.




