RegSvr32 /u /s DevPower.dll
RegSvr32 /s DevPower.dll
RegSvr32 /u /s EnCrypt6.ocx
RegSvr32 /s EnCrypt6.ocx
RegSvr32 /u /s EP.dll
RegSvr32 /s EP.dll
RegSvr32 /u /s csNagraSTB3.dll
RegSvr32 /s csNagraSTB3.dll
RegSvr32 /u /s setIPPV.dll
RegSvr32 /s setIPPV.dll
RegSvr32 /u /s CS_Web.dll
RegSvr32 /s CS_Web.dll
RegSvr32 /u /s CS_MT.dll
RegSvr32 /s CS_MT.dll
RegSvr32 /u /s Crypt32DLL.dll
RegSvr32 /s Crypt32DLL.dll


