/*
  Drop EMC代碼統一化(階段一)所要調整資料檔的相關index
  By: Pierre
  Date: 2003.12.25
	2003.12.29 cd005,cd006,cd007改為第二階段轉換,故移除部份指令
	2004.01.08 cd008改為第二階段轉換,故移除部份指令
*/

Drop INDEX I_SO001_PWCode;
Drop INDEX I_SO001_OrgCode;
Drop INDEX I_SO002_MediaCode;
Drop INDEX I_SO002_DelCode;
Drop INDEX I_SO004_MediaCode;
Drop INDEX I_SO006_MediaCode;
Drop INDEX I_SO007_MediaCode;
Drop INDEX I_SO007_ReturnCode;
Drop INDEX I_SO007_SatiCode;
Drop INDEX I_SO008_MFCode1;
Drop INDEX I_SO008_MFCode2;
Drop INDEX I_SO008_ReturnCode;
Drop INDEX I_SO008_SatiCode;
Drop INDEX I_SO009_ReasonCode;
Drop INDEX I_SO009_ReturnCode;
Drop INDEX I_SO009_SatiCode;
Drop INDEX I_SO014_BTCode;
Drop INDEX I_SO016_BTCode;
Drop INDEX I_SO033_UCCode;
Drop INDEX I_SO033_A1;
Drop INDEX I_SO033_STCode;
Drop INDEX I_SO034_UCCode;
Drop INDEX I_SO034_A1;
Drop INDEX I_SO034_STCode;
Drop INDEX I_SO035_STCode;
Drop INDEX I_SO036_UCCode;
Drop INDEX I_SO036_STCode;
Drop INDEX I_SO095_BulletinCode;
Drop INDEX I_SO096_AcceptEnTimeBulletin;
Drop INDEX I_SO096_BulletinCode;
