/*
將後端所有 Trigger 啟動

Date: 2000.08.17
by: Lawrence

Edit: Lawrence by 2000.11.28
*/

alter trigger TR_SO001_InstCount1 enable;
alter trigger TR_SO001_InstCount2 enable;
alter trigger TR_SO001_InstCount3 enable;
alter trigger TR_SO001_InstCount4 enable;
alter trigger TR_SO001_InstCount5 enable;
alter trigger TR_SO001_Balance1 enable;
alter trigger TR_SO001_Balance2 enable;
alter trigger TR_SO001_Balance3 enable;
alter trigger TR_SO001_SO007SO033 enable;
alter trigger TR_SO007_SNO enable;
alter trigger TR_SO007_SO094 enable;
alter trigger TR_SO007_StrtCode enable;
alter trigger TR_SO008_SNO enable;
alter trigger TR_SO008_SO094 enable;
alter trigger TR_SO009_SNO enable;
alter trigger TR_SO009_SO094 enable;
alter trigger TR_UpdSO017 enable;
alter trigger TR_SO033_SO051 enable;
/*
alter trigger TR_UpdCD001 enable;
alter trigger TR_UpdCD002 enable;
alter trigger TR_UpdCD003 enable;
alter trigger TR_UpdCD004 enable;
alter trigger TR_UpdCD005 enable;
alter trigger TR_UpdCD006 enable;
alter trigger TR_UpdCD007 enable;
alter trigger TR_UpdCD008 enable;
alter trigger TR_UpdCD009 enable;
alter trigger TR_UpdCD010 enable;
alter trigger TR_UpdCD011 enable;
alter trigger TR_UpdCD012 enable;
alter trigger TR_UpdCD013 enable;
alter trigger TR_UpdCD014 enable;
alter trigger TR_UpdCD015 enable;
alter trigger TR_UpdCD016 enable;
alter trigger TR_UpdCD017 enable;
alter trigger TR_UpdCD018 enable;
alter trigger TR_UpdCD019 enable;
alter trigger TR_UpdCD020 enable;
alter trigger TR_UpdCD021 enable;
alter trigger TR_UpdCD022 enable;
alter trigger TR_UpdCD024 enable;
alter trigger TR_UpdCD025 enable;
alter trigger TR_UpdCD026 enable;
alter trigger TR_UpdCD031 enable;
alter trigger TR_UpdCD032 enable;
alter trigger TR_UpdCD034 enable;
alter trigger TR_UpdCD039 enable;
alter trigger TR_UpdCD040 enable;
alter trigger TR_UpdCD041 enable;
alter trigger TR_UpdCM003 enable;
*/
alter trigger TR_CD004_Description enable;
alter trigger TR_CD005_Description enable;
alter trigger TR_CD006_Description enable;
alter trigger TR_CD007_Description enable;
alter trigger TR_CD008_Description enable;
alter trigger TR_CD008A_Description enable;
alter trigger TR_CD009_Description enable;
alter trigger TR_CD010_Description enable;
alter trigger TR_CD011_Description enable;
alter trigger TR_CD011B_Description enable;
alter trigger TR_CD012_Description enable;
alter trigger TR_CD013_Description enable;
alter trigger TR_CD014_Description enable;
alter trigger TR_CD015_Description enable;
alter trigger TR_CD016_Description enable;
alter trigger TR_CD017_Description enable;
alter trigger TR_CD018_Description enable;
alter trigger TR_CD019_Description enable;
alter trigger TR_CD020_Description enable;
alter trigger TR_CD021_Description enable;
alter trigger TR_CD022_Description enable;
alter trigger TR_CD025_Description enable;
alter trigger TR_CD026_Description enable;
alter trigger TR_CD031_Description enable;
alter trigger TR_CD032_Description enable;
alter trigger TR_CD033_Description enable;
alter trigger TR_CD034_Description enable;
alter trigger TR_CD035_Description enable;
alter trigger TR_CD036_Description enable;
alter trigger TR_CD039_Description enable;
alter trigger TR_CD041_Description enable;
alter trigger TR_CD042_Description enable;
alter trigger TR_CD043_Description enable;
alter trigger TR_CD044_Description enable;
alter trigger TR_CD048_Description enable;
alter trigger TR_CD049_Description enable;
alter trigger TR_CD051_Description enable;
alter trigger TR_CD001_Description enable;
alter trigger TR_CD002_Description enable;
alter trigger TR_CD003_Description enable;
alter trigger TR_CD024_Description enable;
alter trigger TR_CD040_Description enable;
alter trigger TR_CD050_Description enable;
alter trigger TR_SO001Modify enable;