-- 以下的指令要用該 owner(ex:EMCKP) 來 run
GRANT ALTER ON "EMCKP"."SOAC0201A" TO "EMCMSS";
GRANT DELETE ON "EMCKP"."SOAC0201A" TO "EMCMSS";
GRANT INDEX ON "EMCKP"."SOAC0201A" TO "EMCMSS";
GRANT INSERT ON "EMCKP"."SOAC0201A" TO "EMCMSS";
GRANT REFERENCES ON "EMCKP"."SOAC0201A" TO "EMCMSS";
GRANT SELECT ON "EMCKP"."SOAC0201A" TO "EMCMSS";
GRANT UPDATE ON "EMCKP"."SOAC0201A" TO "EMCMSS";

GRANT ALTER ON "EMCKP"."SOAC0201B" TO "EMCMSS";
GRANT DELETE ON "EMCKP"."SOAC0201B" TO "EMCMSS";
GRANT INDEX ON "EMCKP"."SOAC0201B" TO "EMCMSS";
GRANT INSERT ON "EMCKP"."SOAC0201B" TO "EMCMSS";
GRANT REFERENCES ON "EMCKP"."SOAC0201B" TO "EMCMSS";
GRANT SELECT ON "EMCKP"."SOAC0201B" TO "EMCMSS";
GRANT UPDATE ON "EMCKP"."SOAC0201B" TO "EMCMSS";

GRANT SELECT ON "EMCKP"."CD039" TO "EMCMSS";
GRANT SELECT ON "EMCKP"."SO004" TO "EMCMSS";



