-- 以下的指令要用該 owner(ex:COM) 來 run
-- 需做適當之修改 => COM 與 EMCNTY 均有可能要修改

GRANT INSERT ON "COM"."SEND_NAGRA" TO "EMCNTY";
GRANT SELECT ON "COM"."SEND_NAGRA" TO "EMCNTY";
GRANT UPDATE ON "COM"."SEND_NAGRA" TO "EMCNTY";
GRANT DELETE ON "COM"."SEND_NAGRA" TO "EMCNTY";
GRANT SELECT  ON "COM"."S_SENDNAGRA_SEQNO" TO "EMCNTY";

-- 以下的指令要用 DBA 來 run
GRANT SELECT ANY SEQUENCE TO "EMCNTY";




