@ECHO 註冊元件(OCX,DLL)....! 請稍後.....
RegSvr32 /u /s AniGIF.ocx
RegSvr32 /s AniGIF.ocx
RegSvr32 /u /s EnCrypt6.ocx
RegSvr32 /s EnCrypt6.ocx
RegSvr32 /u /s GiAddress1.ocx
RegSvr32 /s GiAddress1.ocx
RegSvr32 /u /s GiAddress2.ocx
RegSvr32 /s GiAddress2.ocx
RegSvr32 /u /s GiAddress3.ocx
RegSvr32 /s GiAddress3.ocx
RegSvr32 /u /s GiDate.ocx
RegSvr32 /s GiDate.ocx
RegSvr32 /u /s GiGrid.ocx
RegSvr32 /s GiGrid.ocx
RegSvr32 /u /s GiGridR.ocx
RegSvr32 /s GiGridR.ocx
RegSvr32 /u /s GiList.ocx
RegSvr32 /s GiList.ocx
RegSvr32 /u /s GiLst.ocx
RegSvr32 /u /s GiMulti.ocx
RegSvr32 /s GiMulti.ocx
RegSvr32 /u /s GiNumber.ocx
RegSvr32 /s GiNumber.ocx
RegSvr32 /u /s GiTime.ocx
RegSvr32 /s GiTime.ocx
RegSvr32 /u /s GiYear.ocx
RegSvr32 /s GiYear.ocx
RegSvr32 /u /s GiYM.ocx
RegSvr32 /s GiYM.ocx
RegSvr32 /u /s OpenDBObj.DLL
RegSvr32 /s OpenDBObj.DLL
RegSvr32 /u /s PrintRpt.DLL
RegSvr32 /s PrintRpt.DLL
RegSvr32 /u /s PrintRpt2.DLL
RegSvr32 /s PrintRpt2.DLL
RegSvr32 /u /s GiCombo.ocx
RegSvr32 /s GiCombo.ocx
RegSvr32 /u /s Agency.DLL
RegSvr32 /s Agency.DLL
RegSvr32 /u /s MSBIND.DLL
RegSvr32 /s MSBIND.DLL
RegSvr32 /u /s GiAcc.DLL
RegSvr32 /s GiAcc.DLL
RegSvr32 /u /s csDMToolsCo.DLL
RegSvr32 /u /s csDMToolsSo1.DLL
RegSvr32 /u /s csDMToolsSo2.DLL
RegSvr32 /s csDMToolsSo2.DLL
RegSvr32 /u /s csDMToolsSF.DLL
RegSvr32 /s csDMToolsSF.DLL
RegSvr32 /u /s WebRptCom.dll
RegSvr32 /s WebRptCom.dll
RegSvr32 /u /s AgencyIn.dll
RegSvr32 /s AgencyIn.dll
RegSvr32 /u /s ATMIn.dll
RegSvr32 /s ATMIn.dll
RegSvr32 /u /s csAlterWip.dll
RegSvr32 /s csAlterWip.dll
RegSvr32 /u /s ASPPING.DLL
RegSvr32 /u /s PING.DLL
RegSvr32 /s PING.DLL
RegSvr32 /u /s Comdlg.dll
RegSvr32 /s Comdlg.dll
RegSvr32 /u /s csBankATMNo.dll
RegSvr32 /s csBankATMNo.dll
RegSvr32 /u /s Internet.dll
RegSvr32 /s Internet.dll
RegSvr32 /u /s ep.dll
RegSvr32 /s ep.dll
RegSvr32 /u /s csAlterCharge.dll
RegSvr32 /s csAlterCharge.dll
RegSvr32 /u /s csChargeValidate.dll
RegSvr32 /s csChargeValidate.dll
RegSvr32 /u /s csMSgrd.dll
RegSvr32 /s csMSgrd.dll
RegSvr32 /u /s csBankCenterOut.dll
RegSvr32 /s csBankCenterOut.dll
RegSvr32 /u /s csBankCenterIn.dll
RegSvr32 /s csBankCenterIn.dll
RegSvr32 /u /s MediaOut.dll
RegSvr32 /s MediaOut.dll
RegSvr32 /u /s MediaIn.dll
RegSvr32 /s MediaIn.dll
RegSvr32 /u /s cps.dll
RegSvr32 /u /s csMulti.ocx
RegSvr32 /s csMulti.ocx
RegSvr32 /u /s Export.dll
RegSvr32 /s Export.dll
RegSvr32 /u /s RxMem.dll
RegSvr32 /s RxMem.dll
RegSvr32 /u /s ExpTxt.dll
RegSvr32 /s ExpTxt.dll
RegSvr32 /u /s SetDef.dll
RegSvr32 /s SetDef.dll
RegSvr32 /u /s webreport.dll
RegSvr32 /s webreport.dll
RegSvr32 /u /s CSenc.dll
RegSvr32 /s CSenc.dll
@ECHO 註冊 V3.0 元件....! 請稍後.....
RegSvr32 /u /s Agency2.dll
RegSvr32 /s Agency2.dll
RegSvr32 /u /s AgencyIn2.dll
RegSvr32 /s AgencyIn2.dll
RegSvr32 /u /s ATMIn2.dll
RegSvr32 /s ATMIn2.dll
RegSvr32 /u /s csAlterCharge2.dll
RegSvr32 /u /s csAlterWip2.dll
RegSvr32 /u /s csBankCenter2.dll
RegSvr32 /s csBankCenter2.dll
RegSvr32 /u /s csBankCenterOut2.dll
RegSvr32 /s csBankCenterOut2.dll
RegSvr32 /u /s csBankCenterIn2.dll
RegSvr32 /s csBankCenterIn2.dll
RegSvr32 /u /s csChargeValidate2.dll
RegSvr32 /u /s MediaIn2.dll
RegSvr32 /s MediaIn2.dll
RegSvr32 /u /s MediaOut2.dll
RegSvr32 /s MediaOut2.dll
RegSvr32 /u /s CreditCardOut.dll
RegSvr32 /s CreditCardOut.dll
RegSvr32 /u /s CreditCardIN.dll
RegSvr32 /s CreditCardIN.dll
RegSvr32 /u /s CreditCardOutEMC.dll
RegSvr32 /s CreditCardOutEMC.dll
RegSvr32 /u /s csNagraSTB.dll
RegSvr32 /u /s csCallFinish.dll
RegSvr32 /u /s ESCP.dll
RegSvr32 /s ESCP.dll
RegSvr32 /u /s PHbtn.ocx
RegSvr32 /s PHbtn.ocx
RegSvr32 /u /s cs101.ocx
RegSvr32 /s cs101.ocx
RegSvr32 /u /s DevPower.dll
RegSvr32 /s DevPower.dll
RegSvr32 /u /s MSSCCB.dll
RegSvr32 /s MSSCCB.dll
@ECHO 註冊 V4.0 元件....! 請稍後.....
RegSvr32 /u /s csAlterCharge3.dll
RegSvr32 /u /s csAlterWip3.dll
RegSvr32 /u /s csChargeValidate3.dll
RegSvr32 /u /s csNagraSTB3.dll
RegSvr32 /s csNagraSTB3.dll
RegSvr32 /u /s csCallFinish3.dll
RegSvr32 /s csCallFinish3.dll
RegSvr32 /u /s Agency3.dll
RegSvr32 /s Agency3.dll
RegSvr32 /u /s AgencyIn3.dll
RegSvr32 /s AgencyIn3.dll
RegSvr32 /u /s ATMIn3.dll
RegSvr32 /s ATMIn3.dll
RegSvr32 /u /s csBankCenter3.dll
RegSvr32 /s csBankCenter3.dll
RegSvr32 /u /s csGiAcc3.dll
RegSvr32 /s csGiAcc3.dll
RegSvr32 /u /s MediaIn3.dll
RegSvr32 /s MediaIn3.dll
RegSvr32 /u /s MediaOut3.dll
RegSvr32 /s MediaOut3.dll
RegSvr32 /u /s Agency4.dll
RegSvr32 /s Agency4.dll
RegSvr32 /u /s AgencyIn4.dll
RegSvr32 /s AgencyIn4.dll
RegSvr32 /u /s ATMIn4.dll
RegSvr32 /s ATMIn4.dll
RegSvr32 /u /s csBankCenter4.dll
RegSvr32 /s csBankCenter4.dll
RegSvr32 /u /s MediaIn4.dll
RegSvr32 /s MediaIn4.dll
RegSvr32 /u /s MediaOut4.dll
RegSvr32 /s MediaOut4.dll
RegSvr32 /u /s csAlterCharge4.dll
RegSvr32 /s csAlterCharge4.dll
RegSvr32 /u /s csAlterWip4.dll
RegSvr32 /s csAlterWip4.dll
RegSvr32 /u /s csChargeValidate4.dll
RegSvr32 /s csChargeValidate4.dll
RegSvr32 /u /s CSMC.dll
RegSvr32 /s CSMC.dll
RegSvr32 /u /s CSftp.dll
RegSvr32 /s CSftp.dll
RegSvr32 /u /s csNdsSTB.dll
RegSvr32 /s csNdsSTB.dll
RegSvr32 /u /s csDAC6000.dll
RegSvr32 /s csDAC6000.dll
RegSvr32 /u /s csACHTranRefer.dll
RegSvr32 /s csACHTranRefer.dll
RegSvr32 /u /s csACHauth.dll
RegSvr32 /s csACHauth.dll
RegSvr32 /u /s csACHauth2.dll
RegSvr32 /s csACHauth2.dll
RegSvr32 /u /s csCloseTranOut.dll
RegSvr32 /s csCloseTranOut.dll
RegSvr32 /u /s csCvtXls.dll
RegSvr32 /s csCvtXls.dll
RegSvr32 /u /s DBGRID32.OCX
RegSvr32 /s DBGRID32.OCX
RegSvr32 /u /s CSexporter.dll
RegSvr32 /s CSexporter.dll
RegSvr32 /u /s WinXPctl.ocx
RegSvr32 /s WinXPctl.ocx
RegSvr32 /u /s csIPtxtbox.ocx
RegSvr32 /s csIPtxtbox.ocx
RegSvr32 /u /s setIPPV.dll
RegSvr32 /s setIPPV.dll
RegSvr32 /u /s CS_SPM.dll
RegSvr32 /s CS_SPM.dll
RegSvr32 /u /s CS_Stream.dll
RegSvr32 /s CS_Stream.dll
RegSvr32 /u /s CS_WebCmd.dll
RegSvr32 /s CS_WebCmd.dll
RegSvr32 /u /s csCMconsole.dll
RegSvr32 /s csCMconsole.dll
RegSvr32 /u /s csLogCom.dll
RegSvr32 /s csLogCom.dll
RegSvr32 /u /s Crypt32DLL.dll
RegSvr32 /s Crypt32DLL.dll
RegSvr32 /u /s csSPMconsole.dll
RegSvr32 /s csSPMconsole.dll
RegSvr32 /u /s csPaymentClass.dll
RegSvr32 /s csPaymentClass.dll
RegSvr32 /u /s csGridFieldView.dll
RegSvr32 /s csGridFieldView.dll
RegSvr32 /u /s csDVNSTB.dll
RegSvr32 /s csDVNSTB.dll
RegSvr32 /u /s csTW.dll
RegSvr32 /s csTW.dll
RegSvr32 /u /s csCMFlow.dll
RegSvr32 /s csCMFlow.dll
RegSvr32 /u /s CS_Rpt2Pdf.dll
RegSvr32 /s CS_Rpt2Pdf.dll
RegSvr32 /u /s csAlterSO003.dll
RegSvr32 /s csAlterSO003.dll
RegSvr32 /u /s csSCMcontrol.dll
RegSvr32 /s csSCMcontrol.dll
RegSvr32 /u /s csPrintChargeBill.dll
RegSvr32 /s csPrintChargeBill.dll
RegSvr32 /u /s CS_IVR_SMS.dll
RegSvr32 /s CS_IVR_SMS.dll
@ECHO OFF
@REM ===============================================================================================

REM JetXls.hta

@REM ===============================================================================================

if exist C:\CSMISV30\BIN goto PassBin
    set BinPath=C:\GICMIS\BIN
    goto EndofBin

:PassBin
    set BinPath=C:\CSMISV30\BIN
    goto EndofBin

:EndofBin

@REM ===============================================================================================

if exist C:\GIRD\COMMON goto PassCommon
if exist C:\GICMIS\COMMON goto PassCommon2
if exist C:\CSMISV30\COMMON goto PassCommon3
goto ByPass
 
:PassCommon
    set CommonPath=C:\GIRD\COMMON
    goto EndofCommon

:PassCommon2
    set CommonPath=C:\GICMIS\COMMON
    goto EndofCommon

:PassCommon3
    set CommonPath=C:\CSMISV30\COMMON
    goto EndofCommon

:EndofCommon

:ByPass

@REM ===============================================================================================

if "%OS%" == "Windows_NT" goto WinNTserial

:Win98serial
    set SystemPath=%WINDIR%\SYSTEM
    set HostsPath=%WINDIR%
    goto EndofOS

:WinNTserial
    set SystemPath=%WINDIR%\SYSTEM32
    set HostsPath=%WINDIR%\system32\drivers\etc
    goto EndofOS

:EndofOS

@REM ===============================================================================================

@REM %BinPath%
@REM %CommonPath%
@REM %SystemPath%
@REM %HostsPath%

@ECHO ON
@ECHO.
@ECHO 註冊 ActiveX EXE / OCX ! 請稍後.....
@ECHO.
@REM === ActiveX EXE / OCX register ================================================================

@IF NOT EXIST %SystemPath%\MSDATREP.ocx  RegSvr32 /s MSDATREP.ocx

@IF EXIST %BinPath%\Emc_Separate.exe  %BinPath%\Emc_Separate.exe /REGSERVER

@IF EXIST %BinPath%\GB.exe  %BinPath%\GB.exe /REGSERVER


@ECHO.
@ECHO Copy Win32 Dll ! 請稍後.....
@ECHO.
@REM === Copy Win32 Dll ============================================================================

@IF NOT EXIST %WINDIR%\KBHOOK.DLL         COPY %CommonPath%\KBHOOK.DLL       %WINDIR%    /Y /V
@IF NOT EXIST %WINDIR%\DataAddr.dll       COPY %CommonPath%\DataAddr.dll     %WINDIR%    /Y /V
@IF NOT EXIST %WINDIR%\KBHOOK.DLL         COPY %CommonPath%\KBHOOK.DLL       %WINDIR%    /Y /V
@IF NOT EXIST %WINDIR%\DataAddr.dll       COPY %CommonPath%\DataAddr.dll     %WINDIR%    /Y /V

@ECHO.
@ECHO Copy Visual FoxPro Runtime library ! 請稍後.....
@ECHO.
@REM === Copy Visual FoxPro Runtime library ========================================================

@IF NOT EXIST %SystemPath%\vfp6run.exe    COPY %CommonPath%\vfp6run.exe      %SystemPath%  /Y /V
@IF NOT EXIST %SystemPath%\vfp6r.dll      COPY %CommonPath%\vfp6r.dll        %SystemPath%  /Y /V
@IF NOT EXIST %SystemPath%\vfp6rcht.dll   COPY %CommonPath%\vfp6rcht.dll     %SystemPath%  /Y /V
@IF NOT EXIST %SystemPath%\vfp6renu.dll   COPY %CommonPath%\vfp6renu.dll     %SystemPath%  /Y /V


@ECHO.
@ECHO Copy Hosts ! 請稍後.....
@ECHO.
@REM === Copy Hosts ================================================================================

@IF EXIST %CommonPath%\hosts   COPY %CommonPath%\hosts   %HostsPath%  /Y /V


@ECHO.
@ECHO Copy PureMDB ! 請稍後.....
@ECHO.
@REM === Copy PureMDB ==============================================================================

@IF EXIST P: goto CopyPureMDBfromPtoC
@goto ByPassPtoC

:CopyPureMDBfromPtoC

@IF EXIST P:\GICMIS\PureMdb     Copy P:\GICMIS\PureMdb\*.*     c:\GICMIS\PureMdb     /Y /V
@ECHO.
@IF EXIST P:\CSMISV30\PureMdb   Copy P:\CSMISV30\PureMdb\*.*   c:\CSMISV30\PureMdb   /Y /V
@ECHO.

:ByPassPtoC

@IF EXIST C:\GICMIS\PureMdb     Copy C:\GICMIS\PureMdb\*.*     c:\tmpmdb             /Y /V
@ECHO.
@IF EXIST C:\CSMISV30\PureMdb   Copy C:\CSMISV30\PureMdb\*.*   c:\TmpMDBv30          /Y /V
@ECHO.

@ECHO.
@ECHO 註冊 MSSCCB ! 請稍後.....
@ECHO.
@REM === Register MSSCCB ===========================================================================

@IF EXIST %CommonPath%\MSSCCB* goto RegMSSCCB
@goto Done

@REM mssccb98.exe
@REM mssccb2000.exe

:RegMSSCCB
    @REM if "%OS%" == "Windows_NT" %CommonPath%\mssccb2000.exe
    @REM if "%OS%" == "" %CommonPath%\mssccb98.exe
    @DEL MSSCCB*.EXE
    @rundll32 advpack.dll,LaunchINFSection MssCcb.inf,RemoveClientSide,3
    @goto Done

@ECHO.
@REM === Copy MakeCAB & Expand  ===========================================================================

@if "%OS%" == "" goto CopyCabExp
@goto Done

:CopyCabExp
COPY %CommonPath%\makecab.exe   %WINDIR%\command\makecab.exe  /Y /V
COPY %CommonPath%\expand.exe   %WINDIR%\command\expand.exe  /Y /V
@goto Done

:Done
@ECHO.


@REM === Complete !! === ===========================================================================
@ECHO.
@ECHO 系統元件註冊完成.....
@ECHO.


@ECHO ON



