PROMPT *** So110   拆帳作業之拆帳公式代碼檔 ***

DROP TABLE So110 CASCADE CONSTRAINT;

CREATE TABLE So110 (
	FORMULA_ID	VARCHAR2(4),
	FORMULA_NAME	VARCHAR2(50),
	FORMULA_DESC	VARCHAR2(100),
	REF_NO          CHAR(1),
	STOPFLAG	NUMBER(1),
	OPERATOR	VARCHAR2(20),
	UPDTIME		VARCHAR2(20),
	CONSTRAINT PK_So110 PRIMARY KEY (FORMULA_ID)
       );
