PROMPT *** So111   拆帳作業之各產品拆帳公式資料檔 ***

DROP TABLE So111 CASCADE CONSTRAINT;

CREATE TABLE So111 (
	PRODUCT_ID			VARCHAR2(4),
	PRODUCT_NAME			VARCHAR2(30),
	FORMULA_ID			VARCHAR2(4),
	COMP_TYPE			CHAR(1),
	SO_PROVIDER_ID			VARCHAR2(10),
	SO_PROVIDER_Desc		VARCHAR2(50),
	COMPUTE_ISSUE			NUMBER(1),
	RANGE_UNIT			CHAR(1),
	SUBSCRIBER_COUNT_PERCENT1	NUMBER(8,2),
	SUBSCRIBER_COUNT_PERCENT2	NUMBER(8,2),
	SUBSCRIBER_COUNT_PERCENT3	NUMBER(8,2),
	SUBSCRIBER_COUNT_PERCENT4	NUMBER(8,2),
	SUBSCRIBER_COUNT_PERCENT5	NUMBER(8,2),
	AMOUNT_PERCENT1			NUMBER(10,2),
	AMOUNT_PERCENT2			NUMBER(10,2),
	AMOUNT_PERCENT3			NUMBER(10,2),
	AMOUNT_PERCENT4			NUMBER(10,2),
	AMOUNT_PERCENT5			NUMBER(10,2),
	OPERATOR			VARCHAR2(20),
	UPDTIME				VARCHAR2(20),
	CONSTRAINT PK_So111 PRIMARY KEY (PRODUCT_ID,FORMULA_ID,COMP_TYPE,SO_PROVIDER_ID)
       );
