PROMPT *** So113   拆帳作業之頻道商代碼檔 ***

DROP TABLE So113 CASCADE CONSTRAINT;

CREATE TABLE So113 (
	PROVIDER_ID		VARCHAR2(10),
	PROVIDER_NAME		VARCHAR2(50),
	ATTRIBUTE		Number(1),
	CONTACTEE		VARCHAR2(20),
	TEL			VARCHAR2(20),
	ADDRESS			VARCHAR2(80),
	NOTES			VARCHAR2(100),
	STOPFLAG		NUMBER(1),
	OPERATOR		VARCHAR2(20),
	UPDTIME			VARCHAR2(20),
	CONSTRAINT PK_So113 PRIMARY KEY (PROVIDER_ID)
       );
