PROMPT *** So112A   版權成本分攤之分攤百分比資料檔 ***

DROP TABLE So112A CASCADE CONSTRAINT;

CREATE TABLE So112A (
	CODENO                  NUMBER(3),
	DESCRIPTION             VARCHAR2(20),
	Percent			Number,
	OPERATOR		VARCHAR2(20),
	UPDTIME			VARCHAR2(20),
	CONSTRAINT PK_So112A PRIMARY KEY (CODENO)
       );
