--祇布CUSTSNAME<>SO002A.CHARGETITLE or custsname<>so002.contname
SELECT '祇布CUSTSNAME<>眀めΜン(Τ眀腹)' 猵,A.CUSTID "絪",A.CUSTNAME "狝-﹎",
B.CHARGETITLE "狝--眀めΜン",c.bankname "蝗︽",c.accountno "眀腹",
B.INVTITLE "狝--祇布╋繷",B.INVNO "狝--参絪",C.BILLNO "Μ禣虫腹",D.INVID "祇布腹",
D.CUSTSNAME "祇布-め﹎",D.INVTITLE "秨祇布╋繷",D.BUSINESSID "祇布-参絪",c.realdate,d.invdate
FROM SO001 A,SO002A B,SO034 C,INV007 D
WHERE A.CUSTID=B.CUSTID AND A.CUSTID=C.CUSTID AND C.GUINO=D.INVID
  AND C.SERVICETYPE IN ('I','D')  AND C.ACCOUNTNO IS NOT NULL
  AND B.BANKCODE=C.BANKCODE  AND B.ACCOUNTNO=C.ACCOUNTNO
  AND REALDATE>=TO_DATE('20040420','YYYYMMDD') AND B.CHARGETITLE<>D.CUSTSNAME   
unioN all 
SELECT '祇布CUSTSNAME<>狝叭羛蹈(礚眀腹)' 猵,A.CUSTID "絪",A.CUSTNAME "狝-﹎",
B.CONTNAME "狝--眀めΜン",c.bankname "蝗︽",c.accountno "眀腹",
B.INVTITLE "狝--祇布╋繷",B.INVNO "狝--参絪",C.BILLNO "Μ禣虫腹",D.INVID "祇布腹",
D.CUSTSNAME"祇布-め﹎",D.INVTITLE "秨祇布╋繷",D.BUSINESSID "祇布-参絪",c.realdate,d.invdate
FROM SO001 A,SO002 B,SO034 C,INV007 D
WHERE A.CUSTID=B.CUSTID AND A.CUSTID=C.CUSTID AND C.GUINO=D.INVID
  AND C.SERVICETYPE IN ('I','D') AND B.SERVICETYPE=C.SERVICETYPE 
  AND C.ACCOUNTNO IS  NULL
  AND REALDATE>=TO_DATE('20040420','YYYYMMDD') AND A.CUSTNAME<>D.CUSTSNAME





--LSC ....莱羛秨羛
SELECT 'LSC--莱羛秨羛(Τ眀腹)' "猵",CUSTID "狝絪",TITLECUST,
INVID "祇布腹絏",BILLNO "Μ禣虫腹",Realdate,
INVCUSTID "祇布絪",CUSTSNAME "祇布﹎",TITLEINV,
INVNO "狝参絪",BUSINESSID "祇布参絪" FROM 
(select a.custid,A.CHARGETITLE chargetitle,
A.INVTITLE TITLECUST,b.realdate,
C.CUSTSNAME,C.INVTITLE TITLEINV,
a.accountno,a.invno,C.BUSINESSID,a.invoicetype,
B.BILLNO,B.GUINO,B.INVDATE,B.REALAMT,C.INVID,C.CUSTID INVCUSTID,C.INVAMOUNT
 from so002a a,so034 b, INV007 C 
 where  b.servicetype in ('I','D')  AND A.CUSTID=B.CUSTID 
 AND B.accountno IS NOT NULL  AND B.BANKCODE=A.BANKCODE AND A.ACCOUNTNO=B.ACCOUNTNO
 AND C.INVID=B.GUINO AND C.BUSINESSID IS NULL AND A.INVNO IS NOT NULL
 AND B.REALDATE>=TO_DATE('20040420','YYYYMMDD'))
UNION ALL
SELECT 'LSC--莱羛秨羛(礚眀腹)' "猵",CUSTID "狝絪",TITLECUST,
INVID "祇布腹絏",BILLNO "Μ禣虫腹",Realdate,
INVCUSTID "祇布絪",CUSTSNAME "祇布﹎",TITLEINV,
INVNO "狝参絪",BUSINESSID "祇布参絪" FROM 
(select a.custid,A.CONTNAME chargetitle,A.INVTITLE TITLECUST,
C.CUSTSNAME,C.INVTITLE TITLEINV,b.realdate,
a.accountno,a.invno,C.BUSINESSID,a.invoicetype,
B.BILLNO,B.GUINO,B.INVDATE,B.REALAMT,C.INVID,C.CUSTID INVCUSTID,C.INVAMOUNT
 from so002 a,so034 b, INV007 C,so001 d
 where  b.servicetype in ('I','D') and a.servicetype=b.servicetype and a.custid=d.custid 
 AND A.CUSTID=B.CUSTID 
 AND B.accountno IS NULL
 AND C.INVID=B.GUINO AND C.BUSINESSID IS NULL AND A.INVNO IS NOT NULL
 AND B.REALDATE>=TO_DATE('20040420','YYYYMMDD'))


 



/* め秨ミ祇布 */

SELECT 'め秨ミ祇布' 猵,
A.CUSTID 狝絪,A.GUINO 祇布腹絏,A.BILLNO Μ禣虫腹,A.ITEM 兜Ω,
A.CITEMCODE Μ禣絏,A.CITEMNAME Μ禣兜ヘ,B.CUSTID 祇布絪,
A.REALDATE,A.MEDIABILLNO,A.ACCOUNTNO,A.invoicetime ,C.INVTITLE "002TITLE",B.INVTITLE  "007TITLE"
FROM SO034 A,INV007 B, so002 c
WHERE A.REALDATE>=TO_DATE('20040420','YYYYMMDD') AND A.GUINO IN (
SELECT GUINO FROM (
SELECT GUINO,CUSTID,BILLNO FROM SO034 
WHERE REALDATE>=TO_DATE('20040420','YYYYMMDD')
GROUP BY GUINO,CUSTID,BILLNO 
) QQ GROUP BY GUINO HAVING COUNT(*) > 1) AND A.GUINO=B.INVID 
AND A.CUSTID<>to_number(B.custid) 
and a.custid=c.custid and a.servicetype='C' AND C.SERVICETYPE='C'
ORDER BY A.GUINO

  





/* 祇布╋繷ぃ┪参絪Τ粇 */ 
SELECT '礚眀め--祇布╋繷ぃ' 猵,A.CUSTID,B.CUSTNAME,C.BILLNO,C.GUINO,C.REALDATE,
A.INVTITLE,D.INVTITLE INVNAME,A.INVNO,D.BUSINESSID
FROM SO002 A,SO001 B,SO034 C,INV007 D
WHERE A.CUSTID=B.CUSTID AND A.CUSTID=C.CUSTID
  AND A.SERVICETYPE=C.SERVICETYPE AND A.SERVICETYPE IN ('I','D')
  AND C.GUINO=D.INVID AND C.ACCOUNTNO IS NULL 
  AND C.REALDATE>=TO_DATE('20040420','YYYYMMDD')
  AND A.INVOICETYPE=3 AND A.INVTITLE<>D.INVTITLE
UNION ALL
SELECT '礚眀め--参絪Τ粇' 猵,A.CUSTID,B.CUSTNAME,C.BILLNO,C.GUINO,C.REALDATE,
A.INVTITLE,D.INVTITLE INVNAME,A.INVNO,D.BUSINESSID
FROM SO002 A,SO001 B,SO034 C,INV007 D
WHERE A.CUSTID=B.CUSTID AND A.CUSTID=C.CUSTID
  AND A.SERVICETYPE=C.SERVICETYPE AND A.SERVICETYPE IN ('I','D')
  AND C.GUINO=D.INVID AND C.ACCOUNTNO IS NULL 
  AND C.REALDATE>=TO_DATE('20040420','YYYYMMDD')
  AND A.INVOICETYPE=3 AND A.INVNO<>D.BUSINESSID 
UNION ALL 
SELECT 'Τ眀め--祇布╋繷ぃ' 猵,A.CUSTID,B.CUSTNAME,C.BILLNO,C.GUINO,C.REALDATE,
A.INVTITLE,D.INVTITLE INVNAME,A.INVNO,D.BUSINESSID
FROM SO002A A,SO001 B,SO034 C,INV007 D
WHERE A.CUSTID=B.CUSTID AND A.CUSTID=C.CUSTID  
  AND C.SERVICETYPE IN ('I','D') AND A.BANKCODE IS NOT NULL 
  AND A.BANKCODE=C.BANKCODE AND A.ACCOUNTNO=C.ACCOUNTNO 
  AND C.GUINO=D.INVID 
  AND C.REALDATE>=TO_DATE('20040420','YYYYMMDD')
  AND A.INVOICETYPE=3 AND A.INVTITLE<>D.INVTITLE
UNION ALL
SELECT 'Τ眀め--参絪Τ粇' 猵,A.CUSTID,B.CUSTNAME,C.BILLNO,C.GUINO,C.REALDATE,
A.INVTITLE,D.INVTITLE INVNAME,A.INVNO,D.BUSINESSID
FROM SO002A A,SO001 B,SO034 C,INV007 D
WHERE A.CUSTID=B.CUSTID AND A.CUSTID=C.CUSTID  
  AND C.SERVICETYPE IN ('I','D') AND A.BANKCODE IS NOT NULL 
  AND A.BANKCODE=C.BANKCODE AND A.ACCOUNTNO=C.ACCOUNTNO 
  AND C.GUINO=D.INVID 
  AND C.REALDATE>=TO_DATE('20040420','YYYYMMDD')
  AND A.INVOICETYPE=3 AND  A.INVNO<>D.BUSINESSID

