spool c:\temp\CreateMv.log

prompt 起始時間
select to_char(sysdate,'YYYY/MM/DD HH24:MI:SS') TIME from dual;


prompt 前置動作
prompt 	1.要將tc的 data 放到北平台來
prompt 	2.在我的電腦中,設定好Net 8, 分別使用 alias "tc" 連接到tc,alias "4800" 連接到北平台
prompt 	  而北平台主機上也已經設定好用 alias "tc" 連接到tc.
prompt 	3.在北平台上建立了兩個 tablespace : MV 和 SNAP_NDX, 希望將TC的data以及 index分別放在這兩個 tablespace中
prompt 	4.在北平台上建立一個 tablespace:MV_TMP, 用來做排序用
prompt 	5.在北平台上建立user:EMCYMS, 使其 default tablespace 是MV, default temporary tablespace 是MV_TMP
prompt 	  並賦予EMCYMS適度的權限,指令如下: (特別留意最後一行 grant 指令)
prompt 		GRANT "CONNECT" TO "EMCYMS";
prompt 		GRANT "DBA" TO "EMCYMS";
prompt 		GRANT "RESOURCE" TO "EMCYMS";
prompt 		GRANT UNLIMITED TABLESPACE TO "EMCYMS";
prompt 		ALTER USER "EMCYMS" DEFAULT ROLE ALL;
prompt 		grant create table to "EMCYMS";
prompt 		grant create view to "EMCYMS";
prompt 		grant create sequence to "EMCYMS";
prompt 		grant query rewrite to "EMCYMS";

prompt   注意: 請將 EMCYMS 修改成適當的 owner
prompt   注意: 請修改 system 的密碼以及連線的 alias
prompt   注意: 請修改 EMCYMS 的密碼以及連線的 alias
prompt   注意: 請修改 DbLink 的內容
prompt   注意: 請修改  SNAP_NDX 為正確的 Index tablespace name
prompt   注意: DBMS_REFRESH.MAKE 中 2002102501300 => 表示 2002/10/25 01:30:00 將第一次執行此job. => 將此修改成想要的日期
prompt   注意:                          SYSDATE+1 => 表示以後每一天執行一次此job. => 將此修改成想要的天數



CONNECT EMCYMS/EMCYMS@4800


prompt 為何用 CATVN ? 請連接到 tc, 然後執行 SQL>select * from global_name; 
prompt 若要更改 global name, 指令如下: SQL> alter database rename global_name to new_global_name;
CREATE DATABASE LINK CATVN CONNECT TO EMCYMS  IDENTIFIED BY EMCYMS USING 'tc';

PS:若要建立 public database link, 則指令如下
CREATE PUBLIC DATABASE LINK "CATVN"  CONNECT TO  "EMCYMS" IDENTIFIED BY "EMCYMS"  USING 'tc' ;


CONNECT system/manager@4800;


prompt CD001 ~ CD010


CREATE MATERIALIZED VIEW EMCYMS.CD000   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD000@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD001   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD001@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD001A   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD001A@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD002   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD002@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD002CM003   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD002CM003@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.CD003   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD003@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD004   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD004@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD005   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD005@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD006   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD006@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD006A   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD006A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD006B   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD006B@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD007   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD007@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD008   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD008@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD008A   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD008A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD008B   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD008B@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD008C   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD008C@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD009   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD009@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD010   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD010@CATVN;








prompt CD011 ~ Cd020

CREATE MATERIALIZED VIEW EMCYMS.CD011   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD011@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD011A   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD011A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD011B   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD011B@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD012   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD012@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.CD013   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD013@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD014   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD014@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD015   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD015@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD016   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD016@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.CD017   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD017@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD018   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD018@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD019   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD019@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD019A   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD019A@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD019CD004  USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD019CD004@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD019SO017  USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD019SO017@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD020   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD020@CATVN;




prompt CD021 ~ Cd030

CREATE MATERIALIZED VIEW EMCYMS.CD021   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD021@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD022   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD022@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD022CD019  USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD022CD019@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD023   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD023@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD024   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD024@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD025   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD025@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD026   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD026@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.CD027   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD027@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD027A   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD027A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD027B   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD027B@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD027C   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD027C@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD027D   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD027D@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.CD028   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD028@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD029   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD029@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD030   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD030@CATVN;




prompt CD031 ~ Cd040

CREATE MATERIALIZED VIEW EMCYMS.CD031   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD031@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD031A   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD031A@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD032   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD032@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD033   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD033@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD034   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD034@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD035   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD035@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD036   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD036@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.CD037   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD037@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD039   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD039@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD040   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD040@CATVN;





prompt CD041 ~ Cd050

CREATE MATERIALIZED VIEW EMCYMS.CD041   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD041@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD042   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD042@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD043   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD043@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD044   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD044@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD045   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD045@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD046   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD046@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.CD047   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD047@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD048   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD048@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.CD048A USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD048A@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD049   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD049@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD050   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD050@CATVN;




prompt Cd051 以後

CREATE MATERIALIZED VIEW EMCYMS.CD051   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD051@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD052   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD052@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD053   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD053@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD054   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD054@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD055   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD055@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD056   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD056@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.CD057   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD057@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD058   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD058@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.CD059   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD059@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD060   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD060@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD061   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD061@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD062   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD062@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CD063   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD063@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.CM001   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CM001@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CM002   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CM002@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CM003   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CM003@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CM004   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CM004@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.CM005   USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CM005@CATVN;


prompt SO001~SO010

CREATE MATERIALIZED VIEW EMCYMS.SO001 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO001@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO002 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO002@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO002A USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO002A@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO003 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO003@CATVN;




CREATE MATERIALIZED VIEW EMCYMS.SO004 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO004@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO005 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO005@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO006 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO006@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SO007 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO007@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO008 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO008@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO009 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO009@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO010 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO010@CATVN;





prompt SO011~SO020

CREATE MATERIALIZED VIEW EMCYMS.SO011 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO011@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO012 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO012@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO013 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO013@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO014 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO014@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO015 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO015@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO016 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO016@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO017 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO017@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO017A USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO017A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO018 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO018@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SO019 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO019@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO020 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO020@CATVN;





prompt SO021~SO030

CREATE MATERIALIZED VIEW EMCYMS.SO021 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO021@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO022 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO022@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO023 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO023@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO024 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO024@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO025 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND FOR UPDATE ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO025@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO026 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO026@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO027 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO027@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO028 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO028@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO029 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO029@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO029A USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO029A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO030 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO030@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO030A USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO030A@CATVN;



prompt SO031~SO040

CREATE MATERIALIZED VIEW EMCYMS.SO031 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO031@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO032 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO032@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO032BREAK USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO032BREAK@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO033 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO033@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO034 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO034@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO035 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO035@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO036 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO036@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO037 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO037@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SO038 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO038@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SO039 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO039@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO040 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO040@CATVN;




prompt SO041~SO080

CREATE MATERIALIZED VIEW EMCYMS.SO041 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO041@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO042 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO042@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO043 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO043@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO044 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO044@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO045 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO045@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO046 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO046@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO052 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO052@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO054 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND FOR UPDATE ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO054@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO062 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO062@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO063 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO063@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO064 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO064@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO065 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO065@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO066 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO066@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO067 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO067@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO069 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO069@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SO071 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO071@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO072 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO072@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO073 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO073@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SO074 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO074@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO075 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO075@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO077 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO077@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO079 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO079@CATVN;



prompt SO081~SO100

CREATE MATERIALIZED VIEW EMCYMS.SO081 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO081@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO082 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO082@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO083 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO083@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO084 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO084@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO085 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO085@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO086 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO086@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO087 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO087@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO088 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO088@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO089 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO089@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO090 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO090@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO091 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO091@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO092 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO092@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO093 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO093@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO094 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO094@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO095 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO095@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SO096 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO096@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO097 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO097@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO098 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO098@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO099 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO099@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO100 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO100@CATVN;




prompt SO101~SO130

CREATE MATERIALIZED VIEW EMCYMS.SO102 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO102@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO103 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO103@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO104 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO104@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO105 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO105@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO105A USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO105A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO105B USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO105B@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO105C USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO105C@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO105D USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO105D@CATVN;



CREATE MATERIALIZED VIEW EMCYMS.SO106 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO106@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO107 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO107@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO108 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO108@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO110 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO110@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO111 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO111@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO112 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO112@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO113 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO113@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO114 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO114@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO115 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO115@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO116 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO116@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO117 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO117@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO118 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO118@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO119 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO119@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO123 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO123@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO124 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO124@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO126 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO126@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO127 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO127@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SO128 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO128@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO131 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO131@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO132 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO132@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO133 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO133@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO134 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO134@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO135 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO135@CATVN;





prompt SO200~SO600

CREATE MATERIALIZED VIEW EMCYMS.SO200 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO200@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO201 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO201@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SO301A USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO301A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO301B USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO301B@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO302A USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO302A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO302B USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO302B@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SO303 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO303@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO304 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO304@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO501 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO501@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO501A USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO501A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO501X USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO501X@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO502 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO502@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO502X USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO502X@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO503 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO503@CATVN;



prompt others

CREATE MATERIALIZED VIEW EMCYMS.SOAC0101 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0101@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SOAC0102 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0102@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SOAC0103 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0103@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SOAC0201A USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0201A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SOAC0201B USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH FAST ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0201B@CATVN;

CREATE MATERIALIZED VIEW EMCYMS.SO504 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO504@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SO508 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SO508@CATVN;


CREATE MATERIALIZED VIEW EMCYMS.SOAC0201C USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0201C@CATVN;



CREATE MATERIALIZED VIEW EMCYMS.SOAC0201D USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0201D@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SOAC0201E USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0201E@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SOAC0202 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0202@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SOAC0203A USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0203A@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SOAC0203B USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0203B@CATVN;
CREATE MATERIALIZED VIEW EMCYMS.SOAC0204 USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOAC0204@CATVN;



CREATE MATERIALIZED VIEW EMCYMS.SOPOWER USING INDEX TABLESPACE "SNAP_NDX" 
			REFRESH WITH ROWID ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.SOPOWER@CATVN;



prompt 注意: 若 4800 中該 table 已經存在, 則正確之指令如下:
prompt 注意: CREATE MATERIALIZED VIEW EMCYMS.CD010  ON PREBUILT TABLE USING INDEX TABLESPACE "SNAP_NDX" REFRESH FAST 
prompt 注意: 		ON DEMAND ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD010@CATVN;
prompt 注意: 若要取消此項設定,範例指令如下:SQL>DROP MATERIALIZED VIEW EMCYMS.CD008;
prompt 注意: 此指令執行完成後, data 也就抓取過來了	

prompt 注意: 若該 view 需要被 update, 則正確之指令如下:
prompt 注意: CREATE MATERIALIZED VIEW EMCYMS.CD010  ON PREBUILT TABLE USING INDEX TABLESPACE "SNAP_NDX" REFRESH FAST 
prompt 注意: 		ON DEMAND FOR UPDATE ENABLE QUERY REWRITE AS SELECT * FROM  EMCYMS.CD010@CATVN;


CONNECT system/manager@4800;

execute DBMS_REFRESH.MAKE('EMCYMS.CD1','EMCYMS.CD000,EMCYMS.CD001,EMCYMS.CD001A,EMCYMS.CD002,EMCYMS.CD002CM003,EMCYMS.CD003,EMCYMS.CD004,EMCYMS.CD005,EMCYMS.CD006,EMCYMS.CD006A,EMCYMS.CD006B,EMCYMS.CD007,EMCYMS.CD008,EMCYMS.CD008A,EMCYMS.CD008B, EMCYMS.CD008C,EMCYMS.CD009,EMCYMS.CD010',to_date('20030618050000','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.CD2','EMCYMS.CD011,EMCYMS.CD011A,EMCYMS.CD012,EMCYMS.CD013,EMCYMS.CD014,EMCYMS.CD015,EMCYMS.CD016,EMCYMS.CD017,EMCYMS.CD018, EMCYMS.CD019,EMCYMS.CD019A,EMCYMS.CD019CD004,EMCYMS.CD019SO017,EMCYMS.CD020',to_date('20030618050500','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.CD3','EMCYMS.CD021,EMCYMS.CD022,EMCYMS.CD022CD019,EMCYMS.CD023,EMCYMS.CD024,EMCYMS.CD025,EMCYMS.CD026,EMCYMS.CD027,EMCYMS.CD027A, EMCYMS.CD027B, EMCYMS.CD027C, EMCYMS.CD027D,EMCYMS.CD028, EMCYMS.CD029,EMCYMS.CD030',to_date('20030618051000','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.CD4','EMCYMS.CD031,EMCYMS.CD032,EMCYMS.CD033,EMCYMS.CD034,EMCYMS.CD035,EMCYMS.CD036,EMCYMS.CD037,EMCYMS.CD039,EMCYMS.CD040',to_date('20030618051500','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.CD5','EMCYMS.CD041,EMCYMS.CD042,EMCYMS.CD043,EMCYMS.CD044,EMCYMS.CD045,EMCYMS.CD046,EMCYMS.CD047,EMCYMS.CD048,EMCYMS.CD048A,EMCYMS.CD049,EMCYMS.CD050',to_date('20030618052000','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.CD6','EMCYMS.CD051,EMCYMS.CD053,EMCYMS.CD054,EMCYMS.CD055,EMCYMS.CD056,EMCYMS.CD057,EMCYMS.CD058,EMCYMS.CD059,EMCYMS.CD060,EMCYMS.CD061,EMCYMS.CD062,EMCYMS.CD063,EMCYMS.CM001,EMCYMS.CM002,EMCYMS.CM003,EMCYMS.CM004,EMCYMS.CM005',to_date('20030618052500','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.SO1','EMCYMS.SO001,EMCYMS.SO002,EMCYMS.SO002A,EMCYMS.SO003,EMCYMS.SO004,EMCYMS.SO005,EMCYMS.SO006,EMCYMS.SO007,EMCYMS.SO008,EMCYMS.SO009,EMCYMS.SO010',to_date('20030618053000','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.SO2','EMCYMS.SO011,EMCYMS.SO012,EMCYMS.SO013,EMCYMS.SO014,EMCYMS.SO015,EMCYMS.SO016,EMCYMS.SO017A,EMCYMS.SO019,EMCYMS.SO020',to_date('20030618053500','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.SO3','EMCYMS.SO021,EMCYMS.SO022,EMCYMS.SO023,EMCYMS.SO024,EMCYMS.SO025,EMCYMS.SO026,EMCYMS.SO027,EMCYMS.SO028,EMCYMS.SO029,EMCYMS.SO029A,EMCYMS.SO030,EMCYMS.SO030A',to_date('20030618054000','YYYYMMDDHH24MISS'),'SYSDATE+1');



execute DBMS_REFRESH.MAKE('EMCYMS.SO4','EMCYMS.SO031,EMCYMS.SO032,EMCYMS.SO032BREAK,EMCYMS.SO033,EMCYMS.SO034,EMCYMS.SO035,EMCYMS.SO036,EMCYMS.SO037,EMCYMS.SO039,EMCYMS.SO040',to_date('20030618054500','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.SO5','EMCYMS.SO041,EMCYMS.SO042,EMCYMS.SO043,EMCYMS.SO044,EMCYMS.SO045,EMCYMS.SO046,EMCYMS.SO052,EMCYMS.SO054,EMCYMS.SO062,EMCYMS.SO063,EMCYMS.SO064,EMCYMS.SO065,EMCYMS.SO066,EMCYMS.SO067,EMCYMS.SO069,EMCYMS.SO074,EMCYMS.SO075,EMCYMS.SO077,EMCYMS.SO079',to_date('20030618055000','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.SO6','EMCYMS.SO081,EMCYMS.SO082,EMCYMS.SO083,EMCYMS.SO084,EMCYMS.SO085,EMCYMS.SO086,EMCYMS.SO087,EMCYMS.SO088,EMCYMS.SO089,EMCYMS.SO090,EMCYMS.SO091,EMCYMS.SO092,EMCYMS.SO093,EMCYMS.SO094,EMCYMS.SO096,EMCYMS.SO098,EMCYMS.SO100',to_date('20021028055500','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.SO7','EMCYMS.SO102,EMCYMS.SO103,EMCYMS.SO104,EMCYMS.SO105,EMCYMS.SO105A,EMCYMS.SO105B,EMCYMS.SO105C,EMCYMS.SO105D,EMCYMS.SO106,EMCYMS.SO107,EMCYMS.SO108,EMCYMS.SO110,EMCYMS.SO111,EMCYMS.SO112,EMCYMS.SO113,EMCYMS.SO114,EMCYMS.SO115,EMCYMS.SO116,EMCYMS.SO117,EMCYMS.SO118,EMCYMS.SO119,EMCYMS.SO126,EMCYMS.SO123,EMCYMS.SO124,EMCYMS.SO127,EMCYMS.SO128,EMCYMS.SO131,EMCYMS.SO132,EMCYMS.SO133,EMCYMS.SO134,EMCYMS.SO135',to_date('20030618055700','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.SO8','EMCYMS.SO200,EMCYMS.SO201,EMCYMS.SO301A,EMCYMS.SO301B,EMCYMS.SO302A,EMCYMS.SO302B,EMCYMS.SO303,EMCYMS.SO304,EMCYMS.SO501,EMCYMS.SO501A,EMCYMS.SO501X,EMCYMS.SO502,EMCYMS.SO502X,EMCYMS.SO503',to_date('20030618055800','YYYYMMDDHH24MISS'),'SYSDATE+1');


execute DBMS_REFRESH.MAKE('EMCYMS.SO9','EMCYMS.SOAC0101,EMCYMS.SOAC0102,EMCYMS.SOAC0103,EMCYMS.SOAC0201A,EMCYMS.SOAC0201B,EMCYMS.SOAC0201C,EMCYMS.SOAC0201D,EMCYMS.SOAC0201E,EMCYMS.SOAC0202,EMCYMS.SOAC0203A,EMCYMS.SOAC0203B,EMCYMS.SOAC0204,EMCYMS.SOPOWER',to_date('20030618055900','YYYYMMDDHH24MISS'),'SYSDATE+1');


prompt 完成時間
select to_char(sysdate,'YYYY/MM/DD HH24:MI:SS') TIME from dual;

spool off


prompt 以上表示已經設定完成.

prompt 備註.
prompt 	1.若要馬上從TC抓資料到 4800,動作如下:
prompt 		CONNECT system/manager@4800	;
prompt 		execute DBMS_REFRESH.REFRESH('EMCYMS.CD1');

prompt 	2.若要殺掉此 Refresh Group
		execute DBMS_REFRESH.DESTROY('EMCYMS.CD1');

prompt 	3.目前 refresh group EMCYMS.CD1 擁有 10 個 member, 若要加入 mamber(ex:EMCYMS.CD011,EMCYMS.CD012), 則執行下列指令 :
prompt 		execute DBMS_REFRESH.ADD('EMCYMS.CD1','EMCYMS.CD011,EMCYMS.CD012',true);

prompt 	4.若要移除 refresh group EMCYMS.CD1 的 member (ex: EMCYMS.CD011), 則執行下列指令 :
prompt        	execute DBMS_REFRESH.SUBTRACT('EMCYMS.CD1','EMCYMS.CD011',false);
prompt 	5.在 oracle 8i(含) 以上,若 table 中有 Long 或 Long Raw 這兩種資料型態者,無法使用此機制.




