spool c:\temp\RemoveMv.log

prompt 起始時間
select to_char(sysdate,'YYYY/MM/DD HH24:MI:SS') TIME from dual;


prompt;注意: 請將 EMCKP 修改成適當的 owner
prompt;注意: 請修改 system 的密碼以及連線的 alias
prompt;注意: 請修改 EMCKP 的密碼以及連線的 alias
prompt;注意: 請修改 DbLink 的內容

CONNECT EMCKP/EMCKP@4800


prompt 為何用 SDTCMIS ? 請連接到 tc, 然後執行 SQL>select * from global_name; 
DROP DATABASE LINK SDTCMIS;



CONNECT system/manager@4800;


execute DBMS_REFRESH.DESTROY('EMCKP.CD1');
execute DBMS_REFRESH.DESTROY('EMCKP.CD2');
execute DBMS_REFRESH.DESTROY('EMCKP.CD3');
execute DBMS_REFRESH.DESTROY('EMCKP.CD4');
execute DBMS_REFRESH.DESTROY('EMCKP.CD5');
execute DBMS_REFRESH.DESTROY('EMCKP.CD6');

execute DBMS_REFRESH.DESTROY('EMCKP.SO1');
execute DBMS_REFRESH.DESTROY('EMCKP.SO2');
execute DBMS_REFRESH.DESTROY('EMCKP.SO3');
execute DBMS_REFRESH.DESTROY('EMCKP.SO4');
execute DBMS_REFRESH.DESTROY('EMCKP.SO5');
execute DBMS_REFRESH.DESTROY('EMCKP.SO6');
execute DBMS_REFRESH.DESTROY('EMCKP.SO7');
execute DBMS_REFRESH.DESTROY('EMCKP.SO8');
execute DBMS_REFRESH.DESTROY('EMCKP.SO9');

prompt CD001 ~ CD010


DROP MATERIALIZED VIEW EMCKP.CD000;

DROP MATERIALIZED VIEW EMCKP.CD001;
DROP MATERIALIZED VIEW EMCKP.CD001A;

DROP MATERIALIZED VIEW EMCKP.CD002;
DROP MATERIALIZED VIEW EMCKP.CD002CM003;


DROP MATERIALIZED VIEW EMCKP.CD003;

DROP MATERIALIZED VIEW EMCKP.CD004;
DROP MATERIALIZED VIEW EMCKP.CD005;
DROP MATERIALIZED VIEW EMCKP.CD006;
DROP MATERIALIZED VIEW EMCKP.CD006A;
DROP MATERIALIZED VIEW EMCKP.CD006B;
DROP MATERIALIZED VIEW EMCKP.CD007;
DROP MATERIALIZED VIEW EMCKP.CD008;
DROP MATERIALIZED VIEW EMCKP.CD008A;
DROP MATERIALIZED VIEW EMCKP.CD008B;
DROP MATERIALIZED VIEW EMCKP.CD008C;
DROP MATERIALIZED VIEW EMCKP.CD009;
DROP MATERIALIZED VIEW EMCKP.CD010;


prompt CD011 ~ Cd020

DROP MATERIALIZED VIEW EMCKP.CD011;
DROP MATERIALIZED VIEW EMCKP.CD011A;
DROP MATERIALIZED VIEW EMCKP.CD011B;
DROP MATERIALIZED VIEW EMCKP.CD012;
DROP MATERIALIZED VIEW EMCKP.CD013;
DROP MATERIALIZED VIEW EMCKP.CD014;
DROP MATERIALIZED VIEW EMCKP.CD015;
DROP MATERIALIZED VIEW EMCKP.CD016;
DROP MATERIALIZED VIEW EMCKP.CD017;
DROP MATERIALIZED VIEW EMCKP.CD018;

DROP MATERIALIZED VIEW EMCKP.CD019;

DROP MATERIALIZED VIEW EMCKP.CD019A;
DROP MATERIALIZED VIEW EMCKP.CD019CD004;
DROP MATERIALIZED VIEW EMCKP.CD019SO017;
DROP MATERIALIZED VIEW EMCKP.CD020;


prompt CD021 ~ Cd030

DROP MATERIALIZED VIEW EMCKP.CD021;
DROP MATERIALIZED VIEW EMCKP.CD022;
DROP MATERIALIZED VIEW EMCKP.CD022CD019;
DROP MATERIALIZED VIEW EMCKP.CD023;
DROP MATERIALIZED VIEW EMCKP.CD024;
DROP MATERIALIZED VIEW EMCKP.CD025;
DROP MATERIALIZED VIEW EMCKP.CD026;
DROP MATERIALIZED VIEW EMCKP.CD027;
DROP MATERIALIZED VIEW EMCKP.CD027A;
DROP MATERIALIZED VIEW EMCKP.CD027B;
DROP MATERIALIZED VIEW EMCKP.CD027C;
DROP MATERIALIZED VIEW EMCKP.CD027D;
DROP MATERIALIZED VIEW EMCKP.CD028;
DROP MATERIALIZED VIEW EMCKP.CD029;
DROP MATERIALIZED VIEW EMCKP.CD030;


prompt CD031 ~ Cd040

DROP MATERIALIZED VIEW EMCKP.CD031;
DROP MATERIALIZED VIEW EMCKP.CD031A;
DROP MATERIALIZED VIEW EMCKP.CD032;
DROP MATERIALIZED VIEW EMCKP.CD033;
DROP MATERIALIZED VIEW EMCKP.CD034;
DROP MATERIALIZED VIEW EMCKP.CD035;
DROP MATERIALIZED VIEW EMCKP.CD036;
DROP MATERIALIZED VIEW EMCKP.CD037;
DROP MATERIALIZED VIEW EMCKP.CD039;
DROP MATERIALIZED VIEW EMCKP.CD040;




prompt CD041 ~ Cd050

DROP MATERIALIZED VIEW EMCKP.CD041;
DROP MATERIALIZED VIEW EMCKP.CD042;
DROP MATERIALIZED VIEW EMCKP.CD043;
DROP MATERIALIZED VIEW EMCKP.CD044;
DROP MATERIALIZED VIEW EMCKP.CD045;
DROP MATERIALIZED VIEW EMCKP.CD046;
DROP MATERIALIZED VIEW EMCKP.CD047;
DROP MATERIALIZED VIEW EMCKP.CD048;
DROP MATERIALIZED VIEW EMCKP.CD048A;
DROP MATERIALIZED VIEW EMCKP.CD048A;
DROP MATERIALIZED VIEW EMCKP.CD049;
DROP MATERIALIZED VIEW EMCKP.CD050;



prompt Cd051 以後

DROP MATERIALIZED VIEW EMCKP.CD051;

DROP MATERIALIZED VIEW EMCKP.CD052;

DROP MATERIALIZED VIEW EMCKP.CD053;
DROP MATERIALIZED VIEW EMCKP.CD054;
DROP MATERIALIZED VIEW EMCKP.CD055;
DROP MATERIALIZED VIEW EMCKP.CD056;
DROP MATERIALIZED VIEW EMCKP.CD057;
DROP MATERIALIZED VIEW EMCKP.CD058;
DROP MATERIALIZED VIEW EMCKP.CD059;
DROP MATERIALIZED VIEW EMCKP.CD060;
DROP MATERIALIZED VIEW EMCKP.CD061;
DROP MATERIALIZED VIEW EMCKP.CD062;
DROP MATERIALIZED VIEW EMCKP.CD063;

DROP MATERIALIZED VIEW EMCKP.CM001;
DROP MATERIALIZED VIEW EMCKP.CM002;
DROP MATERIALIZED VIEW EMCKP.CM003;
DROP MATERIALIZED VIEW EMCKP.CM004;
DROP MATERIALIZED VIEW EMCKP.CM005;


prompt SO001~SO010

DROP MATERIALIZED VIEW EMCKP.SO001;

DROP MATERIALIZED VIEW EMCKP.SO002;
DROP MATERIALIZED VIEW EMCKP.SO002A;
DROP MATERIALIZED VIEW EMCKP.SO003;
DROP MATERIALIZED VIEW EMCKP.SO004;
DROP MATERIALIZED VIEW EMCKP.SO005;
DROP MATERIALIZED VIEW EMCKP.SO006;

DROP MATERIALIZED VIEW EMCKP.SO007;
DROP MATERIALIZED VIEW EMCKP.SO008;
DROP MATERIALIZED VIEW EMCKP.SO009;
DROP MATERIALIZED VIEW EMCKP.SO010;



prompt SO011~SO020

DROP MATERIALIZED VIEW EMCKP.SO011;
DROP MATERIALIZED VIEW EMCKP.SO012;


DROP MATERIALIZED VIEW EMCKP.SO013;
DROP MATERIALIZED VIEW EMCKP.SO014;
DROP MATERIALIZED VIEW EMCKP.SO015;
DROP MATERIALIZED VIEW EMCKP.SO016;
DROP MATERIALIZED VIEW EMCKP.SO017;
DROP MATERIALIZED VIEW EMCKP.SO018;


DROP MATERIALIZED VIEW EMCKP.SO017A;
DROP MATERIALIZED VIEW EMCKP.SO019;
DROP MATERIALIZED VIEW EMCKP.SO020;



prompt SO021~SO030

DROP MATERIALIZED VIEW EMCKP.SO021;

DROP MATERIALIZED VIEW EMCKP.SO022;
DROP MATERIALIZED VIEW EMCKP.SO023;
DROP MATERIALIZED VIEW EMCKP.SO024;
DROP MATERIALIZED VIEW EMCKP.SO025;
DROP MATERIALIZED VIEW EMCKP.SO026;

DROP MATERIALIZED VIEW EMCKP.SO027;
DROP MATERIALIZED VIEW EMCKP.SO028;

DROP MATERIALIZED VIEW EMCKP.SO029;
DROP MATERIALIZED VIEW EMCKP.SO029A;
DROP MATERIALIZED VIEW EMCKP.SO030;
DROP MATERIALIZED VIEW EMCKP.SO030A;



prompt SO031~SO040

DROP MATERIALIZED VIEW EMCKP.SO031;

DROP MATERIALIZED VIEW EMCKP.SO032;
DROP MATERIALIZED VIEW EMCKP.SO032BREAK;

DROP MATERIALIZED VIEW EMCKP.SO033;

DROP MATERIALIZED VIEW EMCKP.SO034;
DROP MATERIALIZED VIEW EMCKP.SO035;
DROP MATERIALIZED VIEW EMCKP.SO036;

DROP MATERIALIZED VIEW EMCKP.SO037;
DROP MATERIALIZED VIEW EMCKP.SO038;

DROP MATERIALIZED VIEW EMCKP.SO039;
DROP MATERIALIZED VIEW EMCKP.SO040;


prompt SO041~SO080

DROP MATERIALIZED VIEW EMCKP.SO041;

DROP MATERIALIZED VIEW EMCKP.SO042;
DROP MATERIALIZED VIEW EMCKP.SO043;

DROP MATERIALIZED VIEW EMCKP.SO044;
DROP MATERIALIZED VIEW EMCKP.SO045;
DROP MATERIALIZED VIEW EMCKP.SO046;
DROP MATERIALIZED VIEW EMCKP.SO052;
DROP MATERIALIZED VIEW EMCKP.SO054;

DROP MATERIALIZED VIEW EMCKP.SO062;
DROP MATERIALIZED VIEW EMCKP.SO063;
DROP MATERIALIZED VIEW EMCKP.SO064;
DROP MATERIALIZED VIEW EMCKP.SO065;
DROP MATERIALIZED VIEW EMCKP.SO066;
DROP MATERIALIZED VIEW EMCKP.SO067;
DROP MATERIALIZED VIEW EMCKP.SO069;

DROP MATERIALIZED VIEW EMCKP.SO071;
DROP MATERIALIZED VIEW EMCKP.SO072;
DROP MATERIALIZED VIEW EMCKP.SO073;


DROP MATERIALIZED VIEW EMCKP.SO074;

DROP MATERIALIZED VIEW EMCKP.SO075;
DROP MATERIALIZED VIEW EMCKP.SO077;
DROP MATERIALIZED VIEW EMCKP.SO079;



prompt SO081~SO100

DROP MATERIALIZED VIEW EMCKP.SO081;
DROP MATERIALIZED VIEW EMCKP.SO082;
DROP MATERIALIZED VIEW EMCKP.SO083;

DROP MATERIALIZED VIEW EMCKP.SO084;
DROP MATERIALIZED VIEW EMCKP.SO085;
DROP MATERIALIZED VIEW EMCKP.SO086;

DROP MATERIALIZED VIEW EMCKP.SO087;
DROP MATERIALIZED VIEW EMCKP.SO088;

DROP MATERIALIZED VIEW EMCKP.SO089;
DROP MATERIALIZED VIEW EMCKP.SO090;

DROP MATERIALIZED VIEW EMCKP.SO091;
DROP MATERIALIZED VIEW EMCKP.SO092;
DROP MATERIALIZED VIEW EMCKP.SO093;

DROP MATERIALIZED VIEW EMCKP.SO094;


DROP MATERIALIZED VIEW EMCKP.SO095;




DROP MATERIALIZED VIEW EMCKP.SO096;
DROP MATERIALIZED VIEW EMCKP.SO097;
DROP MATERIALIZED VIEW EMCKP.SO098;
DROP MATERIALIZED VIEW EMCKP.SO099;
DROP MATERIALIZED VIEW EMCKP.SO100;




prompt SO101~SO130
DROP MATERIALIZED VIEW EMCKP.SO101;
DROP MATERIALIZED VIEW EMCKP.SO102;
DROP MATERIALIZED VIEW EMCKP.SO103;

DROP MATERIALIZED VIEW EMCKP.SO104;
DROP MATERIALIZED VIEW EMCKP.SO105;

DROP MATERIALIZED VIEW EMCKP.SO105A;
DROP MATERIALIZED VIEW EMCKP.SO105B;
DROP MATERIALIZED VIEW EMCKP.SO105C;
DROP MATERIALIZED VIEW EMCKP.SO105D;


DROP MATERIALIZED VIEW EMCKP.SO106;

DROP MATERIALIZED VIEW EMCKP.SO107;
DROP MATERIALIZED VIEW EMCKP.SO108;

DROP MATERIALIZED VIEW EMCKP.SO110;
DROP MATERIALIZED VIEW EMCKP.SO111;

DROP MATERIALIZED VIEW EMCKP.SO112;

DROP MATERIALIZED VIEW EMCKP.SO113;

DROP MATERIALIZED VIEW EMCKP.SO114;

DROP MATERIALIZED VIEW EMCKP.SO115;

DROP MATERIALIZED VIEW EMCKP.SO116;

DROP MATERIALIZED VIEW EMCKP.SO117;
DROP MATERIALIZED VIEW EMCKP.SO118;
DROP MATERIALIZED VIEW EMCKP.SO119;

DROP MATERIALIZED VIEW EMCKP.SO123;
DROP MATERIALIZED VIEW EMCKP.SO124;
DROP MATERIALIZED VIEW EMCKP.SO126;

DROP MATERIALIZED VIEW EMCKP.SO127;
DROP MATERIALIZED VIEW EMCKP.SO128;
DROP MATERIALIZED VIEW EMCKP.SO131;
DROP MATERIALIZED VIEW EMCKP.SO132;
DROP MATERIALIZED VIEW EMCKP.SO133;
DROP MATERIALIZED VIEW EMCKP.SO134;
DROP MATERIALIZED VIEW EMCKP.SO135;


prompt SO200~SO600

DROP MATERIALIZED VIEW EMCKP.SO200;
DROP MATERIALIZED VIEW EMCKP.SO201;


DROP MATERIALIZED VIEW EMCKP.SO301A;
DROP MATERIALIZED VIEW EMCKP.SO301B;
DROP MATERIALIZED VIEW EMCKP.SO302A;
DROP MATERIALIZED VIEW EMCKP.SO302B;


DROP MATERIALIZED VIEW EMCKP.SO303;
DROP MATERIALIZED VIEW EMCKP.SO304;

DROP MATERIALIZED VIEW EMCKP.SO501;
DROP MATERIALIZED VIEW EMCKP.SO501A;

DROP MATERIALIZED VIEW EMCKP.SO501X;
DROP MATERIALIZED VIEW EMCKP.SO502;

DROP MATERIALIZED VIEW EMCKP.SO502X;
DROP MATERIALIZED VIEW EMCKP.SO503;

DROP MATERIALIZED VIEW EMCKP.SO504;
DROP MATERIALIZED VIEW EMCKP.SO508;

prompt others

DROP MATERIALIZED VIEW EMCKP.SOAC0101;

DROP MATERIALIZED VIEW EMCKP.SOAC0102;


DROP MATERIALIZED VIEW EMCKP.SOAC0103;
DROP MATERIALIZED VIEW EMCKP.SOAC0201A;
DROP MATERIALIZED VIEW EMCKP.SOAC0201B;
DROP MATERIALIZED VIEW EMCKP.SOAC0201C;


DROP MATERIALIZED VIEW EMCKP.SOAC0201D;
DROP MATERIALIZED VIEW EMCKP.SOAC0201E;
DROP MATERIALIZED VIEW EMCKP.SOAC0202;
DROP MATERIALIZED VIEW EMCKP.SOAC0203A;
DROP MATERIALIZED VIEW EMCKP.SOAC0203B;
DROP MATERIALIZED VIEW EMCKP.SOAC0204;
DROP MATERIALIZED VIEW EMCKP.SOPOWER;




prompt 完成時間
select to_char(sysdate,'YYYY/MM/DD HH24:MI:SS') TIME from dual;

spool off






