PROMPT *** So122  佣金計算之佣金明細檔 ***

DROP TABLE So122 CASCADE CONSTRAINT;

CREATE TABLE So122 (
	CompCode	Number(3),
	ComputeYM	Varchar2(5),
	BelongYM	Varchar2(5),
	StbNo		Varchar2(20),
	SNo		Varchar2(15),
	BillNo		Varchar2(15),
	Item		Number(3),	
	PeriodId	Number(2),
	WorkerEn1 	VARCHAR2(20),
	WorkerEn1Name 	VARCHAR2(20),
	WorkerEn1Comm   Number(10,2),
	ClctEn	 	VARCHAR2(20),
	ClctEnName 	VARCHAR2(20),
	ClctEnComm 	Number(10,2),
	ClctEnOriPercent Number(8,2),
	IntAccId 	VARCHAR2(20),
	IntAccName 	VARCHAR2(20),
	IntAccComm 	Number(10,2),
	IntAccOriPercent Number(8,2),
	StaffCode 	varchar(1),
	RealStartDate  	Date,
	RealStopDate	Date,
	OPERATOR	VARCHAR2(20),
	UPDTIME		VARCHAR2(20),
	BuyOrRent	Number(1),
	CitemCode	Number(3),
	CitemName	VARCHAR2(20),
	MediaCode	Number(3),
	MediaName	VARCHAR2(20),
	RealAmt	                Number(8),
	PromCode	Number(8),
	PromName	VARCHAR2(20),
	RealDate		Date,
	ShouldDate	Date,
	CustID		Number(8),
	CustName	VARCHAR2(50),
	OrderNo	        VARCHAR2(15),
	CallSelf        Number(1)
       );
