PROMPT *** So133  佣金計算之信用卡付費時之佣金歸屬人員資料異動檔 ***

DROP TABLE So133 CASCADE CONSTRAINT;

CREATE TABLE So133 (
	Seq			Number(10),
	CompCode		Number(3),
	OLDCITEMCODE		Number(3),
	OLDCITEMNAME		VARCHAR2(20),
	NEWCITEMCODE		Number(3),
	NEWCITEMNAME		VARCHAR2(20),
	OLDEMPNO		VARCHAR2(10),
	OLDEMPNAME		VARCHAR2(20),
	NEWEMPNO		VARCHAR2(10),
	NEWEMPNAME		VARCHAR2(20),
	OPERATIONMODE		CHAR(1),
	UpdEn			VARCHAR2(20),
	UpdTime		  	Date
       );

