PROMPT *** CD024B   CA頻道組與實體頻道對照檔 ***

DROP TABLE CD024B CASCADE CONSTRAINT;

CREATE TABLE CD024B (
	ChannelID VARCHAR2(12),
	CodeNo VARCHAR2(10),
	Description VARCHAR2(50),
	ProviderID VARCHAR2(10),
	ProviderName VARCHAR2(50),
	CONSTRAINT PK_CD024B PRIMARY KEY (ChannelID,CodeNo));
